= Extreme Ownership(네이비 씰 승리의 기술) 독서 감상문
Gyeongtae Noh <gt.noh77@sirloin.co.kr>
// Metadata:
:description: 입문교육 1주차 제공 도서의 독서 감상문입니다.
:keywords: leadership, professionalism
// Settings:
:doctype: book
:toc: left
:toclevels: 4
:sectlinks:
:icons: font


오랜만에 개발 서적이 아닌 교양 서적을 읽은 것 같다. 환님에게 소개 받은 네이비씰의 승리의 기술이란 책을 읽었다. 책의 전개는 다음과 같다. 

1. 얘기하고자 하는 topic이 제목으로 나타난다. 
2. 이야기와 관련된 네이비 씰에서의 실제 자신이 겪은 사례 소개
3. 실제로 겪은 경험을 바탕으로 어떻게 기업에 적용할 수 있는지 코칭 사례를 통해 설명
이 전개가 맘에 들었다. 이유는 다음과 같다. 

- topic을 먼저 알려주어 topic에 집중하여 네이비 씰에서의 필자의 경험을 읽을 수 있어 경험으로부터 어떤 메시지를 전달하려고 하는지 알 수 있었다.
- 저게 그럼 내가 앞으로 커리어에서 적용해볼만한 부분이 있을까에 대한 가려움을 기업 사례를 통해 정확히 해소시켜준다. 
이 책을 통해서 배운것은 첫 번째 어떤 조직이든간에 리더의 리더십에 따라 조직의 역량이 결정된다는 것이다. 여기서의 네이비 씰에서의 사례는 매번 1등을 하는 2조와 매번 꼴등하는 6조와
서로 조장을 바꿨을 때 각 2조와 6조에 무슨 일이 일어났는지에 대한 경험을 이야기 했다. 결과는 조장만 바꿨을 뿐인데 매번 꼴등하는 6조는 1등을 했고 2조는 6조에게 선두를 내줬다. 

왜 그랬을까? 정답은 마음가짐에 있다. 2조 조장은 6조의 환경과 조직원들 탓이 아닌 극한의 오너십을 발휘하여 6조의 문제를 해결해 나가기 시작했다. 단합력 정신력 등을 강화시켜 나갔고
이로써 6조는 매번 꼴찌에서 매번 1등을하는 조로 탈바꿈 할 수 있었다. 뿐만아니라 이러한 극한의 오너십은 전파 됩니다. 2조의 경우 조장이 바꼈음에도 좋은 성적을 유지할 수 있었는데
바로 이러한 오너십이 전파되었기 때문이다. 2조는 이미 조장으로 부터 보았던 오너십을 통해 이미 각각의 조원들이 오너십으로 똘똘 뭉친 상태였으며 6조 조장 또한 거기서 이러한 오너십을 전달 받아
결국 2조도 1등까진 하지 못했지만 6조와 치열하게 1등 경쟁을 하는 팀으로 남을 수 있었다. 

나는 그리고 이 구문을 읽고 스스로를 뒤돌아 보았다. 그 동안 많은 팀을 이끌었고 성공도 했지만 실패도 많았다. 그리고 당시에 나는 항상 주변을 탓했다. "단합력이 낮은 동료들", "조직의 역량 부족", "너무 우수한 참여자들"
주변 환경에서 실패 요인을 분석했다. 사실 이 책을 읽고 그랬던 과거가 부끄러웠다. 결국 나는 극한의 오너십을 발휘하여 팀원들을 제대로 이끌지 못한 것이다. 단합력을 높일 수 있는 방법, 조직의 역량을 끌어올릴 수 있는 방법
등을 고민하고 더 나은 팀을 만들기 위해 노력했어야 했던 사실을 깨달았다. 

두 번째로는 책임감에 대한 무게이다. 첫 글에서 필자는 어려운 상황에 처했다. 전투에서 아군끼리의 교전이 발생한 것이다. 아군끼리의 교전은 치명적인 실수이다. 그리고 이러한 실수는 누군가가 결국 책임을 져야한다. 그리고 책에서
필자는 리더로써 아군과의 교전이라는 것을 파악하기전 상황 설명을 듣고 아군과의 교전 가능성을 생각하고 빠른 판단을 통하여 아군끼리의 교전에서 더욱 안좋은 상황이 발생할 수 있던 상황을 막을 수 있었다. 
만약 나였다면 이 상황에서 충분히 팀원들에게 책임을 전가할 수 있고 팀원들에 책임을 먼저 따졌을 것이다. 

하지만 필자는 달랐다. 본인이 책임을 졌다. 이유는 다음과 같았다.

팀을 이끌고 있는 리더이고 지휘 하고 있던 사람도 나이기 때문에 내가 이 모든 것을 책임 져야한다. 

사실 이는 당연하게 느껴질 수도 있지만 엄청난 용기가 필요하고 극한의 오너십이 있어야만 가능한 말이다. 본인이 이 작전의 오너이고 잘못이끌었기 때문에 이런 일이 발생했다고 인정해야한다. 나 또한 리더였을 때 하지 못했던 행동이다. 
이 문장이 앞으로 내 리더로서의 모습을 많이 바꿔놓을 수 있을 것 같다라는 생각이 들었다. 

마지막으로 이러한 사례들이 네이비 씰 같은 군 조직에서만 나오는 것은 아니다. 축구에서 이러한 사례들을 볼 수 있는데 첫 번째로는 리더의 중요성이다. 축구 감독에 따라 팀의 역량이 달라지는 경우가 많은데 토트넘이 대표적이다. 
토트넘은 이전 감독들의 오너십이 부족했다. 주변 환경과 선수들의 비난만을 할 뿐 팀을 성공적으로 이끌지 못했다. 심지어 이로인해 팀의 핵심 선수가 이탈하고 성적도 좋지 않을 정도로 극한의 상황까지 다가갔다. 
하지만 이번에 선임한 새로운 감독은 달랐다. 오너십을 갖고 토트넘의 문제점을 파악했고 지금 팀 선수들을 180도 바꿔놓았다. 또한 본인의 실수를 인정하고 빠르게 선수와 전략을 변경하여 이달의 감독상과 토트넘을 1위로 올려놓는 
엄청난 성과도 만들어내었다. 이것이 바로 리더의 중요성이다. 

두 번째는 책임감의 무게이다. 여기서는 나쁜사례가 있을 수 있다. 보통 팀이 부진하면 먼저 구설수에 올라오는건 선수가 아니다. 감독이다. 이유는 리더로써 팀을 올바르게 이끌지 못한 것이다. 그리고 요즘 시대에 감독이 팀을 바꾸는
사례가 많아지고 있고 선수들은 점점 과학의 발달로 인해 상향 평준화 되고 있다. 심지어 어떤 선수는 감독의 코칭으로 인해 벤치에만 있다가 어느 순간 핵심 멤버로 자리 잡는 경우도 있다. 그리고 대중들은 그것을 알기에 더욱 감독 얘기를
하는 것이다. 이런 것이 리더로써 갖는 책임감의 무게가 아닐까 싶다. 

결국 리더는 좋은 커리어가 될 수 있지만 리더 자체가 커리어가 되는 것이 아닌 어떤 리더였느냐가 중요한거 같다. 그리고 나쁜리더는 나쁜 조직을 만든다라는 것을 꼭 기억하자.
