= Extreme Ownership(네이비 씰 승리의 기술) 독서 감상문
Hwan Jo <hwan.cho@sirloin.co.kr>
// Metadata:
:description: 입문교육 1주차 제공 도서의 독서 감상문입니다.
:keywords: leadership, professionalism
// Settings:
:doctype: book
:toc: left
:toclevels: 4
:sectlinks:
:icons: font

내가 유일하게 사용하는 소셜 미디어는 Facebook이다.
아마 책이 출판된 직후였을 것이다.
Facebook에 접속해 친구들의 소식을 보던 중, 눈길을 사로잡는 난데없는 책 광고가 있었다.
네이비씰은 미국의 정예 특수부대다.
높은 작전 성공률로 유명하며 우리나라의 특수부대인 UDT의 창설에도 큰 영향을 준 군사 조직이다.
그런 유명한 조직 출신의 리더가 말하는 리더쉽이란 어떤 것일지 너무 궁금했다.
그리고 정신을 차려보니 어느새 제목에 낚여 구매 버튼을 클릭하는 내 모습을 볼 수 있었다.

흔히 특수부대라 하면, 목표물을 신속하게 제압하고 각종 장비, 기기를 능숙하게 다루는 완전 초인 같은 느낌을 받는다.
그런데 이 책에서는 특수부대의 가장 중요한 임무란 바로, 무사 귀환이라고 한다.
그리고 거기에 걸맞은 사람이란 바로 신체 능력과 우수한 격투술을 가진 사람보다 어떤 상황에서도 냉정함을 유지할 수 있는 사람이란다.
생각해 보면 그게 더 맞는 말인 것 같다. 특수부대원 한 명을 육성하는 데에는 적지 않은 비용이 드니까.
실패한 임무는 다시 도전할 기회가 주어지기라도 하지만, 죽은 사람을 다시 살릴 수는 없으니 말이다.

특수부대가 투입될 정도의 환경은 전황이 시시각각 급변한다.
이 때문에 작전에 투입되는 인원들은 사전에 훈련하지 않은 상황에서도 멘탈을 유지해야 무사 귀환이라는 궁극 목표를 달성할 수 있다.
그리고 이를 위한 필수 조건이 바로 임무를 빠르고 쉽게 이해시킬 수 있는 설득의 기술, 높은 자율성, 임무에 대한 강력한 동기 등이라고 한다.
특히 나에게 와 닿았던 대목은 바로 임무를 이해시키라는 대목과 상황이 바뀌지 않으면 자신을 변화시키라는 조언이었다.

10 수년간의 직장생활 중 그저 '높은 분들이 하래요.'라고 해서 하는 경우와 내 기안으로 스스로 진행하는 업무의 경험이 떠올랐기 때문이다.
당연히 전자와 후자의 책임감은 차원이 다를 수밖에 없다.
내가 책임을 져야 한다는 단순한 이유 때문이 아니다.
나를 믿어준 상사의 기대감을 배신하면 안 되고, 스스로 실망하지 않아야 하며, 결과로써 나의 탁월함을 세상에 증명해야 하기 때문이다.
후자의 방식으로 일을 할 경우, 야근을 밥 먹듯 해도 지치지도 않고, 주말에도 일 생각만 할 정도로 몰두했던 적이 대부분이었다.
그리고 대부분 좋은 결과를 인정받았다.

또한, 나를 별로 좋게 생각하지 않던 상사와 갈등을 겪은 적도 있었다.
그리고 그 상황을 극복할 수 있었던 것도 결국 내가 스스로 변했기 때문이었다.
당시 그분에게 받은 피드백이란 바로 내가 업무에 몰입하지 못하고 산만하다는 것이었다.
실제로 개인적인 어려움을 겪던 시기였기 때문에 좋지 않은 모습을 보인 것도 사실이었다.
하지만 나는 그 일이 있고 난 뒤 상사에게 그러면 1주일 간격으로 업무를 보고하고 좀 더 자주 피드백을 해 달라는 요청을 했고 받아들여졌다.
물론 힘든 것은 사실이었으나 그 덕에 부정적인 피드백을 받은 지 1년 만에 연봉이 22% 나 오를 정도로 우수 사원으로 인정받을 수도 있었다.
만약 당시에 감정을 이기지 못하고 '내 개인 사정을 이해하려 들지 않는 꼰대' 정도로 상사를 치부했었더라면 결과적으로도 내 경력을 이만큼 발전시킬 수는 없었을 것이다.

비즈니스는 사람의 목숨이나 재산의 심각한 파괴가 없다뿐이지 치열한 생존 경쟁을 하는 엄연한 전쟁터와도 같다.
"너무 오바한다, 뭐 그리 비정하냐, 오글거리는 소리 한다." 같은 분들도 계셨다.
그런데 특히 winner takes all인 소프트웨어 플랫폼 산업은 나에게는 그야말로 전쟁터로 비친다.
승리자에게는 막대한 이익이, 패배자에게는 약간의 가십거리 말고는 그야말로 아무것도 남지 않기 때문이다.
인터넷의 태동기였던 90년대 말에 난무하던 수많은 검색 포털들의 이름을 지금껏 모두 기억하는 사람이 몇이나 될까?
유일한 승자인 Google은 지금 그들의 이름으로 어떤 문화를 선도해 나가고 있나? 
한때 직장인 필독서로 손자병법이나 미야모토 무사시의 오륜서 등을 추천하던 분들도 분명 비즈니스란 다른 의미의 전쟁터라고 생각하셨던 것이리라.
비즈니스라는 전장에서 어떻게 임무를 달성하고 무사 귀환할 수 있을까?
이 관점에서 본다면 이 책도 비슷한 내용이라 생각한다.

컴퓨터 프로그래밍에서도 우수한 프로그래머에게 필요한 건 논리력과 분석력이다.
그리고 이 두 가지 능력이 탄탄해야 우수한 코딩 능력도 보여줄 수 있는 것이다.
프로그래밍으로 치환하자면 신체 능력과 격투술은 코딩 능력, 강인한 멘탈은 논리력 및 분석력이다.
즉, 소프트웨어 엔지니어가 비즈니스라는 전장에서 살아남아 무사히 돌아오려면 강인한 멘탈을 바탕으로 유연하고 능숙한 코딩 능력을 갖춰야 한다고 나름대로 해석해 보았다.
상황이 꽉 막혀 답보 상태라면, 나 자신을 스스로 변화 시켜 새로운 환경에 빠르게 적응하려는 태도도 당연히 필요해 보인다.

1주일 만에 급히 읽은 책 한 권이, 당장 나를 크게 변화 시켜 줄 것 같지는 않다.
하지만 '이해', '자신을 변화' 같은 조언들은 내 인생 경험과 비슷한 부분도 많아 오래 기억할 수 있을 것 같다.
