= Extreme Ownership(네이비 씰 승리의 기술) 독서 감상문
Jaewon Kim <jw.kim@sirloin.co.kr>
// Metadata:
:description: 입문교육 1주차 제공 도서의 독서 감상문입니다.
:keywords: leadership, professionalism
// Settings:
:doctype: book
:toc: left
:toclevels: 4
:sectlinks:
:icons: font

[[intuition-model]]
== 문제 해결의 관점: 직관모델

교육공학을 전공할 때, 문제 해결 패러다임이 "직관모델"로 이동하고 있음을 인지해야 한다는 내용의 강의를 인상 깊게 들은 적 있다. 이전 세대가 맞닥뜨린 문제 상황들은 우리 세대가 겪고 있는 것보다 단순하고 인과관계를 예측하기 쉬운 것들이었다. 따라서 지나간 상황들을 되돌아보고 분석하는 '과거 지향적 접근'만으로도 충분히 해결책을 찾아낼 수 있었고, 실수나 오차를 최소화하기 위해 고안된 '과학적 통제기법'을 얼마나 잘 받아들이는지에 따라 역량이 좌우되는 시절이기도 했다.

반면, 우리 세대가 마주한 문제 상황들은 훨씬 복잡하고 불확실한 세상으로부터 비롯되었다. 불변의 진리일 것만 같았던 이론이 뒤집히기도 하고, 미리 준비해 둔 시스템도 한순간에 무용지물이 될 수 있는 시대에 살고 있기 때문에 문제 해결의 관점을 달리 가져야 한다는 것이 "직관모델"의 요지였다. 『Extreme Ownership』의 내용 역시 불확실성으로 가득 찬 문제 상황을 회피하지 않을 수 있어야 하며, 이론과 체계에 과도하게 의존하지 말아야 함을 강조한다는 점에서 어느 정도 일맥상통한다고 느꼈다. '책상 위에서 개발된 일부 리더십 이론은 실제 전투에서는 쓸모없는 것으로 드러났다'는 책 속의 문구처럼, 강력한 위계질서에 의해 돌아가는 군대마저도 예측 불가능한 실전에서는 구체적인 매뉴얼보다 직관적인 사고방식을 따르게끔 지도하고 있었다.

개발자라는 직책도 기술을 무기로 사업적인 문제를 해결하는 입장이라고 생각한다. 아직은 경력이 부족해서 나도 모르게 '정형화된 테크 트리'에 갇힌 채로 지난 문제들을 상대해 오진 않았나 돌아보게 된다.

[[ask-why]]
== 자기 설득의 기술: 왜?

그래도 어떤 일을 시작하는 것에 있어 "왜?"라는 질문이 중요하다고 생각하는 편이라, 승리의 원칙 중 하나였던 '무엇을 해야 하는지 말하기보다 왜 해야 하는지를 설명하라'에 많은 공감이 갔다. 개인적으로는 "왜?"에 대한 답에 공감한 팀원들이 같은 목표를 바라보며 나아갈 때 생기는 문제 해결력을 믿는 편이다. 축구에서도 선수들의 전술 이해도가 높은 팀이 더 훌륭한 경기를 펼칠 수 있는 것처럼, 오너십을 가진 팀원으로서 맡은 일에 대한 이해도를 충분히 갖춰야지만 팀이 목표를 달성하는 것에 효율적으로 기여할 수 있기 때문이다.

새롭게 팀에 합류하는 입장에서 아직 모르는 게 훨씬 많은 상태다. "왜?"에 대한 답을 얻고, 사업에 대한 이해도를 높이기 위한 노력이 특히 필요한 때다.

[[extreme-ownership]]
== 극한의 오너십

책의 제목이기도 한 "극한의 오너십"의 첫인상은 다소 버거워 보였다. 팀의 약한 부분을 쳐 내고, 더 나은 팀을 만들려는 노력을 지속해야 하며, 팀의 업적은 기꺼이 부관이나 팀원들에게 돌려야 한다. 이상적인 리더의 자세이기는 하나, (박명수가 유재석처럼 되기는 어렵듯이) 갑자기 무한한 책임감과 그에 따르는 의사결정들을 스스로 떠안아야 한다고 생각하니 어려워 보이는 게 당연하지 않을까?

다만 "실패의 오너가 되는 것"부터는 도전해 볼 수는 있을 것 같다. 역시나 경력이 부족한 관계로 잘했던 때만큼이나 실수도 잦았다. 다른 사람을 탓할 상황이 있지도 않았지만, 그렇다고 매 순간 실수에 떳떳했던 것도 아니었다. 실수를 바로잡는 것만으로 끝나는 게 아니라, 다음에 더 잘할 방법에 대해서 고민하고, 그 결과를 팀원들에게 공유하거나 기록해 두는 습관부터 하나씩 시작해 봐야겠다.