= Extreme Ownership(네이비 씰 승리의 기술) 독서 감상문
WongueShin <wg.shin@sirloin.co.kr>
// Metadata:
:description: 입문교육 1주차 제공 도서의 독서 감상문입니다.
:keywords: leadership, professionalism
// Settings:
:doctype: book
:toc: left
:toclevels: 4
:sectlinks:
:icons: font

# 상황을 주도한다는 의미.
책을 읽으며 반복적으로 들었던 생각이 회사에 입사하기 전 재학시절부터 꾸준히 생각했었던 주제에 대해서 책의 저자와 내생각을 주고받으며 토론하는듯한 느낌이 들었다. +

몇 년 동안 학교를 다니고, 공부하며 전문 분야를 변경하고, 취업 준비를 하며 반복적으로 발견했었던 부분은 바로 사람들은 생각보다 능력도 크게 보면 차이가 없고, 노력또한 모두 비슷비슷하게 한다는 사실이다.

본인이 의도한 목표를 달성하는, 혹은 실패하는 정말 핵심적인 요인은 타고난 능력이 부족하다거나 노력을 열심히 하지 않아서가 아니라는 생각이다. +
물론, 노력이나 타고난 재능이 필요가 없다는 말이 아니다. 이러한 부분은 남들과 시장에서 경쟁을 *시작* 하기 위한 준비물이라 할 수 있다. +

그러면 어떠한 변수가 목표성취의 핵심이라고 말할 수 있냐면, 내 경험으로는 메타인지가 그 핵심이 아닐까 생각한다. +
*목표를 성취한다는 과정* 은 나에겐 운동장 어딘가에 있는 *바둑돌* 을 하루에 *한 번* 만 건드려서 내가 원하는 장소로 이동시킨다는 이미지로 그려진다. +
바둑돌을 튕긴다는 행위가 공부한다던지, 목표를 위해 운동을 한다는 등 노력으로 이해할 수 있다. +

하지만, *여기서 재밌는 부분은 목표 지점에는 깃발이 꽂히지 않다는 점이다.*:: 
* 어디가 목표 지점이라고 누가 알려주지도 않으며 
* 도착했다 생각했는데 사실은 중간 과정일 수도
* 아니면 아예 다른 곳을 왔을 수도
* 내 마음과 얻게 되는 정보, 상황의 변화에 따라 실시간으로 목표지점이 바뀌기도
* 심지어는 없어질 수도 있다는 점이다. 

이러한 불확실성은 사람을 불안하게 만든다.::
이럴 때, 일반적으로는 더 이상 목표 설정에 관련한 부분을 생각하지 않고, 지나치게 단순화하고 검증되지 않은 가설을 순진하게 믿고, 그저 당장 할 수 있는 일을 전력으로 하며, 자신은 열심히 미래를 준비하고 있다고 위안을 얻고 싶어 하는 성향을 가지고 있음을 발견했다. +

인생에서 무엇을 성취한다는 부분은 무수한 벡터의 합을 구하는 것과 비슷해서,::
긴 시간에서 가장 핵심적인 요소는 각 구성하는 벡터의 크기가 아니라, 하위 벡터들의 방향이 얼마나 의도하는 목표에 근접하는지가 결정한다.

*그리고* 일반적으로 우리가 원하는 목표는 그 목표가 단기적으로 달성할 수 없기 때문인 경우가 많다. 방향을 일치시키는 능력은 *생각을 생각하는 능력* 인 메타인지가 관여하는 부분이다.

그리고 이러한 요건을 모두 충족시켰을 때::
 사람은 필연적으로 상황에 주도적인 태도를 가지게 된다. +
 통제 가능한 변수들을 최대한 설정해서 내가 원하는 목표에 가장 가까운 방향으로 결과를 얻어야 하기 때문이다.


## 저자가 말하는 극한의 오너십
저자가 책 안에서 반복적으로 강조하는 극한의 오너십을 가지라는 의미는::
 위에 서술한 나의 언어로 다시 정리하면, 
 * 목표를 정말 명확하게 설정하고
 * 현 상황과 목표의 괴리를 파악한 뒤
 * 주어지는 상황 중에 통제 가능한 변수를 원하는 목표에 가까워지는 방향으로 설정하라는 말이 될 수 있을 것 같다.

이 부분이 저자가 말하고 싶었던 *핵심 주제* 이고, 나머지 지면에서는 이러한 과정을 잘못 이해하거나, 미처 놓칠 수 있는 디테일적인 부분을 설명하는 지문으로 받아들였다. 

## 실수하기 쉬운 부분들

### 1.(불필요한) 자존심 내려놓기
개발자라는 직업 특성상 타 직군에서 진입하기 어려운 기술적 장벽이 있는 부분과,나의 타고난 성향의 환장의 조화 때문에, 나는 비대한 에고를 가지기 쉬워지는 부분이 있다는 걸 인지하고 있다.

이전부터 이 *인정욕구* 라는 것이 항상 골칫거리였던 게,
가끔은 성장의 강한 동기부여로 동작하게 되어 타인보다 짧은 시간 동안 좋은 결과를 보여주는 장점 중 하나가 되기도 하지만 순전히 기뻐할 수만은 없는 이유가 차마 지면에 적기 부끄러운 경험을 너무 많이 겪었고 지금도 극복하지 못하는 단점이라 생각한다.

정직이 가장 최선의 전략이라는 것은 십분 동감하지만, 같은 사실을 표현할 때도 장점에 집중하며 기술하면 성공적인 PR이 될 수 있는 부분일 텐데 어떤 선이 성공적인 PR과 허풍을 구분하게 되는 걸까. 아직은 어려운 부분이다.

완벽한 해결책은 존재하지 않지만, 주기적인 회고와 자기반성으로 나의 객관적인 위치와 나의 인식을 동기화 하는것이 그나마 미봉책이 아닐까 생각하고 있다.

### 2. 명확하지 않으면 이해하지 못한 거다.
1번의 자존심 내려놓기와 만나면 정말 파멸적인 결과를 불러오게 되는 약점이 될 수 있는 부분이다.

한 문장으로 정의내릴수 없다면 이해하지 못한 것이다라는 말이, 이전에 사실은 잘 모른다는 점을 알고 있었지만, 그 사실을 인정하기 싫어서 너무 큰 손해를 봤었던 많은 실수를 생각하게 했었다.

### 3. 우선순위 파악
상황이 모호할때, 목표를 기반으로 우선순위를 파악하고, 우선순위 기반으로 작업을 하는 편이 모호하고 복잡한 상황을 명료하게 만든다는 사실을 이전부터 체감을 하고 그렇게 작업을 하고자 노력을 해왔었던 편이라고 생각한다. 하지만 책에서 저자가 말하는 부분 중에, 우선순위가 상황의 변화와 또 새로운 필요에 따라 실시간으로 수정될 수 있는 절대적인 부분이 아니라는 것은 이전까진 깊이 생각하지 못했었던 부분이었다.

### 4. 지휘권 분할
팀 구성원 모두에게, 자기가 맡은 분야에서의 오너십을 함양시키고, 그러한 과정이 충분히 진행되었을 때 리더는 자신이 가진 지휘권 중에 디테일적인 부분을 위임하고 리더 본연의 위치에 걸맞게 맥락적인 부분과 전술적인 판단에 집중하는 것이 적은 인원으로 효율적인 의사결정과 높은 업무 생산성을 달성할 수 있는 최적의 팀 구성 체계라는 것이 이 책의 저자가 주장하는 해심 요소라 생각된다. +
우수한 인재가 무수히 많이 지원하는 네이비씰에서는 이러한 방식으로 팀을 구성하고, 부적응자는 내치는 방식으로 팀을 조직할 기회가 있었겠지만, 과연 지원인력이 무한하지 않은 다른 사기업체에서 이와 같은 목적으로 팀을 구성하기에는 너무나 많은 인력 채용 비용을 감당할 수 있는지에 대한 고민이 필요하지 않나 생각한다. +

관련 업무를 무리 없이 수행할 수 있는 능려과 더붙어 팀의 컬처핏에 맞는 개성과, 그걸 모두 함유하고 그 이상의 맥락적인 전술 가치를 파악하고자 노력하는 신입사원이라... 

물론 나는 팀에 입사한 이상 이와 같은 목표를 가지고 성장하고자 하지만, 이러한 인재상이 과연 쉽게 찾을 수 있는 건지, 아니면 성장시킨다고 달성할 수 있는 현실적인 목표인 건지는 아직 쉽게 동의하기는 힘든 부분이다. +
물론 일반적이지 않을 꺼로 생각하고, 이러한 목표를 달성해 능동적인 오너십을 향유하면 나의 전반적인 커리어에서 큰 도움이 될 자산이라 생각이 된다.

저자가 설명한 잘 조직된 팀에서는 팔로워가 보스의 지시를 기다리는 것만이 아닌, 주도적으로 자신이 파악한 업무 범위 내의 한도에서 팀에게 목표를 제안하는 방식은 이전의 업무지시가 내려오길 기다렸던 방식보다 훨씬 더 매력적인 업무체계라 생각이 들었다.

### 5. 윗사람을 이끄는 법

아주 신선한 관점의 오너십에 대한 설명이었다. +
살다 보면 가끔 정말 처세술의 달인이라는 이름이 아깝지 않은, '타고났다'는 사람들이 가끔 보여주는 탁월함의 편린을 찾은 기분이었다. +
현시점의 나는 이러한 방법론은 자주 사용할 일은 없을 거 같다만, 나의 머릿속의 GC가 이 정보를 가져가지 못하도록 꾸준히 기억하면서 참조 카운트를 유지할만한 가치가 있는 지식이었다.

## 책에대한 총평.

책을 읽으며 몰랐던 지식을 많이 알게 되었다기보단, 암묵지로 어렴풋이 이렇지 않을까 추측했었던 가정들을 언어로 구체화 시켜 실적용을 할 수 있도록 문서화를 하는듯한 경험이었다. +
충분히 권장 도서로 선정될만한 가치가 있는 도서라 생각이 들면서 1분기 후, 1년 후에 이 문서와 책을 다시 복기하면서 과연 이러한 내용을 내가 충분히 실정에 반영하였는지를 체크를 할 때 이 감상문이 완성되지 않을까 생각한다.
