= Extreme Ownership(네이비 씰 승리의 기술) 리뷰
yh.j@sirloin.co.kr - <yh.j@sirloin.co.kr>
// Metadata:
:description: 입문교육 1주차 제공 도서의 독서 감상문입니다.
:keywords: leadership, professionalism
// Settings:
:doctype: book
:toc: left
:toclevels: 4
:sectlinks:
:icons: font

== 책 소개
조코 윌링크라는 네이비씰 장교가 이라크 라마디 파병을 통해 얻은 오너십에 대한 인사이트를 보여주는 도서이다. 해당 인사이트는 상명하복이 중요한 군 내에서 통하는 리더십이 아니라 형태에 구애 받지 않게 모든 조직에 도움이 되는 내용으로 실제 조직 생활, 그리고 삶을 나아가는 방향에 있어서 많은 인사이트를 제공한다.

== 오너십이란 무엇인가?
책에서 리더십, 오너십을 정의하고 이를 토대로 여러 문제를 해결하는 사례들을 보여준다. 두 용어는 “책임”이라는 본질이 같고 오너십은 결국 리더십(구성원들이 믿고 따르느냐)보다 더 본질적인 핵심이라 파악하여 오너십에 대해 고민하고 정의하였다. 책을 통해 이해한 오너십을 한마디로 정의하자면  “어떤 목표나 소속된 조직을 위해 온전히 책임을 지려하고 이를 위해 할 수 있는 모든 것을 다 하였느냐”였다. 책에서는 리더뿐만 아니라 중간 책임자 그리고 구성원들에게도 오너십이 필요하다고 말한다. 내가 맡은 목표(혹은 업무)를 달성하기 위해 상급자와 커뮤니케이션을 하기 위해 노력했는지, 이를 위해 상급자의 입장을 이해하였는지, 혹은 구성원들에게 업무를 주었을 때 업무의 목적과 궁극적 목표를 제대로 얼라인했는지도 결국 위 오너십을 제대로 이해하고 이행하였는지에 따라 달라진다고 생각한다. 위 오너십을 통해 과거 사업을 했을 때 나의 태도, 커뮤니케이션 방식에 대해서 아래와 같이 복기하였다.

== 나는 팀의 목표를 구성원들과 얼라인하였는가?
입사 3달 전 약 10년 간 식당에서 점장을 한 친구와 같이 맥주집을 창업하는 사이드 프로젝트를 진행하였다. 나는 상권분석부터 finance modeling, 그리고 투자유치를 통해 헬스장, 피자집 등 로컬 사업을 런칭하는데 자신감이 있었고 operation이 가능한 인력만 있으면 성공한다는 자신감으로 친구에게 동업을 제안하였다. 말 그대로 이런 경영관련 지식이 없는 친구였기에 최대한 모든 것을 알려주려고 시간과 노력을 쏟았고 동기부여를 하였다. 그러나 내가 열심히 알려준 것들은 제대로 숙지되지 않고 3일 노력하면 끝낼 일을 3주가 넘도록 미루더니 마지막에 “프렌차이즈라서 하기 싫다”라는 말을 남기고 친구가 스탑을 선언하였다. 

처음에는 친구에게 굉장히 실망을 했다. “너의 잠재력 하나만 보고 내가 시간과 정성을 쏟았고 초기투자금을 지원해주는데 어떻게 이렇게 노력도 안하지?” 라고 생각하며 친구의 열정이 부족하다고 속으로 실망했었다. 그러나 이 책을 읽으면서 다음 2가지 생각이 들었다.
 1) 우리의 목표를 명확히하고 친구에게 이를 얼라인하였는지? 
 2) 업무를 알려주었을 때 업무의 목적이 무엇인지 명확히 설명해주었는지
 3) 업무가 제대로 안되어있을 때 그 근본적인 원인을 생각해봤는지.

나는 애초에 나를 위한 목표를 세웠고, 그렇기 때문에 친구는 목표가 무엇인지 조차 인지할 수 없었다. 또한 업무의 목적을 설명하지 않고 “해야한다”라는 책임감만 심으려 했으며 업무가 제대로 안되어있을 때 단순히 노력할 줄 모르는 사람이라고 생각했다. 나중에 다른 친구를 통해  “덜컥 겁이나서 진행할 수 없었다”라는 그 친구의 솔직한 피드백을 전해 들었고 당시에는 배포가 없다고 실망했지만 책을 읽고 나서 위 같은 실수를 통해 남탓만 하던 나를 진심으로 반성하게 되었다. 진심으로 친구가 사업을 통해 무엇을 원하는지 더 들었어야했고 그 목표를 이루기 위해 무엇을 해야하는지 차근히 이해시켜야 했는데 나의 오만한 자존심으로 인해 친구의 첫 도전을 망가트렸다.

== 나는 오너십을 가지고 사업을 운영하였는가?
1년동안 창업을 하면서 많은 일들을 겪었다. 그 중 기억에 남는 것은 헬스장 창업 때 투자유치담당자와의 다툼이었다. R&R을 나눌 때 투자자 리스크를 담당하는 동료가 있었고 나는 운영 총괄 담당자였다. 런칭 전 건물이 경매에 넘어가는 이슈, 그로 인해 런칭일자가 미뤄지고 예상했던 임대료가 200만원 가까이 오른 이슈 그리고 이런 문제들을 통해 한 몫 하려는 1% 지분 소유자인 건물 관리인단의 내용증명서 공격 등으로 인해 투자담당자가 투자자들과의 커뮤니케이션을 위해 나에게 많은 자료들을 요구했었다. 당장 런칭을 준비하고 변호사들을 만나면서 시간이 정말 빠듯하였기에 많은 스트레스를 받았고 이로 인해 운영팀과 투자유치팀으로 파가 갈려 분쟁이 시작되었다. 결국 문제들은 해결했지만 복기하였을 때 3가지가 부족한 거 같았다.

. 투자를 담당하여 리스크를 진 동료의 입장을 이해하였는가?
. 현장의 상황을 이해시키기 위해 동료와 충분한 대화를 하였는가?
. 결국 우리 둘은 같은 목표를 가지고 있다는 것을 계속 생각하였는가?

당시 위 셋 중 어떤 생각도 할 수 없었기에 서로 상처를 주게되었다. 상대방을 이해하려고 노력했다면 4주동안 진행됬던 갈등은 1시간 안에 해결될 수 있었다고 생각한다. 나는 서류를 요구하는 동료를 현장을 모르는 사람이라고 비난하였고, 그 요구사항을 이행하기 위한 데이터가 잘못되었으면 현장에서 일하는 구성원들에게 책임을 물었다. 오너십을 가졌다면 서류에 대한 책임은 현장인력이 아닌 내가 온전히 받았어야했고 투자리스크를 지고 있는 동료의 상황을 이해하고 들어주면서 현장의 상황을 이해시키려 노력했어야 했다.

== 나는 앞으로 어떻게 일해야하는가?
오너십을 가지고 업무를 진행할 때는 아래 3가지를 핵심이라고 생각한다.
내가하고 있는 업무의 목적과 이유를 알고 있느냐
업무들의 우선순위를 제대로 파악하고 있느냐
업무에 대한 책임을 온전히 받으려는 태도를 가지고 있느냐?

위 3가지를 생각하고 업무를 진행하면 팀의 목표를 성취하는데 크게 기여할 수 있다고 생각하고 나아가 리더가 되었을 때 구성원들이 믿고 따르는 사람이 될 수 있다고 생각한다.
