= Extreme Ownership(네이비 씰 승리의 기술) 독서 감상문
youjin <howyoujini@sirloin.co.kr>
// Metadata:
:description: 입문교육 1주차 제공 도서의 독서 감상문입니다.
:keywords: leadership, professionalism
// Settings:

# 네이비 씰 승리의 기술


*** 21세기에 살고 여자라는 이유로 전쟁 속 군대를 경험해보지 못해 목숨을 건 팀워크가 무엇이고, 그 팀이 주는 영향력과 결과에 대해 진지하게 생각해본 적은 없었다. +
그래서 솔직히 이 책을 읽으면서도 전쟁에 대한 묘사들을 정확하게 공감할 수 없었다. +
네이비씰을 바탕으로 한 영화, <론 서바이버> 를 유튜브에서 따로 찾아보고 전체적인 줄거리와 영상을 보며 '네이비씰' 부대에 대해 좀 더 공감할 수 있었다. +

*** 사실 "전쟁"이야 말로 승리와 실패가 분명하다. +
그리고 그 승리와 실패는 또 언제 뒤바뀔 지 알 수 없다. +
수 없이 싸워서 "이겨야"하는 전쟁통에서 최고의 팀워크는 무엇일까? +
어떻게든 체력과 경제적 지원이 바쳐준다면 한두번은 전쟁에서 승리할 수 있을 것이라고 생각한다. +
하지만 몇 번의 전쟁 이후 팀원들이 정신적으로 피폐해져 있는 상태라면 그래도 전쟁에서 승리할 수 있을까?+

*** 이 책을 다 읽어갈 즈음에 왜 이 책에 대한 감상문을 쓰라고 하셨는지 좀 더 명확하게 알 수 있었다. +
과연 성장가능성이 있는, 희망적인 팀은 무엇이 다를까? 리더십이란 무엇일까? +
그럼 리더란 무엇이고, 팔로워는 무엇일까? +
그들의 역할은 무엇이고 어떻게 하면 그들 모두가 팀에게 선한 영향력을 줄 수 있을까? +
이런 다양한 물음을 가지고 나는 이 책을 읽을 수 있었다. +
네이비씰에서 리더의 역량으로 "극한의 오너십"이라는 말을 강조하는 듯 보였다. +
자신의 업무 이외에도 업무에 미치는 모든 일까지 자신의 책임이라고 생각하고 문제를 "해결"하는데에 초점을 두는 극한의 오너십을 가지는 것은 정말로 쉽지 않은 일이다. +
나의 성격과 일하는 태도로 보았을 때 자주 팀장, 리더 역할을 맡은 적이 많았다. +
이런 경험 속에서 "극한의 오너십"을 가지고 팀을 이끄는 것은 정말 힘들고 어려운 일이라고 느꼈다. +
팀장이라고 해서 힘들지 말라는 법은 없기에 나를 잘 컨트롤 하면서도 다른 사람들을 컨트롤하며 팀 자체도 이끌어 성장시켜야하기 때문이다. +
책 53페이지에서는 - 어떤 팀이나 조직을 막론하고 성공과 실패의 책임은 모두 리더에게 귀속된다. +
그러므로 리더는 남을 비난해서는 안된다. +
자기 세계에 속한 모든 것의 오너여야 한다. +
리더는 실패와 실수를 인정하고, 그것에 대한 오너십을 갖고 다음번 계획을 성공적으로 이끌 방법을 찾아내야 한다. - 라고 한다.+