= Extreme Ownership(네이비 씰 승리의 기술) 독서 감상문
youjin <howyoujini@sirloin.co.kr>
// Metadata:
:description: 입문교육 1주차 제공 도서의 독서 감상문입니다.
:keywords: leadership, professionalism
// Settings:
:doctype: book
:toc: left
:toclevels: 4
:sectlinks:
:icons: font

# 네이비 씰 승리의 기술, 극한의 오너십


21세기에 살고 여자라는 이유로 전쟁 속 군대를 경험해보지 못해 목숨을 건 팀워크가 무엇이고, 그 팀이 주는 영향력과 결과에 대해 진지하게 생각해본 적은 없었다. 그래서 솔직히 이 책을 읽으면서도 전쟁에 대한 묘사들을 정확하게 공감할 수 없었다. 네이비씰을 바탕으로 한 영화, <론 서바이버> 를 유튜브에서 따로 찾아보고 전체적인 줄거리와 영상을 보며 '네이비씰' 부대에 대해 좀 더 공감할 수 있었다. +

사실 "전쟁"이야 말로 승리와 실패가 분명하다. 그리고 그 승리와 실패는 또 언제 뒤바뀔 지 알 수 없다. 수 없이 싸워서 "이겨야"하는 전쟁통에서 최고의 팀워크는 무엇일까? 어떻게든 체력과 경제적 지원이 바쳐준다면 한두번은 전쟁에서 승리할 수 있을 것이라고 생각한다. 하지만 몇 번의 전쟁 이후 팀원들이 정신적으로 피폐해져 있는 상태라면 그래도 전쟁에서 승리할 수 있을까? +

이 책을 다 읽어갈 즈음에 왜 이 책에 대한 감상문을 쓰라고 하셨는지 좀 더 명확하게 알 수 있었다. 과연 성장가능성이 있는, 희망적인 팀은 무엇이 다를까? 리더십이란 무엇일까? 그럼 리더란 무엇이고, 팔로워는 무엇일까? 그들의 역할은 무엇이고 어떻게 하면 그들 모두가 팀에게 선한 영향력을 줄 수 있을까? 이런 다양한 물음을 가지고 나는 이 책을 읽을 수 있었다. 네이비씰에서 리더의 역량으로 "극한의 오너십"이라는 말을 강조하는 듯 보였다. 자신의 업무 이외에도 업무에 미치는 모든 일까지 자신의 책임이라고 생각하고 문제를 "해결"하는데에 초점을 두는 극한의 오너십을 가지는 것은 정말로 쉽지 않은 일이다. 나의 성격과 일하는 태도로 보았을 때 자주 팀장, 리더 역할을 맡은 적이 많았다. 이런 경험 속에서 "극한의 오너십"을 가지고 팀을 이끄는 것은 정말 힘들고 어려운 일이라고 느꼈다. 팀장이라고 해서 힘들지 말라는 법은 없기에 나를 잘 컨트롤 하면서도 다른 사람들을 컨트롤하며 팀 자체도 이끌어 성장시켜야하기 때문이다. 책 53페이지에서는 "어떤 팀이나 조직을 막론하고 성공과 실패의 책임은 모두 리더에게 귀속된다. 그러므로 리더는 남을 비난해서는 안된다. 자기 세계에 속한 모든 것의 오너여야 한다. 리더는 실패와 실수를 인정하고, 그것에 대한 오너십을 갖고 다음번 계획을 성공적으로 이끌 방법을 찾아내야 한다." 라고 한다. 나를 인정하고 부족함을 이해하며 팀의 문제'해결'위해 힘을 쓰는 것이 진정한 리더라는 것이다. +

다음으로 인상깊었던 내용이 있는데, 리더는 목표를 위해 현재 어떤 것이 문제이고 이 문제 때문에 어떤 다른 문제가 blocker가 되었으며 문제를 해결하기 위한 원인을 파악해야한다는 점이었다. 결국 문제를 큰 그림으로 바라보고 전술적 임무 뿐만 아니라 전략적 임무에 어떻게 기여하는지 팔로워들(팀원) 에게 설명을 잘 해주고 이해시켜준다면 팔로워들도 리더를 신뢰하고 잘 따를 것이라고 생각한다.나는 리더일 때가 더 많았지만 주니어 소프트웨어 엔지니어로써는 앞으로 성장해야하는 부분이 더 크기 때문에 팔로워일 때가 더 많을 것으로 예상하고 있다. 이 책을 볼 때에도 리더였던 과거의 경험에 대입하여 읽기도 했지만 팔로워의 입장에서도 책에서 주는 메세지를 생각해볼 수 있었다. 리더보다는 팔로워의 입장이 사실 더 마음편하고 업무를 대할 때 쉬운 것은 사실이다. 극강의 오너십은 리더에게 요구되는 조건이라고 한다면, 그만큼 팔로워가 져야할 책임이 덜어진다는 뜻이 될테니까. 하지만 팀의 발전, 팀의 소속감을 위해서는 극강은 아니겠지만 팔로워도 오너십을 가져야 한다고 생각된다. 이 책에서는 "책임의 선순환"을 통해 이를 실천하는 것으로 보인다. +

"책임의 선순환"은 그럼 어떻게 일어날까? 사람들의 심리를 파악하면 알 수 있다. 내가 먼저 책임지는 자세를 보였을 때 상대가 더 책임지는 자세로 나올 가능성이 크다. 이를 전제한다면 리더가 극한의 오너십을 보여줄 때 팔로워들도 더욱 역할에 책임지는 자세를 가질 가능성이 크다는 것이다. 결국은 그럼 팀 내에서 "책임의 선순환" 구조의 문화가 만들어진다면 팀 내의 connection이 더욱 단단해지고 업무의 성과도 상승세를 보일 것이라 예상한다. 하나의 조직이라는 것은 서로가 서로에게 의지하고 도움이 되어주며 받을 수 있을 때 더 성장할 수 있다고 생각한다. 서로가 서로를 이해하기 힘든 부분이 있더라도 자신의 고집과 경험을 내려놓고 상대를 인정하고 온전히 받아들이며 소통한다면 앞으로 있을 팀의 성장에도 좋은 영향력이 있을 것이다. +

그럼, 우리 팀에서 나의 역할은 무엇일까? 우선 주니어 프론트엔드 개발자로써 최선을 다해야 할 것이다. 다른 팀원들과의 소통을 위해 그들의 업무에 대해서도 지속적인 관심을 가지고 어떻게 하면 내가 도움이 될 수 있을지 생각해볼 것이다. 결국 어떤 끝을 위해 우리가 일하고 있는지 목적의식을 가지고 "도구"에만 의존하지 않고 활용해나가며 더 나은 프로덕트를 만들기 위해 폭넓은 사고를 가지려 노력해야겠다. +

앞으로 만들 우리의 프로덕트가 너무 기대되며 나 개인도 얼만큼 성장해나갈지 너무 기대가 되는 바이다. +