== 네이비씰 성공의 기술을 읽고

. 극한의 오너쉽
* 리더는 책임을 남에게 전가해서는 안된다. 성공과 실패의 책임은 모두 리더에게 귀속된다.
** 실패할 수 밖에 없었던 이러저러한 불가피한 이유가 있었더라도 팀의 리더는 그것을 캐치하고 팀의 목표에 걸림돌이 되지 않도록 대응을 할 수 있었어야한다.
** 실패를 하더라도 그 실패의 대한 원인을 파악하고 다음 실패의 원인이 되지 않도록 해야한다.

* 극한의 오너쉽은 전파된다.
** 팀의 목표를 이루는 과정에서 팀원의 누군가의 실수가 있었더라도 그것은 사전에 실수의 가능성을 고려하지 못한 리더의 책임이 된다.
*** 리더가 팀원의 실수까지 책임을 지게 될 때, 팀원들도 리더의 오너쉽에 영향을 받게 된다.
*** 이것은 말단 팀원에게까지 전파되고, 하나된 팀으로서 문제를 해결하려고 노력하게된다.
*** 이 부분의 내용을 읽으면서 짧지만 환님과 팀장님의 모습이 오버랩되었다.
(정확히는 어떤 주제인지 기억은 안나지만) 이것은 본인의 잘못이고 본인이 잘했어야하는 것이라고 말씀해주시던 적이 있었다. +
사실 당시에 살짝 신선하게(?) 느꼈었던 순간이었는데 책을 읽으면서 ‘이러한 맥락일수도 있겠구나’ 라고 느낄 수 있는 부분이었다. +
팀원이 잘못을 하더라도 무작정 질책을 하는 것은 팀원의 자신감을 위축되게 만들고 다음 업무에 있어서 행동 반경을 줄이게 만들어서 좋은 업무 효율을 내지 못할 것이라는 생각이 들었다. +
반대로 팀원이 한 잘못인데 다른 누군가가 자발적으로 책임을 진다면 그 누군가에게 미안함과 실수하지 말아야겠다라는 마음 그리고 팀내에서 으쌰으쌰(?)하는 분위기가 생기지 않을까 싶다. +
대신 그 팀원도 기본적인 소양은 있어야겠는 생각이 들었다. +
’오늘도 다른 사람이 책임져주어서 살아남았다! 아싸^^’ → X +
’내 실수로 누군가에게 신세를 졌다. 같은 실수는 다시 하지 말도록 주의하고 나도 그 분처럼 극한의 오너쉽을 가질 수 있도록 해야겠다.’ → O

** 극한의 오너쉽을 체화한 리더가 팀에 높은 수준의 성과를 요구할 때 명심할 것이 있다. 목표한 수준은 리더가 뭐라고 말하느냐에 따라 정해지는 것이 아니라 어떻게 행동하느냐에 의해 결정된다. - 80p

. 나쁜 리더의 부정적인 태도는 팀 전체에 전파된다.
* 리더의 부정적인 태도는 팀전체에 전파되고 팀이 더욱 나아지고 발전할 가능성을 가로막는다.
** 리더가 팀원 혹은 외부로 실패의 원인을 돌린다면, 팀의 수준을 그 자리에 안주시키고 그 분위기는 팀 전체로 전파되어 팀원 각자가 각자도생의 길을 찾게 된다.
** 극한의 오너쉽이 전파되듯 부정적인 태도 또한 전파된다.

. 무엇을 해야하는지 보다 왜 해야하는지를 설명해라
* 팀의 비전과 구성원의 믿음은 정렬되어야 한다.
** 리더는 팀의 전략적 결정을 팀원들에게 이해시켜야한다.
팀원이 결정의 의도를 이해하지 못한다면 업무의 처리에 있어서 왜곡이 생길수도 있다.
** 팀원의 입장에 있어서는 본인의 업무를 시켜서 하는 것이 아니라 ‘이러저러한 이유 때문에 해야만 하는 것이다’라는 믿음이 있어야한다. +
동기 부여가 되지않는다면 업무 처리에 있어서 좋은 효율을 낼 수 없을 것이라 생각한다.
*** 이 부분을 읽으면서 회사에서 상품에 관련된 세미나를 듣는 내가 떠올랐다. +
나는 백엔드 개발자로 입사를 했지만 도메인에 관한 지식을 내가 꿰고 있어야(아직 멀었지만..) 개발을 진행하는 것에 있어서 모티베이션이 될 것이라 생각했다. +
전체적인 그림이 어떻게 돌아가는지 모르고 시키는 대로만 일하는 개발자보다는, 필요에 의해 ‘이러저러한 이유 때문에 이 기능이 필요하다!’ 혹은 ‘필요하지 않다!’ 라고 말을 할 수 있는 주도적인 자세를 가지는 개발자가 되고 싶었다. +
그것이 나에게 더 큰 성취감과 동기 부여를 가져다 줄 것이라 생각했다.

. 리더는 본인의 위치가 하위 구성원에게 부담스러운 위치일 수 있다는 것을 인지하고 있어야한다.
* 팀원은 리더에게 질문할 수 있어야하고 리더가 나서서 그러한 분위기를 만들어야한다.
** 질문을 한다고해서 반항하거나 권위에 도전한다고 생각해서는 안된다.
*** 팀원이 업무의 내용이나 팀의 목표를 제대로 이해하지 못했는데 질문하기가 두려워서 질문을 하지 않는다면 업무의 진행에 있어서 문제가 생길 수 있다.
그 문제는 처음에는 조막만해도 나중에는 눈덩이처럼 커져서 수습하기 어려울 수 있다. +
이 부분을 읽으면서 모르는 것이나 이해가 안가면 언제든 물어보라고 하셨던 팀장님과 환님이 떠올랐다. +
실제로도 여쭤봤을 때도 친절하게 답변을 해주셨다. +
책을 읽으면서 왜 이 책을 추천해주셨는지 알 것 같다는 순간이기도 했다. 내용 중간중간에서 떠오르는 오버랩되는 순간들은 살찍 띠용(?) 하는 느낌이기도 했고 새로운 직장에서 걱정 많은 나에게 기분 좋은 경험이기도 했다. +
작게는 앞으로 커질 팀의 동료들에게, 크게는 앞으로 될 수도 있는 리더로서 이러한 마인드셋을 가졌으면 하는 바람이였을까하는 생각이 들었다.
. 하나된 목표로 모인 팀원들은 본인의 자존심으로 일을 그르쳐서는 안된다.
* 자존심에 눈 앞을 가리지 말자.
** 밥 먹여주지 않는다.
* 자존심으로 흐려진 상대방의 판단력을 생각하자.
** 극한의 오너쉽은 그것까지 고려하는 것이다.
* 부하가 잘못했더라도 그 잘못에 대한 사항을 사전에 인지시키지 못했다면 그것은 리더의 잘못이다.
** 이것은 누구의 문제도 아니고 누가 맞고 틀리고의 문제도 아니다. +
조직의 목표를 어떻게 잘 달성할 수 있을까에 대한 문제이므로 모두가 합심해서 풀어낼 수 있어야한다. +
자존심 대결이 되어서는 안된다.

. 함께 일하는 모든 팀은 서로를 지원한다.
* 적은 옆 팀이 아니라 회사 밖에 있다.
** 팀간에 문제가 있다면 오해를 풀고 천천히 생각을 해볼 수 있어야한다. +
서로 손가락질하며 비난하는 것은 더 큰 불화만을 야기한다. +
옆 팀이라고 우리팀이 잘되지 않았으면 하는 의도로 갈등을 만드는 것이 아니다. +
파고들고 보면 사소한 오해가 눈덩이처럼 커졌을 수도 있고 협업을 어렵게 만드는 다른 요소가 있을수도 있다. +
팀이 성공하면 팀원 전체와 이를 지원한 모두가 성공한다.

. 지나친 복잡성은 효율이 떨어질 수 있다.
* 자신이 무엇을 하고 있는지 알아야 제대로 할 수 있다.
** 리더가 아무리 훌륭한 전략을 가지고 있더라도 그것이 너무 복잡해 팀원들이 이해하지 못한다면 그 전략은 제대로 효율을 낼 수가 없다. +
전략의 세부 사항을 이행하는 것은 팀원이기에 모두가 이해할 수 있을 정도로 단순해야한다. +
계획을 이해하는 팀원은 진행 도중에 장애물을 만나도 자신의 행동을 빠르게 수정할 수 있다.

. 우선 순위를 정해라.
* 리더는 전체적인 그림을 보는 것을 필요로 한다.
** 방대하고 복잡한 계획은 그 디테일에 매몰되어 버릴수도 있다. +
상위 리더는 한발짝 물러나 전체적인 그림을 보고 하위 리더들이 자신의 팀의 우선순위를 결정하는 것을 도울 수 있어야 한다. +
각 하위 리더들은 최우선 순위에 집중을 하되, 매몰되어서는 안된다. 변하는 상황에 맞추어 다른 문제를 함께 보며 판단할 수 있어야 한다.
*** 이 부분을 읽으면서 업무에 있어서 우선순위를 정하는 것은 중요하다고 느꼈다. +
팀에서 필요로 하는 여러 업무의 진행이 있는데 하나의 업무에 매몰되면 전체적으로 차질이 생길 수도 있다. +
각 업무의 중요도가 전체에서 가지는 위상을 생각하고 우선순위를 결정할 수 있어야겠다는 생각이 들었다.

. 지휘권 분산
* 한명의 상위 리더가 모든 팀원을 조율할 수 없다.
** 상위 리더는 전체 그림을 볼 수 있어야 한다.
** 상위 리더는 하위리더에 대한 믿음을 가질 수 있어야한다.
** 조직의 목표를 이해하고 스스로 무엇을 해야할지 아는 리더이야 한다.
*** 스스로 무엇을 해야할지를 아는 리더는 그 자신의 팀 실무에 예기치못한 일에 직면하더라도 상황에 맞는 대처를 누구보다 잘 할 수 있다.
**** 리더가 능동적으로 업무를 진행하기 위해서
***** 상위 리더는 하위리더에게 자신감을 심어줄 수 있어야한다.
***** 하위 리더는 상위 리더의 목표와 의도를 명확히 숙지하고 있다는 믿음을 가져야한다.
***** 상위 리더는 자신의 결정을 지지해줄 것이라는 절대적 신뢰도 필요로 한다.
**** 이러한 것이 없다면 하위 리더는 자신있게 일을 처리할 수 없다.
이를 위해서는 상위 리더는 하위 리더의 최신 정보를 인식하고 있어야한다. +
위에서 말하는 단순함이 중요한 이유도 지위권이 분산되고 다층화되면 위에서 내려오는 지시의 의도가 왜곡될 수 있기 때문이다. +
위의 사항들이 자리를 잘 잡으려면 시행착오가 필요할 수 있다. +
상위리더는 본인이 잘 할 수 있더라도 하위 리더에게 일을 맡기고 문제를 해결할 수 있도록 기다려야한다. +
제대로 해내지 못하더라도 지지해주어야 한다. +
쌍방간 신뢰를 쌓아가는 과정이다.
* 이 부분을 읽으면서도 오버랩이 되는 부분이 있었다. 환님이 해야할 일(https 통신을 위한 인증서 발급 작업)을 주시면서 잘 못해도 좋으니 진행함에 있어서 생기는 문제(?)들을 기록해보라고 하셨다. +
+
[source,text]
----
maven repository 를 만드는 이유는, gradle 로 artifact 를 참고하기 위함입니다.

그런데, maven repository 가 반드시 https 여야 할까? 에서 출발하는 작업입니다.
----
+
그러면서도 jira에 이러한 코멘트도 남겨주셨다. +
업무를 진행하는 방법을 익히도록 하면서도 시키는 일만을 잘하는 것이 아니라 일의 진행에 있어서 이 일이 꼭 필요한 것인지, 이 일을 왜 해야하는 것인지를 생각하고 주도적으로 일을 진행할 수 있는 능력을 키웠으면 하는 의도이지 않으셨을까하는 생각이 들었다.

. 계획을 세워야한다.
* 일을 진행함에 있어서 예기치 못한 상황을 대비할 수 있어야한다.
** 계획을 세우는 것에 있어서는 모든 팀원이 이해할 수 있을 정도로 쉬워야한다. 계획이 어려우면 정작 그 계획을 이행할 팀원들이 제대로 이해하지 못할 수도 있다.
** 계획 의도를 이해하는 것은 중요하다. 의도를 이해하고 있어야 예기치 못한 변수가 생겼을 때도 의도에 부응하는 능동적 대처를 할 수 있다.
** 계획의 진행 이후 회고도 필요하다. 진행 도중 마주했을 장애물에 어떻게 대처를 했는지등을 자가진단하는 것은 이후 진행할 계획을 더욱 나은 형태로 발전시킬 것이다.
** 이 부분을 읽으면서 예전 포트폴리오 프로젝트로 간단한 게시판을 만들 때가 생각났다. +
간단한 게시판을 만들면서도 여러 변수와 수정 사항으로 도메인 필드를 여러번 바꾸고 로직도 수정해야했다. +
간단한 게시판 마저도 계획이 없으면 중구난방이 되는데 이보다 큰 프로젝트에서 계획의 유무는 얼마나 중요할지 생각해보는 순간이었다.

. 모두를 이끌어라
* 리더에게 당연하고 명백한 것도 구성원에게는 아니어 보일 수 있다.
** 리더는 큰 그림을 가지고 팀을 이끈다. 그리고 구성원들도 그 그림을 머리 속에 그릴 수 있어야한다.
*** 구성원은 자신의 업무에 믿음을 가지고 있어야한다. +
그러나 계획에 대한 전체적인 지식이나 통찰력을 가져야한다는 의미는 아니지만,각자의 역할이 전략적 측면에서 얼마나 중요한지는 알 수 있어야한다. +
그렇지 못하면 큰 그림에서 구성원 개인의 업무가 어떠한 위치를 가지는지 이해하지 못하게 되고 업무의 효율성 또한 떨어지게 된다.
* 구성원에게 당연하고 명백한 것도 리더에게는 아니어 보일 수 있다.
** 위에서 아래로 이끄는 것만이 아니라, 아래에서 위를 이끌수도 있어야 한다.
*** 필요한 지원을 해주지 않는다면 먼저 자신을 돌아볼 수 있어야한다.
리더가 필요한 지원을 해주지 않는다면 먼저 그 지원의 당위성을 가지게 해줄 필요한 정보를 리더에게 제공했는지 생각해보아야 한다.
* 팀이 구성원은 본인의 업무가 팀의 전략적 목표에 어떻게 연결되는지 알 수 있어야한다.

. 리더는 불확실함의 속에서도 단호하게 행동할 수 있어야한다.
* 100% 옳은 해결책은 없고 완벽하게 선명한 그림도 없다.
** 현실은 게임이 아니기에 먹기 좋게 차려진 밥상은 기대하면 안된다.
주어진 상황에서 팀을 위한 최선의 선택을 신속하게 결정할 수 있어야한다.

. 규율은 자유를 위한 것이다.
*  규율은 목적을 빠르고 효율적으로 이루기 위한 것이다.
** 목적을 빠르게 달성하면 그만큼 생기는 시간에 다른 일을 할 수 있다.
** 규율은 목적을 달성하는 경험 후에 정리되어질 수 있는, 다음에 더 잘할수있도록 도움을 주는 메뉴얼일수도 있겠다는 생각이 들었다. +
이러한 규율은 새로운 구성이 조직에 적응하며 겪는 시행착오를 줄여줄 수도 있다.
그러나 규율은 업무를 서포트하는 선에서 조정되어야 한다. 지나친 규율은 오히려 업무의 효율을 저해할 수 있다.

. 좋은 리더는 항상 경계선을 걷는다.
* 좋은 리더는 성공을 우선으로 생각해야한다.
** 리더는 자신을 갖되 자만을 해서는 안되고, 용감하되 무모해서는 안된다.
** 경쟁심을 가져야하지만 때로는 품위있는 패자가 될 수도 있어야한다.
** 디테일에 신경쓰되 매몰되어서는 안된다. +
구성원은 리더보다 좋은 의견을 낼 수도 있고, 구성원이 리더보다 더욱 빛날까 걱정될 수도 있지만 자존심은 접어두어야한다. +
우리는 팀의 성공을 위해 움직이는 전문가가 되어야하고 리더 뿐만 아니라 팀원들 모두가 바라는 것이다. +
문제를 풀어가는 상황에서 또 다른 문제가 생길수도 있고 갈등도 빚을수 있지만 이 모든 것은 팀의 성공 혹은 모두의 성공을 위한 것임을 떠올리고 언제든 조율할 수 있어야한다.
