= Why SoftwareSucks (소프트웨어, 누가 이렇게 개떡같이 만든거야)
Gyeongtae Noh <gt.noh777@sirloin.co.kr>
// Metadata:
:description: 
:keywords: ui, ux, user-experience
// Settings:
:doctype: book
:toc: left
:toclevels: 4
:sectlinks:
:icons: font

소프트웨어를 개발하면서 사용자 관점에서 어떻게 생각해야하는지를 많이 생각해야한다는걸 배운거 같다. 이 책은 맨 처음 개발자의 사고에 대한 단점을 꼬집는다. 
개발자의 사고 방식이 고객 관점이 아닌 자신의 관점이 되버리면 사용자가 원하는 동작과는 전혀 안맞는 이상한 동작이 나올 수 있다는 것이다. 

대표적인 예시는 사용자가 문서 작업 후 닫기를 누르면 저장하시겠습니까? 라는 문구가 뜬다. 그러면 사용자 입장에선 이걸 굳이 생각해 봐야할까? 라는 접근이다. 
당연히 프로그래머 관점에선 용량을 효율적으로 관리하기 위해 매번 저장할지 안할지 고려해야한다. 그리고 프로그래머는 난 이런걸 이렇게 해결했어! 정말 훌룡한 개발자야!
할 수도 있다. 사실 틀린말도 아니다. 하지만 사용자는? 과연 그걸 정말 우와 대단한 프로그램이야! 사용자 PC 용량을 고려하여 설계하다니! 라고 생각했을까? 
내 생각엔 음 이건 왜 물어보는거지? 매번 내가 이 창을 보는건 너무 비효율적인거 같아. 라는 생각을 더 할 수 있다.

이러한 것들이 개발자들이 흔히겪는 오류라고 생각한다. 당연히 프로그래머 관점에서 이러한 걸 그냥 바로바로 매번 저장한다는 건 용량 관점에서 불합리한 선택일 수 있다. 
하지만 우리도 현실세계에서 단 한번도 메모에 대한 공간을 고려하여 매번 보관을 걱정하는 짓 따위 하지 않는다. 사용자를 고려했다면 당연히 물어보지 않는 것이 맞다. 

이 책에서 말하는 내용 대부분이 그렇다. 프로그래머는 사용자들을 위해 고민하는가를 되돌아 봐야한다고 생각한다. 우리가 하는건 멋진 기술을 써서 멋진 방법으로 문제를 해결했어!
장애를 해결했어!가 아니다. 문제를 어떻게든 해결한다가 우선시되어야 한다고 생각한다.

나 또한 마찬가지지만 요새 개발자들이 MSA나 DDD 같은 훌륭한고 매혹적인 기술에 빠져 개발하는 것에 집중하지 사용자 문제를 어떻게 해결할까를 고민하지 않는 것이 많다. 또한 MSA DDD 같은
기술을 쓰는 과정에서 비용이 배로 늘어난다면? 사용자 문제를 해결하자고 회사 문제를 만들어버리는 것이나 다름이 없다. 
우리는 문제를 해결하는 사람들이지 문제를 만드는 사람들이 아니지 않은가! 기술에 매료되어 절대 문제를 만드는 행동은 안했으면 좋겠다고 생각한다. 

개인적으로 개발자로써 무슨 일을 해야할지 잘 모르겠다면 이 책을 읽어보는건 어떨까? 지인들에게 추천해주고 싶었다. UX의 중요성 사용성에 대한 중요성 사용자 정보를 안전하게 지키기 위한 보안의 중요성
그리고 그에는 큰 기술보단 사고력이 중요하다는 점 정말 좋은 교훈을 우리에게 주는 것 같았다. 

그리고 보안 또한 사용자 입장에서 어려워지지 말아야한다고 생각한다. 지금 우리가 payco pass를 사랑하는 이유를 생각해보자 기존의 은행 공동인증서 얼마나 우리를 지독하게 괴롭혔나 아무리 보안이 중요해도
그렇게 불편하면 우리는 계좌이체에 대한 거부감이 들 수 도 있다. payco pass는 보안과 사용성 모두를 챙긴 훌륭한 어플 중 하나이고 대표적인 예이다. 

마지막으로 이 책을 읽고 느낀 한 가지는 모든 애플리케이션은 쉬워야 한다! 편해야한다! 재밌어야한다! 저자는 우리에게 가장 전달하고 싶은 메시지가 이것이지 않을까 생각한다.
