= Why SoftwareSucks(소프트웨어 누가 이렇게 개떡같이 만든 거야) 독서 감상문
Hwan Jo <hwan.cho@sirloin.co.kr>
// Metadata:
:description: 
:keywords: ui, ux, user-experience
// Settings:
:doctype: book
:toc: left
:toclevels: 4
:sectlinks:
:icons: font

소프트웨어 누가 이렇게 개떡같이 만든 거야

처음 제목을 봤을 때는 도발적인 제목에 웃음을 터뜨리지 않을 수 없었다.
하지만 책을 읽어나가면서 소프트웨어 엔지니어 입장에서는 당연한 것으로 생각했던 동작들이 이용자에겐 굉장히 불편하겠구나라는 생각을 갖게 되었다.
이 책에서는 다양한 사례들을 들며 왜 이게 개떡같은지를 상세하게 설명하고 있다.
그리고 제일 처음 등장하는 것이 메모장 애플리케이션의 사례다.

메모장을 쓰면서 다들 한번쯤은 "저장하지 않으면 모든 내용이 사라집니다" 같은 무시무시한 경고창을 본 경험이 있을 것이다.
물론 이 대화창은 중요한 내용을 작성중이었다면 정말 무서울 것이다.
그런데 간단한 메모만 작성하고 종료할 생각이었다면 앱을 빨리 종료하지 못하게 해서 짜증을 유발한다. 

심지어 메모장 앱이 텅텅 비어 있는데도 저런 메시지를 보면 어이가 없어지기까지도 한다.
복사-붙여넣기 용도로만 간단하게 쓸 생각으로 메모장을 켜고, 이제 필요없으니 메모장에 적은 내용을 모두 지우자.
그리고 종료를 누르면 이미 한번이라도 편집한 이력이 있기에 "편집중이었던 모든 내용이 사라진다" 는 오류창을 볼 수 있다.
마치 누구를 놀리나 싶은 생각이 들 정도다.
편집을 했던건 맞지만, 내용이 없는데 뭘 저장하라는 거지? 라는 생각이 당연히 들기 마련이다.

그런데 소프트웨어 엔지니어 입장에서 생각해 보면 메모장의 이런 동작은 당연한 것이다.
명시적인 저장 전까지 메모장의 모든 편집 내용은 메모리에만 저장된다.
또한 이 메모리의 내용은 메모장 프로세스가 살아있는 동안만 유효하다.
게다가 이용자가 실수로 종료창을 누른 건지, 아닌 건지 알 수 없다.
마지막으로, 사용자가 편집하던 내용을 임시 저장해야 할 가치를 판단하기도 어렵다.

사용자에게 편의성을 주기 위해 저런 다이얼로그를 띄우는 대신 임시 저장소에 저장중인 내용을 저장하는 일도 생각만큼 간단하지는 않다.
임시 저장소의 접근 권한이라던가, 남은 용량 등도 고려해야 한다.
모든 최후의 수단이 사라졌을 때 오류 메시지는 어떻게 띄워야 할까? 같은 문제도 생긴다.
이 쯤 되면 창 닫기처럼 간단한 기능 하나를 구현하는 일도 단순하지 않다.
그래서, 다른 높은 우선순위의 일을 처리한다는 미명 하에 '쓸데없이 복잡한' 문제는 뒤로 밀린 채로 고객에게 출하된다.

그러나 저자는 단호하게 말한다.
그게 당연할지라도, 그건 소프트웨어 엔지니어의 귀찮음을 이용자에게 떠 넘기는 최악의 결정에 불과하다고 말이다.
그냥 간단하게, 저장중이던 내용을 다시, 잘 불러오도록 만들면 된다는 것이다.
임시 저장을 못하게 되는 최악의 상황도 당연히 고려해야겠으나, 그런 상황은 드물게 일어날 테니 일단 이용자 편의를 최대한 제공하는게 먼저라고 말이다.

저자의 이런 나쁜 소프트웨어를 만든 사람에게 그걸 매일 쓰게 하는 형벌을 줘야 한다는 대목에서는 웃음이 터졌다.
이제는 거의 사라지는 추세지만 공인인증서가 제일 대표 사례다.
나만 해도 공인인증서를 쓸 때마다 욕설을 내뱉으며 "공인인증서 개발한놈 집의 화장실 출입문을 공인인증으로만 열리게 애야 한다" 같은 말을 하니까.
특히 나처럼 Linux 같은 특이한 운영체제를 쓰는 사람 입장에서 주민등록등본 열람 같은 일을 하는데 40분 가까운 시간을 쓰면 욕이 안 나올래야 안 나올 수가 없다.

그리고 저자의 말 중, 우리를 정말 아프게 때리는 말이 있다.
바로 소프트웨어 개발에 관계된 사람들이, 고객을 제대로 이해하지 못하면 이런 허섭쓰레기들이 나온다는 말이다.
그 고객이 있기에 월급이 나온다는 간단한 사실을 망각한 자들의 손에서 이런 것들이 나온단다.
책의 꽤 이른 부분에 이 대목이 나오는데, 읽으면서 많이 반성하게 만든 문장이었다.

좋은 개발 프로세스, 가독성이 높은 코드, 훌륭한 아키텍쳐... 다 좋은 말들이다.
하지만 그런 공정을 거쳐 출하한 제품이 임시 저장도 없는 주제에 쓸데없는 기능도 많고 복잡한 메모장이라면 과연 그게 세상에 얼마나 가치를 더해줄 수 있을까?
고객의 기분을 상하게 하는 주제에 내가 월급을 받을 자격이 있긴 한 걸까? 를 생각하며 책을 덮었다.
'그게 진짜 우리 고객이 원하는게 맞을까?' 같은 질문을 던지게 해 준 좋은 책이었다고 생각한다.
책의 순서는 다소 난잡했지만 프로세스 중심에서 고객 중심으로 생각할 기회를 얻게 되어 의미있었다.

