= Why Software Sucks(소프트웨어 누가 이렇게 개떡같이 만든 거야) 독서 감상문
Jaewon Kim <jw.kim@sirloin.co.kr>
// Metadata:
:description: 입문교육 2주차 제공 도서의 독서 감상문입니다.
:keywords: ui, ux, user-experience
// Settings:
:doctype: book
:toc: left
:toclevels: 4
:sectlinks:
:icons: font

[[user-centered-design]]
== 좋은 소프트웨어를 개발한다는 것

저자는 좋은 소프트웨어를 개발한다는 것이 (프로그램의 설계에 1도 관심 없는) 사용자들의 입장에 맞춰 얼마나 쉽고 편한 제품을 만들기 위해 노력하는지에 달려있다고 셀 수 없이 강조한다. 많은 실생활의 문제들은 소프트웨어를 개발하는 프로그래머와 설계자, 관리자들이 그들의 고객을 충분히 이해하지 못하는 데서 비롯되기 때문이다.

우리가 소프트웨어를 만드는 이유는 고객이 그들의 문제를 해결할 수 있도록 돕기 위한 것에 있지만, 고객과의 커뮤니케이션으로부터 단절된 채로 개발에 임하는 개발자들이 생각보다 많기 때문에 그렇게 출시된 제품이 "개떡같이" 만들어지기란 너무 쉽다는 것이다.

____
여러분은 가정용 드릴을 설계하는 사람들과 같습니다.

그런데 여러분은 여기서 볼 베어링이냐 롤러 베어링이냐 아니면 에어 베어링이냐 같은 내부 사항에 대해서만 얘기하며, 고객이 이런 것들을 다른 어떤 것보다도 중요하게 생각할 것이라 주장하고 있습니다.

틀렸습니다. 고객은 드릴 자체에 대해서는 조금도 신경 쓰지 않습니다. 신경 쓴 적도 없고 앞으로도 계속 그럴 겁니다.
____

누구보다 전문 지식을 많이 보유한 집단이기 때문에 오히려 관련 지식이 거의 없는 일반적인 사용자들의 입장을 이해할 수 없는 '앎의 역설(Paradox of Knowing)' 현상이 개발자들에게도 발생하는 셈인데, 이는 사용자들 역시 그들과 같을 거라는 안일한 생각을 낳게 되고, 결과적으로는 누구도 신경 쓰지 않는 문제나 뜬금없는 기능에 역량을 투입하는 실수로 이어진다.

물론 그런 실수가 제품을 이용하는 사용자들을 방해하지 않는다면 큰 문제가 되지 않겠지만, 항상 그렇게 희망적인 경우만 있을 수는 없기 때문에 사용자 관점을 이해하지 못한 개발자들은 그들의 고객에게 손해를 끼칠 수밖에 없다. 사용자 관점에서는 소프트웨어에 어떤 복잡한 설계와 기능들이 담겨있는지 일일이 공부해서 능숙해져야 할 이유가 전혀 없고, 문제 해결에 필요한 핵심 기능 위주로 빠르게 익혀 해당 문제를 눈앞에서 치워버리고 싶을 뿐일 것이며, 그마저도 익힌다는 생각이 들지 않을 정도로 쉽기만을 바랄 텐데 말이다.

그런데 불필요한 기능을 개발하는 데에 힘을 쏟느라 원활하게 제품을 이용하던 사용자들의 시간과 노력을 낭비하게 만든다면, 결국에는 경쟁사에 고객들을 뺏기는 일밖에 남지 않을 것 같다.

[[personal-experience]]
== 개인적인 경험: 사용자 관점의 중요성

그런 의미에서 비영리 단체에서 교육봉사 및 장학 프로그램을 기획・운영했던 경험은 도움이 된다.

당시에는 (소프트웨어가 아닌) 교육복지와 행정에 대한 분야를 다뤘는데, 복잡다단하게 설계된 프로그램을 이끌어나가다 보면 프로그램을 만들고 제공하는 입장에 매몰되어 참여자들의 의견을 제대로 반영하지 못하기 일쑤였다. 혹시라도 참여자들이 만족하지 못하고 떠나가는 일이라도 발생하면 프로그램의 성과가 기하급수적으로 낮아질 텐데도 초반에는 관리하는 측면의 업무를 접수된 의견들보다 우선했던 적이 종종 있었고, 그로 인한 실수를 뒤늦게 만회하고자 고생했던 기억도 난다.

그때마다 중요했던 건 참여자들과의 커뮤니케이션이었다. 현장 실사를 반기별로 진행해 참여자들의 의견을 직접 듣기 위해 노력했고, 그게 여의찮을 경우를 대비해 활동 내용에 관한 소통을 온라인으로도 꾸준히 진행했다. 그러다 보면 (사전에 치밀하게 기획했더라도) 운영하는 과정에서 예상치 못한 허점이 드러나거나 새롭게 발생하는 돌발상황에 적응해야 할 때가 간혹 발견됐는데, 그럴 때마다 참여자들이 현장에서 느낀 감정과 아이디어들을 적절하게 수용하고 프로그램에 반영해 나가는 것이 참여자들의 만족도와 프로그램의 성과를 동시에 높이는 가장 빠른 방법이었다.

그 결과, 참여자들의 활동에 도움이 되지 않는다고 판단되는 관리 업무들을 대폭 축소할 수 있었던 데다가, 위의 과정들이 자연스럽게 다음 기수를 위한 '사용성 테스트(Usability Test)'의 역할을 수행해 준 덕분에 프로그램을 운영하는 기간이 오래될수록 참여자들의 만족도를 더 높게 유지할 수 있었다.

설로인의 B2C 커머스 개발에 참여했던 경험 또한 사용자 관점의 중요성을 체득할 수 있었던 좋은 기회였다.

사용자들과의 상호작용을 담당하는 프론트엔드 엔지니어로서 (기술적으로 탁월한 것도 중요했겠지만) 개인적으로는 "고객의 입장"에 많은 신경을 썼던 것 같다. 샤토브리앙을 구매하려고 설로인 커머스 앱에 접속한 고객들에게는 '얼마나 쉽고 편하게 샤토브리앙을 구매할 수 있는지'가 무엇보다 중요할 것이다. 그래서 작업이 주어질 때마다 해당 작업이 고객의 구매 과정을 쉽고 편하게 만들어 주는 게 맞는지 거듭 확인했고, 필요한 경우에는 적극적으로 의견을 내기도 했다.

작업을 진행하면서는 고객이 우리가 의도한 대로 행동에 옮기는지 검증하기 위해 Amplitude와 같은 행동 분석 도구를 활용했다. 기능 개발 및 출시에서 그치는 것이 아니라, 출시 이후에도 고객들의 행동 분석 결과를 통해 새롭게 개발한 기능이 실제로 도움이 되고 있는지, 오히려 고객들에게 불편함을 주고 있지는 않은지 등을 지속적으로 관찰했다.

결국 우리가 제공하는 서비스를 사용자(혹은 참여자)들이 얼마나 쉽고 편하게 이용하는지 관리하는 것이 분야를 막론하고 비즈니스의 중요한 목표가 된다는 것, 그리고 그 목표를 달성하기 위해서는 직・간접적인 커뮤니케이션을 통해 그들의 입장을 이해하려는 노력이 꾸준하게 필요하다는 것을 앞선 경험들을 통해 깨달을 수 있었다.

[[outro]]
== 앞으로

본대로의 B2B 커머스 개발에 합류하게 되면서도 크게 달라지는 건 없지 않을까.

서비스가 출시된 지 얼마 되지 않았기 때문에 초기 기획에 따라 완성해야 할 부분도 아직 많이 남았겠지만, 고객들과의 접점을 통해 얻는 의견들을 바탕으로 우리 서비스의 사용성을 지속적으로 보완해 나가야 하겠으며, 나아가 한우 도매 거래를 온라인화한다는 궁극적인 목적을 달성하기 위해 '꼭 필요한 기능 위주로, 쉽고 편한 서비스'를 만들기 위한 개선 작업을 계속 이어 나가야겠다.

무엇보다 "개발자는 사용자의 삶을 쉽게 하기 위해 존재하는 것이지, 사용자의 삶을 복잡하게 하기 위해 존재하는 것이 아닙니다"라는 문장만큼은 앞으로의 커리어 내내 되새길 수 있도록 해야겠다.