= Why SoftwareSucks(소프트웨어 누가 이렇게 개떡같이 만든 거야) 독서 감상문
youjin <wg.shin@sirloin.co.kr>
// Metadata:
:description: 입문교육 3주차 제공 도서의 독서 감상문입니다.
:keywords: ui, ux, user-experience
// Settings:
:doctype: book
:toc: left
:toclevels: 4
:sectlinks:
:icons: font

# 소프트웨어 누가 이렇게 개떡같이 만든 거야

이 책은 프로그램의 UI와 보안에 대해, 개발자(저자의 언어로는 Geek, 긱)들이 놓치기 쉬운 부분에 관해 설명하고 있다.

### UI
가장 중요한 부분은, 소프트웨어는 사용자를 위한 상품이라는 점이라는 부분을 저자는 책 전반에 걸쳐서 강조한다.

어떠한 이유에서라도, 사용자가 프로그램의 사용 방법을 제대로 이해하지 못하거나, 동작 방법에 대해서 이해했더라도 불만족스러운 사용경험을 했을 경우에는 일말의 변호의 여지 없이 그 프로그램은 잘못 만들어진 것이라는 이야기이다.

물론 개발자들의 입장에서 변호하자면 사용하는 데스크탑, 혹은 스마트폰은 사용자가 기대하는 것처럼 모든 일을 간단하게 해줄 수 있는 마법의 상자가 아니다.

1900년대 후반부터 시작된 IT기술을 발전시킨 선배들의 노력으로 만들어진 계층 분리와 추상화라는 기법을 이용해서 가능한 관심사의 분리를 달성하였다. +
하지만, 온보딩 과정을 진행 할수록 반복적으로 느끼는 것은 많은 단계의 계층 분리와 추상화는 동일한 반복작업의 필요성을 줄여주는 도구이지 하위 계층에 가려져 있는 부분을 학습하지 않아도 되는 핑계가 되지 않는다는 것이다.

'소프트웨어'가 실행되는 도구는 결국 하드웨어일 수밖에 없다.
결국 소프트웨어의 능력의 한계는 하드웨어에서 결정된다는 것이다. +
이러한 많은 제약사항을 극복하고 성공적으로 동작하는 프로덕션 레벨의 코드를 작성하는 것은 결코 쉽지 않은 작업이라 생각한다.

하지만, 이러한 작업이 어렵다는 이유로 혹은 개발자 본인이 컴퓨터를 너무 사랑한다는 이유로 개발한 서비스를 사용하는 유저에게 관련한 CS지식을 요구하는 것은 잘못되었다는 것이 저자의 주장이다.

우리가 의사에게 처방받을 때, 의학지식의 소유를 걱정하지 않듯이 프로그램을 실행시킬 때 사용자가 CS적 지식을 요구받는 경우가 없어야 한다는 당연한 이유이기도 하다.

이러한 문제가 저자가 에필로그를 적은 2006년에서 15년 이상이 지난 지금에서도 상용하는 서비스에서 반복적으로 관찰되는 근본적인 원인은 바로 사람은 '부재'라는 개념을 태생적으로 이해하지 못하기 때문이라 생각된다.

모든 개발자가 특권의식을 갖고 내부적으로 결속해, CS적 지식이 없는 대중들에게는 신성한 산물인 서비스를 이용할 수 없게 장벽을 세우자고 생각한다 주장하기에는 이는 진지하게 받아들이기 힘든 부분이 많다.

그렇다면 왜 같은 실수가 반복되어가는 걸까.
이는 사람이 부재라는 개념을 이해하지 못하기 때문이라 생각한다.
코끼리를 상상하지 말라고 되뇔수록 머릿속에서는 더욱 선명히 코끼리의 이미지가 그려지듯이

개발자들은 이미 CS와 프로그램이 요구하는 도메인에 대한 지식이 너무 당연해서, 이와 관련한 배경지식이 없는 상태를 상상할 수 없는 것이다.

물론 개발자 본인은 충분히 대부분의 일반적인 유저에 적합한 UI 디자인을 설계했다고 생각할 것이다. 하지만, 사람으로 태어난 이상 절대로 한번 어떤 부분을 알아버리면, 다시는 그 지식을 알기 전이 어떤 상태였는지 상상할 수 없어진다.

저자는 이러한 부분을 다양한 가설을 수립하고 실 사용자에게 서비스의 UI를 테스트할 것을 강력하게 추천한다. 가능하면 자산적, 시간적인 비용이 관련 서비스에 투자되기 전에 먼저 실행할수록 좋다고 한다.

저자는 이러한 방식으로 비용을 요구하지만, 결과적으로 실패한 디자인의 서비스를 개발하는 것을 방지할 수 있는 해결책을 제시하고 있다.

한마디로 이야기하면 네가 사용자를 알고 있다 착각하지 말라는 것이다.

### 보안
나는 이 책을 읽기 이전에는 보안이 이렇게나 UX와 관련이 깊은 영역인지 짐작하지 못했었다.

저자의 말을 인용하자면, 개발된 서비스의 보안이라는 것은 마치 사슬과 같아서, 보안의 견고함은 그 연결고리 중 가장 약한 부분의 강도를 의미한다는 것이다.

또한, 이러한 사슬의 가장 처음과 끝부분에는 우리가 작성한 프로그램이 아니라 결국 사람이 있다는 부분이다.

아무리 내부적으로 완결성이 높은 보안체계를 구성해놔도, 사용하는 유저가 절대 공개해야 하지 말아야 할 정보를 공개해가며 사용한다면 그 완벽한 보안체계를 구성하기 위한 수많은 노력과 비용은 아무런 의미가 없어지게 되는 것이다.

따라서 보안이야말로 어떤 기능보다도 UX 적으로 접근하여야 한다는 의미였다.

또한, 다른 많은 부분이 그렇듯이 서비스의 내부 보안성과 사용자의 불편함은 트레이드-오프 관계를 가지게 되는데. 보안성을 추구하기 위해 임계값을 넘어버리게 UX를 훼손하면 결국 위에 말한 이유로 보안체계 자체가 무너지든가 아니면 단순히 유저가 관련 서비스를 사용하지 않아버리는 결과를 얻게 된다.

따라서 상용하는 서비스에서 추구해야 하는 보안성은 완벽한 보안을 의미하는것이 아니다.

서비스의 도메인 적인 특성과 사용자의 특성 모두를 고려해, 사용자가 충분히 감안할수 있는 정도의 UX 적 손실과 서비스 운영자가 요구할 수 있는 정도의 보안성을 확보하는 적절한 타협점을 찾아서 기술적인 해결책을 제시해야 하는 것이 개발자의 역할이라고 저자는 주장한다.

### 정리
저자는 반복적으로 네가 모든 걸 다 알고 있다 생각하지 말라며 경계한다. +
또한 단순히 원론적인 이야기에서 끝나는 것이 아닌 가설 수립과 검증의 반복으로 우리는 절대 사용자의 머릿속을 알 수 없지만, 현실적으로 근접해 나갈 수 있는 방법론 또한 제시해주어 상당히 가치가 있는 독서를 할 수 있었던 것 같다.
