= 소프트웨어 누가 이렇게 개떡같이 만든 거야 독후감상문

시간이 지나면서 사용자 경험을 중시하는 서비스들이 많이 나타나고 있다. +
예전에는 UPS의 사례뿐만 아닌 그때 즈음의 웹사이트들은 무언가 거쳐야할 단계들이 많았다. +
스타벅스의 사례만 보더라도 검색할 반경을 사용자가 직접 입력했어야했지만 콜택시 서비스인 카카오 택시는 일정 반경안에서 택시가 잡히지 않으면 자동으로 반경을 늘리면서 검색을 해준다. +
‘검색 반경을 늘릴까요?’ 라고 물어보지 않는다. 사용자에게 몇분만에 도착할 거리인지를 보여주면서 반경을 늘려간다. +
때문에 사용자는 예정 도착 시간을 보면서 택시를 기다릴 것인지 아니면 다른 선택지를 고를 것인지 결정할 수 있다. +
요즘(?)에 들어서 ‘사용자의 경험을 신경써주는 이유가 무엇일까?’ 고민했고 두가지 정도가 떠올랐다. +
하나는 기술 기반의 서비스가 부흥(?)을 했기 때문이라고 생각했다. +
이전에는 어떠한 서비스 혹은 사업을 할 때, 이 사업장이 무엇을 위한 것인지, 어디에 위치하는지 안내하는 정도로 IT기술이 사용되었다면
요즘은 앱 혹은 웹을 통해 서비스 자체를 이용 혹은 예약하는 방향으로 발전하면서 서비스 이용자의 경험을 중시하는 방향으로 변한 것이라 생각이 들었다. +
다른 하나의 이유는 돈이다. +
IT산업은 타 산업에 비해 진입 장벽이 낮은 편이다.
다른 산업처럼 기반시설이나 특별한 기술을 위해 연구에 투자할 필요성이 없기 때문에 초기에 투자해야하는 비용이 많이 들지 않는다. +
가장 큰 비용으로 예상될 서버도 요즘에는 클라우드 기반으로 운영되는 서버를 통해 초반에는 낮은 가격에 적은 부담을 가지고 시작할 수 있다. +
그리고 우리나라는 개발자의 인건비도 타 직무에 비해서 그렇게 비싼 편도 아니었을뿐더러 정부에서 직접 IT인력 육성을 지원했기 때문에 시장에 개발자 인력의 공급은 문제가 없었다. +
이러한 환경에서 기술 기반의 서비스가 부흥을 하면서 너나할 것 없이 서비스 경쟁에 뛰어들었으니
기업들은 사용자의 유인을 위해 무엇이든 할 수밖에 없었다고 생각이 든다. +
마지막 하나는 애플이라고 생각했다. +
초기 스마트폰이 출시되던 시기에는 안드로이드 기반의 스마트폰은 사용하기가 무언가 복잡했지만 아이폰은 상대적으로 사용하기가 쉬웠다. +
아이폰 특유의 고급스러운 디자인과 내부 소프트웨어의 UI/UX는 사용자들에게 이제까지 겪어보지 못했던 경험을 가져다 주었고, 사용자들의 좋은 경험은 애플의 시장점유율 상승과 이익으로 이어졌다. +
이를 지켜보던 경쟁자들은 애플의 성공 요인을 분석하고 벤치마킹을 하는 과정에서 위와 비슷한 결론에 도달했고, 회사의 제품 개발에 반영되는 방향으로 이어졌을거라 생각했다. +

안전하고 좋은 것은 쉽게, 위험하고 나쁜 것은 어렵게 +
책을 읽으면서 뇌리에 남았던 문구였다. +
책에서는 마이크로소프트사의 윈도우의 달력을 예시로 들었다. +
윈도우의 관리자 계정을 사용하는 이용자는 윈도우의 오른쪽 하단의 시계버튼을 눌러서 ‘무슨날이 무슨요일인지’ 달력을 확인할 수 있었다. +
더불어 OS의 시간 설정도 할 수 있는 기능도 있다. +
하지만 달력을 봐야하는 일반 이용자가 하단의 시계 버튼을 눌렀을 때 권한이 없어 불가능하다는 문구가 뜬다. +
달력을 보는데 권한이 필요한 것인가? 문제는 OS의 시간을 설정하는 기능이 같이 있었던 것이다. +
안전하고 쉬운 것은 달력을 보는 것이다. +
위험하고 어려운 것은 OS의 시간을 보는 것이다. +
책의 내용에 따르면 이 둘은 분리가 됐어야 한다. +
백엔드 개발자의 관점에서 이러한 점을 어떻게 다루어야 할까? 고민이 됐다. +
사용자가 서버에 가장 밀접히 맞닿는 지점은 엔드포인트를 통해 요청을 시도할 때이다. +
그렇다면 간단한 정보를 요청할 때 단순한 엔드포인트를 가지는 Get 요청이 안전하고 쉬운 것일까? +
사용자의 계정을 삭제하는 위험한 요청을 할 때 Http의 헤더나 바디에 어드민의 인증 정보를 넣고 Post 요청을 하는 것이 어렵고 위험한 것에 분류될 수 있는 것일까? +
아니면 사용자 vs 서버의 관점을 떠나 개발자 vs 프로젝트 관점에서
상대적으로 낮은 위험성을 가지지만 동시에 큰 변동성을 가져야하는
컨트롤러단 혹은 서비스단은 쉽게 찾고 수정 가능하도록 구조를 만드는 것이 ‘안전하고 쉬운 것’에 속하는 것일까? +
상대적으로 높은 위험성을 가지면서 전역적으로 영향을 미칠 수 있지만 작은 변동성을 가지는
레파지토리단 혹은 core 로직은 프로젝트 깊숙히 숨겨도는 것이 ‘위험하고 어려운 것’에 속할 수 있는 것일까? +

인증 과정의 아웃소싱 +
상점들이 장부를 관리하며 개인 고객들이 신용거래를 하던 시절이 있었다. +
이후 카드사들이 생겨나면서 지불 과정의 일체를 카드사에 아웃소싱하게 되었고 개인과 카드사 그리고 카드사와 상점으로 관계를 맺으면서 개인과 여러 상점 혹은 상점과 여러 개인의 관계를 다루어야하는 부담이 줄어들게 되었다. +
웹사이트에 있어서도 보안은 전문성이 필요하면서도 부담스러운 부분이다. +
이러한 필요성에서 인증의 아웃소싱의 방법으로 소셜인증이 나타나게 된 것 같다는 생각이 들었다.
