= Why SoftwareSucks(소프트웨어 누가 이렇게 개떡같이 만든 거야) 독서 감상문
youjin <howyoujini@sirloin.co.kr>
// Metadata:
:description: 입문교육 3주차 제공 도서의 독서 감상문입니다.
:keywords: ui, ux, user-experience
// Settings:
:doctype: book
:toc: left
:toclevels: 4
:sectlinks:
:icons: font

# 소프트웨어 누가 이렇게 개떡같이 만든 거야

<소프트웨어, 누가 이렇게 개떡같이 만든거야>라는 책을 읽고 "사용성"에 대해서 다시 생각해볼 수 있었다. 나는 이전에 UX UI 디자이너로 일해본 적이 있다. motion-graphic 디자이너로 작업할 때에는 엄청 신경쓰지 않아도 되었던 "사용자"에 대해 이것저것 생각해야하는 부분이 굉장히 어려우면서도 재밌었다. +

이제는 소프트웨어 개발자로써 "사용자"에 대해 생각해야한다. 도대체 사용자가 뭐길래, 이렇게 신경을 쓰고 사용자를 위해 수정하고, 사용자를 배려해야하는 것일까? 사용자는 곧 나이다. 곧 내 가족들이며 친구들이라 생각하면 불편하지 않게 프로덕트를 사용할 수 있도록 만들고 싶어진다. 주로 프로그래머는 사용자 인터페이스를 사용자의 사고 과정에 맞추는 대신에 사용자가 자신의 사고과정에 맞추도록 강요하게 된다. 하루 내내, 어쩌면 일년 내내 자신이 개발하고 기획하고 있는 프로덕트만 죽어라 몰두해서 보기 때문에 이런 현상이 생긴다고 본다. 본인의 프로덕트를 저 멀리 떨어져서 바라보고 가끔은 처음 보는 프로덕트처럼 사용해볼 필요가 있다. +

이 책에서는 우리가 어떤 파일을 삭제하기 위해 삭제버튼을 누르면 "정말로 삭제하시겠습니까?"라는 알림창이 뜨는 것에 비관적인 시선이다. 또한 메모장에서 특정 메모를 수정하고 나면 "변경된 내용을 저장하시겠습니까?", "방금 작업한 내용을 모두 버리겠습니까?"라는 등의 알림창이 뜨는 것을 경계한다. 왜냐하면 일상생활에서 옷을 살 때 "정말로 이 옷을 구매하시겠습니까?"라고 물어보는 점원은 없을 뿐더러 집에서 휴지통에 물건을 버릴 때에도 "정말로 이 물건을 버리겠습니까?"라고 물어보는 과정은 없기 때문이다. 실제로 오프라인 상에서는 존재하지 않는 확인질문이기에 처음 사용하는 사용자들은 귀찮기도 하고 오히려 괴리감을 느낀다는 것이다. 하지만 내가 생각하기엔 이미 많은 사용자들은 온라인에서 확인알림을 받는 것에 너무 익숙해져서 당장 이 기능을 없앤다면 오히려 불편함을 제기 할 수 있겠다는 생각이 들긴했다. 이 예시를 살펴보면 사용자들이 원하는 것은 프로그램이 돌아가는 과정을 알고 싶은 것이 아니라 정말 이 기능을 사용하고 싶은 것이다. 프로그램의 내부에서 어떻게 동작하는지는 알고 싶어하지도 않는다. +

나는 일반사용자에서 소프트웨어 개발자로 전향한지 1년이 되지 않았다. 하지만 이전에 일반인이었던 내가 온갖 전문적인 용어와 정말 어려운 로직을 처리하기 위한 과정을 이야기하는 개발자들을 보았을 때 대화를 쉽게 걸기 어려웠다. 흔히 Geekble하다고 하는 것 처럼 그들은 그들만의 컴퓨터 세계가 있어서 일반적으로 다가가기 어렵다고 "나마저도" 그렇게 생각했었기 때문이다. 하지만 진작에 일반인인 내가 말하고 싶은 것은 단지 "메모를 수정할 수 있게 해달라"라는 간단한 기능이었을 것이다. 현재 소프트웨어 엔지니어의 길을 걷고 있는 나도 사용자로써 기능자체를 볼 수 있는 시선을 길러야할 것 같다. 소프트웨어 엔지니어는 프로그램을 어떻게 짜고 어떤 로직을 활용했으며 어떻게 진행했다는 테크기반의 해결책도 물론 중요하다. 하지만 가장 먼저는 그 문제가 테크기반으로 해결하면 되는 문제인지, 어떤 다른 방법은 없는지, 더 간단한 방법은 없는지, 다른 시선은 없는지 항상 경계하고 생각해야할 것이다. +

지금까지 내가 사용해왔던 (이 책에서 이야기하는) 개떡같은 소프트웨어들을 보고 느낀 것들은 진짜 이렇게 밖에 할 수 없었을까 ! 싶다. 어플을 등록하기까지의 과정이 있을 텐데 정말 아까울 정도로 아쉬운 프로덕트들을 꽤 봤기 때문이다. 소프트웨어 개발자로써 우리 프로덕트가 발전할수록 사용자들이 우리의 기능과 플로우에 학습(익숙)해지게 할 것인가, 그냥 아주 자연스럽게 (사용자의 심리를 파악하여) 스며들게 할 것인가? 나는 과연 앞으로 어떤 소프트웨어 개발자로 발전해야하는 것인가를 돌이켜 보는 의미있는 한 주였다. +
