= The Passionate Programmer(프로그래머 열정을 말하다) 독서 감상문
Hwan Jo <hwan.cho@sirloin.co.kr>
// Metadata:
:description:
:keywords: passion, growth, professionalism
// Settings:
:doctype: book
:toc: left
:toclevels: 4
:sectlinks:
:icons: font

출판사측에서 구판의 '사랑하지 않으면 떠나라!' 라는 제목을 좀 더 직관적으로 바꿨나 보다.
그리고 개인적으로도 훨씬 더 만족스러운 제목이다.
다만 신판은 구판보다 책 크기는 좀더 작아지고 종이 질도 좀 더 나빠진 것 같다.
책의 만듦새가 나빠졌을 뿐 아니라 2012년 이후 더 이상의 개정판도 출시되지 않는다는 것이 조금 안타까웠다.
워낙 오래 전에 읽은 책이라 내용이 잘 기억나진 않지만, 꽤 감명 깊게 읽었던 기억이 있기 때문이다.

이 책의 내용을 한줄로 요약하자면 "열정을 가지고 끊임없이 수련하라" 가 되겠다.
업계에 입문하며 소프트웨어 엔지니어로 일한다는 것은 평생 공부하는 것이란 말을 들었었다.
잘 나가는 기술 한두개만 익혀두면 평생 굶을 걱정 없을 줄 알았던 꼬꼬마 시절의 내 자신이 떠오른다.
14년이 지난 지금, 그 말의 의미를 지금은 약간은 알 것 같다.
소프트웨어 업계는 변화의 바람이 매우 빠르게 불기에 다양한 기술을 빠르게 펼칠 수 있어야 하니까다.
물론 탄탄한 기본기도 중요하다.
무협지로 치면 내공과 외공을 모두 끊임없이 수련해야 한다는 말이다.
외공이 부족하면 말만 잘하는 연예인 개발자가 되기 쉽고, 내공이 부족하면 금방 한계가 드러나기 마련이다.

이 책의 전반적인 내용과 나름 비슷한 방향으로 일하고 있다는 사실이 신기했고, 안도감을 느꼈다.
하지만 신입때 이 책을 정말 감명깊게 읽어서 이대로 살아야겠다고 생각한 적은 없다.
내 잠재 의식은 책의 영향을 받았을 수도 있겠지만.
나는 운이 좋아서 그간 훌륭한 분들을 많이 만나고 곁에서 일할 수 있었다.
그분들의 업무를 대하는 자세, 시간 관리 기법 등을 보고 배울 수 있었다.
훌륭한 분들은 대부분, 디테일에서는 차이가 있을지언정 큰 흐름에서는 다들 비슷한 가치관을 보여주셨다.
그런 좋은 영향력에 알게 모르게 감화되고, 내 자신을 바꿔오다 보니 이렇게 된 것 같다.
또한 받은 만큼 나도 동료들에게 도움이 되는 사람이 되어야겠다.

나는 내 커리어 확인을 위해 면접을 한 해에 2-3회 정도 본다.
그럼으로써 내가 가진 기술이 시장에서 여전히 통하는지, 내 말투나 태도가 상대방을 불쾌하게 하지 않는지를 계속 확인한다.
'네카라쿠배당토' 중 한 기업에 지원했을 때는 서류 탈락한 적도 있다.
적지않은 충격이었으나 사실을 직시하고 채용담당자께 솔직한 피드백을 부탁드렸었다.
운 좋게도 정말 열정적인 분을 만났다.
개발팀으로부터 직접 피드백을 전달받아 주신 것이다.
비록 서류 탈락이었지만 큰 힘이 된 사건이었다.
이런 경험들을 쌓아가며 내 이력서와 경력이 잘 팔리는지 계속 점검하고 있다.
책의 '자신을 브랜딩하라' 는 장의 내용을 알게 모르게 실천하고 있는 자신을 발견했을 때 뿌듯했다.
 
'진정한 전문가가 되어라' 라는 장의 내용도 매우 큰 의미로 다가왔다.
우리 일은 저수준 지식이 없더라도 의외로 큰 지장이 없다.
제품을 만드는 일에는 저수준 지식보다는 분석력과 다양한 경험이 훨씬 더 중요하기 때문이다.
하지만 저수준 지식이 없는 사람은 일반적이지 않은 상황에서 문제를 해결할 수 없다.
트래픽이 몰려온다거나, 예상하지 못한 입력이 발생한다거나, 악의적인 공격을 받는다던지 하는 상황들이다.
이것들은 흔하지는 않지만 일단 한번 발생했을 때 빠르게, 제대로 해결하지 못하면 비즈니스 성장에 큰 걸림돌이 된다.
전문가는 이런 상황에서 진정한 빛을 발한다.
즉, 서비스를 길게 유지보수 한 경험은 결코 무시할 수 없다는 뜻이다.
분명 그들은 말도 안되는 괴상한 상황들을 어떤 식으로던 극복한 경험이 있기 때문이다.
또한 탄탄한 저수준 지식을 가진 사람은 새로운 기술을 빠르게 습득할 수 있기도 하다.
나도 덕분에 프로로 일해본 적은 없지만 golang, python 회사에 실제로 합격하기도 했다.
탄탄한 기본기로 무장한 전문가는 시장 변화에 유연한 사람이 될 수 있다.

이는 '인생에 투자하라' 는 서장의 내용과도 이어진다.
나는 주변과 팀원들에게 항상 '기술이 망하더라도 내 커리어가 망해서는 안된다' 는 말을 한다.
직업안정성(job security) 을 위해 인생에 투자해야 한다는 것이다.
그러나 주변의 후배들이나, 이제껏 만나봤던 수 많은 후보자들은 커리어보다는 기술에 초점을 맞추는 사람들이 훨씬 더 많았다.
물론, 무언가를 만드는 일은 즐거우니 기술 그 자체를 추종하는 현상을 이해하지 못하는 것은 아니다.
다만 그 시간이 길어질 수록, 기술의 운명에 자신의 커리어를 맡기는 꼴이 된다.
2022년 현재 유행하는 Spring framework, React 같은 기술이 2032년에도 유효할까?
잘 모르겠다.
프로그램 언어를 이용해 코딩하는 일은 2032년에도 유효할까?
알파코드가 등장한 시점에서, '그렇다' 라는 말을 쉽게 할 수 없다.
 
누군가가 알아듣도록 잘 설명해서 일을 시키는 행위가 사라질까?
그건 아닐 것 같다.
이를 우리 업에 치환해 보자면 다음과 같다.
코딩은 기계에게 사람이 원하는 결과를 낼 수 있도록 설명하는 일이다.
게다가 기계는 바보라서 사람의 말도 잘 알아듣지 못하며 모든 과정을 하나하나 일일히 설명해야 한다.
그렇기에 2022년 현재까지도 어려운 컴퓨터 언어를 기계어로 바꾸는 복잡한 과정을 거쳐야 한다.
그런데 알파코드는 충분히 똑똑해서 이미 지금도 사람의 말을 바로 알아들을 수 있으며 그 능력은 점점 더 좋아질 것이다.
그리고 우리는 미래에 똑똑한 알파코드에게 자연어로 일을 시킬 것이다.
앞서 확인한 '내공' 과 '외공' 이야기에 덧붙이자면 이렇게 말할 수 있다.
코딩이라는 외공을 수련하되, 프로그래밍의 본질인 내공에 더 집중해야 앞으로도 살아남을 수 있다.
이 말을 팀원들과, 주변에 항상 하고 다니는데 과연 내 진심이 얼마나 전해질런지는 잘 모르겠다. 

책을 덮으며 나도 나름대로 저자인 채드 파울러와 비슷한 삶을 살고 있는 것 같아 안도감을 느꼈다.
다만 이 안도감이 자위가 되지 않으려면, 은퇴하는 그날까지 꾸준히 수련해야 한다.
그리고 이 과정을 즐거운 자극으로 받아들일 수 있는 방법도 끊임없이 찾아봐야겠다.
