= The Passionate Programmer(프로그래머, 열정을 말하다) 독서 감상문
Jaewon Kim <jw.kim@sirloin.co.kr>
// Metadata:
:description: 입문교육 3주차 제공 도서의 독서 감상문입니다.
:keywords: passion, growth, professionalism
// Settings:
:doctype: book
:toc: left
:toclevels: 4
:sectlinks:
:icons: font

개인적으로 공감되는 부분도 많고, 책의 내용을 토대로 원래 가지고 있던 생각을 더욱 확장할 수도 있어서 재밌게 읽었다.

제목에서부터 드러나듯이 『The Passionate Programmer』는 다른 사람의 계획을 따라가는 데 그치지 않고, '삶을 사랑하는 가장 중요한 열쇠'로써 우리의 일을 대하며, 주도적으로 정진해 나가다 보면, 탁월한 수준에 도달할 수 있다는 내용을 담고 있다.

____
나는 색소폰 연주자로서 자신에게 정말로 전혀 투자하지 않았다. 일이 굉장히 쉽게 잘 되어 만족한다고 생각했다. 또 연주하는 밴드에서 내가 늘 조언을 하는 사람이어서 동료한테서 압박감을 느끼지 않았다. 깨닫지 못했지만 나는 천천히 침체되고 있었다.
____

일과를 소화하는 것만으로도 바쁘고 벅찬 시기를 겪고 나면, "바쁘게" 일과를 소화했고 "실수 없이" 업무를 마무리했다는 것만으로도 충분하다는 생각이 들곤 했다. 제 몫을 다하는 것만으로도 조직 내에서는 쉽게 자리 잡을 수 있었고, 다른 동료들에게 모범이 되는 구성원으로 인정받을 수도 있었지만, 그게 내가 성장하고 있구나 하는 느낌으로 이어지지는 않았던 것 같다.

그렇게 지난 커리어를 마무리하게 됐고, 머지않아 소프트웨어 개발의 문을 두드리게 됐다. 학부 시절에는 경영학을 전공했으며, 대학원에 진학하면서는 (지난 커리어를 발전시켜 보고자) 교육공학 및 행정을 전공했던 내가 뜬금없이 전직을 목표로 소프트웨어 개발을 공부하겠다고 하니까 주위에서는 응원만큼이나 걱정이 많았다.

그러나 그 이상의 도전 의식을 느낄 수 없다는 게 분명했기 때문에 결정은 바뀌지 않았고, 이후에는 부트캠프와 독학을 거쳐 프론트엔드 엔지니어로서 커리어를 시작하게 되었다.

____
자신의 달걀을 전부 다른 사람의 바구니에 넣지 말라.
____

소프트웨어 개발에도 트렌드가 있다 보니까 초심자의 입장에서는 어떤 기술을 선택할 것인지에 대한 고민이 굉장히 크게 다가왔던 것 같다. jQuery는 한물간 기술이니 쳐다도 보지 말 것이며, React/Vue/Angular 중에서도 React 진영의 규모가 압도적이니 취업하려면 반드시 React를 할 줄 알아야 한다, 우선은 REST API를 배워둬야겠지만 조만간 GraphQL이 대체할 것이니 미리 공부해 둬야 한다 등등…

위처럼 트렌드에 관해 수많은 이야기를 들어왔지만, 짧게나마 실무를 경험하면서 깨달은 건 기술의 트렌드보다는 '기술에 담긴 본질'이 중요하다는 것이다. 어쨌거나 설로인이라는 회사에서 개발자로 일하는 것의 본질은 설로인의 상품을 고객에게 판매하는 일련의 과정을 "기술을 활용하여" 지원하는 것에 있다고 본다.

우리가 제공하는 서비스가 React로 개발되었냐, Flutter로 개발되었냐는 고객 입장에서 중요하지 않다. 그저 판매 과정에 필요한 기능들을 React나 Flutter 등을 활용하여 얼마나 더 잘 구현할 수 있는지가 중요하고, 그렇기 때문에 하나의 기술에 얽매이지 않아야겠다는 생각이 들어 이번에 팀을 옮기는 결정도 내릴 수 있었다.

책에서도 한번은 잘 아는 기술로, 그다음 한 번은 경쟁 기술로 각각의 특징을 적극 활용하여 같은 프로젝트를 두 번 구현해 보라고 권하는데, 이는 같은 문제를 더 잘 해결하기 위한 방법을 선택하는 데 필요한 경험을 위한 거라고 생각한다. 제임스 던컨 데이비스의 말처럼, 기술은 그저 성공에 이르는 한 방법일 뿐이다.

____
무언가를 정말 배우고 싶다면 그것을 다른 누군가에게 가르쳐 보라. 어떤 것에 대한 이해를 구체화하는 데 가장 좋은 방법은 다른 사람들이 이해할 수 있도록 그것을 표현하는 것이다. _(중략)_

다른 사람들을 가르쳐 봄으로써 그것을 더 깊이 이해할 수 있다. 누군가를 가르치게 되면 전에는 결코 생각하지도 못했던 질문에 대답해야 할 때가 있다. 가르쳐 봄으로써 자신의 지식 중 모호한 부분이 드러나고 그것을 분명히 인식하게 된다.
____

제일 감명받았던 부분은 '멘토가 되라'라는 챕터였다. 평소에도 가르치면서 배운다는 것의 효과를 알고 있었는데, 소프트웨어 개발을 공부하면서부터는 기술을 익히는 데에도 급급했던지라 누군가를 가르칠 수 있겠다는 여유를 갖지 못했다.

그런데 플랫폼팀으로 합류한 뒤부터 LWIL과 같이 내가 배운 것들을 글로 옮길 일이 생기다 보니까 (내가 쓴 글을 누군가는 읽을 수 있다는 생각 때문에) 자연스럽게 불특정 다수를 상대로 내가 배운 것에 대해 설명을 하고 있는 셈이 되었다.

글을 쓰거나, 누군가에게 설명하는 것 자체가 오랜만이라 아직은 많이 어색하지만, 확실히 내가 배운 걸 글로 정리해 전달하려고 노력하는 것만으로도 단순히 검색 결과를 읽고 끝내는 것보다는 훨씬 도움이 된다. 앞으로는 좀 더 습관화 해두었다가 개인 블로그를 발전시키는 데까지 나아갈 수 있도록 해봐야겠다.
