= The Passionate Programmer(프로그래머, 열정을 말하다) 독서 감상문
youjin <wg.shin@sirloin.co.kr>
// Metadata:
:description: 입문교육 2주차 제공 도서의 독서 감상문입니다.
:keywords: passionate, programmer's mind
// Settings:
:doctype: book
:toc: left
:toclevels: 4
:sectlinks:
:icons: font

# 프로그래머 열정을 말하다

내가 좋아하는 구절 중에, 一以貫之라는 고사성어가 있다. +
하나의 핵심 원리나, 그 학문에서 논리를 다루는 어법을 정말 깊게 이해했다면, +
같은 원리로 다른 부분 또한 설명이 가능하다는 이야기이다. +

저번주차에 읽었던 Extreme Ownership에서 이야기했었던 내용과,이 책에서 이야기하는 내용이 서로 겹치는 바가 많아서 +
시작점이 어디였던가는 상관없이 치열하게 생각하고 검증하다 보면 도달하는 목표 지점은 비슷하다는 것을 한 번 더 생각하게 되었다. +

Extreme Ownership은 조금 더 범용적으로 서술된, 모든 비즈니스에 적용될 수 있는 대원칙들을 설명하는 것에 지면을 할애했다면 +
"프로그래머 열정을 말하다" 이 책은 좀 더 실용적으로 도움이 될 만한 사례를 인용하며, 내가 당장 적용할 수 있는 구체적인 사안들을 소개해주었다는 차이점이 있었다. +

모든 항목에서 설명해주는 사례와 방법들은 충분히 시간을 들여 읽을만한 가치가 있고 적용해 성장해야 하는 주제들이지만 +
그중에서 내가 이전에는 진지하게 생각해보지 못했다던가, 아니면 동감을 많 했었던 항목들에 대해서 밑에 나열해보겠다.

### 기술에 종속되지 않아야 한다. (남의 바구니에 모든 계란을 담지 마라.)
물론 현업에서는 이미 작성되어 공유되는 라이브러리나 프레임워크를 특별한 경우가 아니라면 쓰지 않을 이유가 없다. +
하지만, 어떠한 기술의 생애주기는 나의 커리어의 생애주기보다 짧으므로, +
기술을 "사용하는" 곳에 초점을 맞추는 게 아니라 좀 더 근본적으로 접근하여 그 기술이 어떻게 "구현되었는지"에 관해 집중하는 것이 현명하다고 볼 수 있다.

내가 생각하는 개발자의 역할은, +
제시된 기획안에서 요구하는 서비스의 사양을 현 사업부의 환경 안에서 추천할만한 기술적 솔루션을 제시할 수 있고, +
이를 실제로 코드로 작업해 결과물로서 구현하는 것이 개발자의 역할이라 생각한다. +
사업 목표를 이룰 수 있는 많은 효율적인 방법이 있는데 개발자의 역량 부족으로, 이를테면 현행 기술에 종속되어서 다루지 못하는 기술이라는 이유로 좋은 결과가 예상되는 방법이 있는데 이를 선택하지 못하는 것은 개발자의 역량 부족이기 때문이다. +
따라서 개발자가 꾸준히 기술 트랜드를 쫒아가야하고 기본에 가장 강한 개발자가 되어야 하는 이유는 +
모든 다양한 기술을 커리어에서 사용하기 위함이 아니라, 필요하다면 기꺼이 해당 솔루션을 채용하고, 결과를 도출할 수 있는 능력이 요구되기 때문이라 생각한다.

### 전문가라는 이름은 핑계가 되지 못한다.
현재 우리 팀에서 요구하는 성장 방향과 동일하다고 볼 수 있다. +
프로그래밍의 큰 장점 중의 하나인 추상화는 반복되는 작업을 할 때, 하위 계층의 모든 설정을 다시 작업하지 않도록 "도와주는" 기능이지
추상화된 상위 계층을 다루기 때문에 하위 계층을 몰라도 되기때문이 아니라는 것이다.

### 사랑하지 않으면 떠나라.
고용주와 피고용인 둘 다를 위한 말이라 생각한다. +
다행히도 나는 아직 우리 팀에서 다루는 도매인과 기술에 대해서 흥미를 느끼고 있다는 점이다. +
특히 책에서 설명하는 2주간 자신이 이 일에 가진 열정을 수치화해 기록해보라는 것은 상당히 흥미로웠다. +

### 비즈니스의 전문가가 되어라.
환님이 항상 강조하시는 말이기도 하다. +
서비스를 개발한다는 행위는 결국 비즈니스이고, 해당 도메인에 대한 충분한 지식과 사용자에 대한 깊은 공감이 결여된 상태에서는 결코 좋은 결과물이 나오지 못한다. +
내가 임금을 받는 이유는 아름다운 코드를 작성한 걸 보고 하늘이 감동해서 내려오는 것이 아님을 명심하자. +
좋은 디자인 패턴과 명확한 변수명, 명확한 로직의 코드를 작성하는 것이 권장되는 이유는, 그러한 요건의 코드가 일반적으로 비즈니스에서 좋은 결과를 내었기 때문이다. +
프로그래머가 학문적으로 아름다운 코드를 만들어야 하기 위함이 아니라!

### 멘토를 찾아라, 내가 멘토가 되어라, 자신의 목소리가 들리도록 하자.
세 챕터 모두 네트워크의 중요성에 대해 강조하는 글이다. +
특히 멘토를 찾아 롤모델을 수립하는 전략은 내가 즐겨 사용했었던 전략이다. +

멘토라는 롤모델을 설정함으로써 명확한 이미지를 가질 수 있게 되고 +
그 이미지와 현 시점의 나를 비교하며 어떠한 요건을 충족시켜야 하는지 +
또한, 어떠한 우선순위를 기반으로 자원의 효율적인 분배를 통해 짧은 시간 안에 많은 성장을 도와줄 수 있는 전략이다. +
아직은 내가 남에게 도움을 줄 수 있을 정도로 기술적으로 완성되지 않았다고 생각해 타인의 멘토가 되는 부분은 아직 생각하지 않고 있었는데, +
생각해보니 나름대로 취업을 목표하는 예비 구직자 중에서 전공자가 아닌 사람들에게 내가 겪었던 시행착오들이나 노하우를 공유할 수 있겠다는 생각이 들어, 차차 시도해 볼까 한다.

### 유지 보수를 즐겨라.
내가 이해한 바로는 하기 싫은 업무를 받았을 때도 그 안에서 창조성을 발휘해 나에게 득이 될 방법을 만들어 진행하는 것이 +
결과적으로 나에게도, 사측에도 도움이 된다는 의미로 이해했다.

### 8시간 열중하기.
장시간 근무가 너무 당연하게 요구되었던 이전 경험에서 얻은 학습 패턴으로 취업을 준비하다가 +
현 직장에 오게 되며 가장 처음 위기감을 느꼈던 부분은 바로 근무 시간 8시간이 너무 짧다는 것이였다. +
하지만 궁극적으로 나의 삶의 윤택함과 사측에서 기대하는 생산성을 만족시키기 위해서는 시간이라는 자원도 그 양을 한정시켜서 귀중하게 관리하고 운용해야 함을 이해하게 되었다. +
너무 많은 자원이 공급되는 환경에서는 그 자원을 가치 있게 쓰지 못한다는 말은 나에게 신선하면서도 왜 내가 진작 이 생각을 하지 못했을까 하는 충격을 주었다.

### 위기관리 (실패하는 법을 배워라, 아니오라고 말해라.)
두 챕터 모두 위기관리애 대해 실사례로 설명하는 챕터였다. +
이 책을 읽기 이전에는 위기관리에 대해 이렇게 진지하게 생각을 할 수 있었던 기회가 없었다. +
이 기회를 바탕으로 앞으로 개발하며 사용할 나의 위기관리 법을 하나씩 쌓아갈 기회로 삼아야겠다는 생각이 들었다.

### 작문 실력이 중요하다.
흔히 생각하는 것 보다도 훨씬 작문 실력이 중요한 것은 이미 몇 가지의 사례를 통해 알고 있음에도, 나의 작문 실력을 향상하기 위해 특별한 노력을 하지 않았다는 반성을 하게 되었다. +
이 부분은 성장시키기 위해서 오랜 시간이 소모될 것이고, 당장 지금부터 착수해야 하는 부분임을 알게 되었다. +
오늘부터 나의 작문 실력을 올리기 위해 어떤 방법을 사용할 수 있는지에 대한 고민이 필요하다 생각이 들었다. +

## 결론
전주 차에 읽었던 책과 이 책이 말하는 바가 큰 흐름에서 같은 내용의 주장을 하고 있고 +
내가 여태껏 성장하고자 하였던 방향이 두 개의 책에서 말하는 방향과 너무 다르지 않다는 점이 아주 엇나가지 않고 있다고 하는 자신감을 받을 수 있었던 기회였다.
