= The Passionate Programmer(프로그래머, 열정을 말하다) 독서 감상문
youjin <howyoujini@sirloin.co.kr>
// Metadata:
:description: 입문교육 2주차 제공 도서의 독서 감상문입니다.
:keywords: passionate, programmer's mind
// Settings:
:doctype: book
:toc: left
:toclevels: 4
:sectlinks:
:icons: font

# 프로그래머, 열정을 말하다

회사 임원면접을 볼 때 였다. "유진님은 성장을 위해서 어떤 노력을 하시나요?" +

"성장..." +

성장이라는 단어가 사실 내게는 보이지 않고 마치 안개처럼 답답한 느낌이 있다. 어렸을 때 성장이라는 단어는 내게 희망과 설렘을 안겨줬었다면 이제 성장이라는 단어는 솔직히 안개가 낀 것처럼 좀처럼 눈에 보이지 않는, 희미한 존재 같았다. 그래서 내가 마련한 대책은 하루하루에 대한 투두리스트를 세워서 70%이상을 달성하면 하루 동안 성장한 지표로 삼기로 했다. 이렇게 하루하루를 살다보면 한달 뒤 나는 비록 한달 전보다는 성장해 있을 것이고 향후 몇 년 뒤에는 성장해 있지 않을까, 하고 기대하면서 말이다. +

이 책을 읽게 되면서 정말 좋은 영향력을 지닌 책이라며 지인들께 추천하였다. 그만큼 나에게는 개발뿐만 아니라 20대 중반이 흔히 겪는 인생노잼시기에서 꺼내 줄 것 같은 책이었기 때문이다. 더불어 "소프트웨어 엔지니어"라는 직무에 한껏 어깨가 무거웠는데 더 무거워지게 된 계기가 되기도 했다. 무거워졌다는 것은 부정적인 뜻은 아니며 그 만큼 내가 전문가가 되려면 한 기술만 어느 정도 안다고 뽐내는 것이 아니라 그 기술을 바탕으로 "본질, 개념"을 파악하여 어떤 문제가 닥쳐도 해결할 줄 아는 지혜를 갖춰야한다고 느꼈기 때문에 나의 역할에 대한 무게를 다시 느낄 수 있었다. +

책 내에서 크리스라는 사람은 마이크로소프트에서 제안이 왔음에도 본인의 흥미와 반짝이는 즉흥에 이끌려 마음맞는 사람들과 "깃허브" 프로젝트를 진행하였다. 간접적으로 그 경험을 듣고 나서 정말 흥미로웠다. 나는 내가 하는 모든 작은 것들이 수많은 잘하는 기술자들 사이에서 허술하고 보잘것 없이 느꼈던 적이 참 많았다. 사실 거대한 무언가를 만들 때에도 굉장히 작은 것에서 시작되는 것일텐데 나는 나의 작은 것들을 무시하고 있었던 것이었다. 결국 작은 것이 점점 커져 많은 사람들이 사용하는 거대한 무언가가 된다는 태도로 프로그래밍을 해야겠다고 다짐했다. +

그리고 업무 중 완전히 이해하지 못한 측면에 대해 다시한번 생각해봐야겠다. 직접 파고 들어야하는 부분에 있어서 "어떻게 작동하는가," "왜 이렇게 해야하는가,"를 적당히 파고 들다보면 나도 모르게 업무가 내 것이 되어있지 않을까? 항상 이렇게 생각하다보면 끝없이 달려가게 되는데 사실 정말 방대한 컴퓨터 지식에서 뚝딱 하루만에 모든 것을 통달 할 수는 없다. 하루하루 조금씩이라도 알고 가는 것이 중요하다. +

전문직에 종사하시는 부모님 덕에 나도 크면 전문직을 해야 성공하는 것이라 생각했던 것 같다. "전문가"라는 말이 어린 나에게는 멋있게 다가왔나보다.  자신이 깊게 배우고 많이 겪은 분야를 전문으로 하게 되면 남들에게도 그 부분에서 많은 도움이 될 것 같았다. 하지만 전문가는 그만큼 역할에 대한 책임도 컸으며 어떤 것을 전문으로 한다해도 다른 것들과 융합적인 사고를 할 줄 알아야 했다. 그렇다면 전문가 역할의 무게는 경험치와 비례할까? +

소프트웨어 분야에서 전문가는 과연 어떤 사람이어야할까? 이 책에서는 한 특정 기술분야에만 집중하지 않고 그 기술의 본질에 집중하여 본질을 꿰뚫는 연습을 해야한다고 말한다. 아래 3가지 문구는 다음에 다시 한번 더 꺼내어 보기 위해 작성해 두었다. +

- 컴파일 방식이면서 가상기계 위에서 동작하는 프로그래밍 언어를 사용한다면 시간을 들여서 가상 기계가 어떻게 동작하는지 내부 구조를 공부해보라  +

- 자신이 사용하는 언어가 가상기계에 의존하든 그렇지 않든 소스 파일을 컴파일 할 때 무슨일이 일어나는지 시간을 내 공부해보라  +

- 예를 들어 j2ee 어플 서버 전문가가 되고 싶다면 어플 서버를 설정하고 배치하는 방법을 자세히 배우는데 노력을 기울이는 대신, 시간을 따로 마련해서 오픈 소스 제이보스나 제로 니모 서버를 받아 서버 운영 뿐만 아니라 내부 구조를 공부해 보라  +

개발 직무에 뛰어들게 되면서 나는 묘한 기분을 느낀다. 나는 업무시간에 일을 하는 것인가, 공부를 하는 것인가? 사실 이렇게 까지 돈을 받으면서 공부를 하고 있어도 되나 싶은 마음이 자리잡고 있어서 불편할 때가 있다. 개발직무에서는 개인이 성장이 곧 회사의 성장이고 회사의 성장이 곧 개인의 성장이라는 것을 잘 알고 있다. 하지만 적어도 돈을 받고 업무를 통해 "성과"를 도출해야하는 상황에서 마냥 즐겁게 공부만 할 수는 없지 않은가, +

이 책에서는 이런 해결방안을 "재즈연습"에 비유하여 설명한다. 재즈 연습은 크게 3가지 범주로 나누어 설명할 수 있다. +

1. 몸에 익히기 +
2. 악보읽기 +
3. 즉흥연주 +

- 몸에 익히기 : 
선택한 프로그래밍 환경에서 멀티 스레드 프로그래밍이 동작하는 방식에 대해 확실하게 파고들어보는 것처럼 직접 코드현장에서 경험을 통해 연습해보는 것이다. +

- 악보 읽기 : 
악보를 처음 보고 거의 완벽하게 이해하고 연주할 수 있는 능력은 무엇보다도 중요한 것처럼 요구 명세서나 설계를 보고 빠르고 정확하게 읽는다는 것은 매우 중요한 일이다. 타인들과 함께 협업이 많은 프로젝트일수록 해당 코드이해력은 곧 개발자의 몸값이 되기도 할 것이다. 오픈 소스 소프트웨어, 오픈 소스 커뮤니티를 즐겨보며 이를 많이 경험해보는 것이 좋을 것 같다. 진짜 목표는 자신이 보고 있는 것을 최대한 빨리 이해하는 것이며 반드시 다양한 소프트웨어로 작업해보는 것이 한 기술에 특정하지 않고 본질을 이해하는 것이다. +

- 즉흥연주 :
즉흥연주는 새롭게 무언가를 만드는 것이다. 글쓴이는 프로그래머로써 뭔가 스트레스를 받을 때 즉흥성이 발현된다는 사실을 알게 되었다고 했다. 나는 해당 문제에서 벗어나 완전히 다른 부분을 시각적으로 겪고 있을 때 즉흥성이 발현된다는 것을 알고 있다. 나의 이런 부분을 통해서 아키텍쳐나 최적화 로직, TDD에서 창조적이고 위트 있는 인사이트를 발견하여 하나씩 조건을 추가해보면서 연습을 해본다면 확실히 발전 할 수 있을 것 같다. +

이 모든 것을 공연(근무) 도중에 연습을 하지말라고 제안한다. 연습시간을 따로 내어 실전(근무)에 투입되기전에 많은 연습을 하라고 하셨다. 사실 이 부분에 대해서는 더 많은 선배개발자들과 얘기를 해보면서 라이프 사이클을 어떻게 관리하는지 알아가 봐야겠다. 개인적으로는 업무를 하고 나면 집에 와서 저녁식사와 독서를 하고 룸메이트와 잠깐 산책과 대화하면 시간이 금방 12시가 되어간다. 다음날을 위해 또 일찍 잠이 들고 이를 5번 반복하게 되는데 시간관리를 코어하게 하는 방법을 나름 터득해야겠다. +
