= 2022년 LWIL(Last week I learnt) 모음
// Metadata:
:description: Last Week I Learnt
:keywords: study, til, lwil
// Settings:
:doctype: book
:toc: left
:toclevels: 4
:sectlinks:
:icons: font

[[section-202203-W5]]
== 2022년 3월 5주

- hwan: Apple M1 기기에 Jenkins 설치는 Java 8 설치부터 빡세다. AArch64 용 OpenJDK 8 이 없어서, Azul 같은 배포판을 이용해야 한다.
- gon: aggregate에 대한 이해도가 상승하였다. 개념적 모델인 도메인은 물리적 모델과 연관을 끊고 순수해질수 있게하는 개념이다.
- yoonho: 네이비씰 승리의 기술을 보면서 우선 순위를 정하는 것의 중요성을 알았다. 전체적인 그림에 있어서 한가지 업무에 매몰되면 목표 달성에 있어서 차질이 생길수도 있다.

[[section-202204-W1]]
== 2022년 4월 1주
- gon: 코틀린의 operator에 대하여 학습하였다. 연산자 오버라이딩을 할 경우 객체의 표현으 좀 더 다양하게 할 수 있게 되었다.
- yoonho: 프로그래머, 열정을 말하다를 읽으면서 특정 기술에 종속되는 것은 좋지 않다는 것을 알게 되었다. 기술을 이루는 근본(?)에 대한 앎이 중요하다고 생각했다.
- youjin: 코드없이 UI를 제작하고 firebase, API를 지원해서 빌드까지 할 수 있는 link:https://flutterflow.io/[flutterflow] 개발이 있다는 것을 알게 되었고 빠르게 프로토타입을 제작해야 할 때는 부분적으로 활용해볼 수 있겠다고 생각했다. 
- hwan: javascript 에서는 *A = C, B = C 이면 A = B 다* 라는 명제가 성립하지 않는 케이스가 있다. 이렇게.
+
[source,shell]
0 == "0"  // true
0 == []   // true
"0" == [] // false  << 헐?!?!
  
[[section-202204-W3]]
== 2022년 4월 3주

- hwan: 유튜브 미트러버 채널 보면서 육류에 대한 지식을 좀 더 늘려갈 수 있을 것 같다.
- gon : 지도 API는 국내 한정으론 카카오가 제일 좋은것 같다. 네이버는 위치를 지정해서 검색이 불가능하다.
- yoonho : '이용자가 많은 생각을 하게 만드는 서비스를 만들지 않도록 해야겠다.' 라는 생각을 '소프트웨어 누가 개떡같이 만든거야'를 읽으면서 하게되었다.
- youjin: Xcode로 실행을 시켜보려다 이런 에러를 마주쳤다. 이는 루비의 패키지 매니저인 gem이 mac에 의존적이면서 생기는 문제였다. rbenv를 통해 문제를 해결할 수 있었다.
+
[source,shell]
$ gem install bundler
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.3.0 directory.
    
    
[[section-202204-W4]]
== 2022년 4월 4주

- gon : B햄버거프랜차이즈는 쿠폰을 사용하여 결제하고 취소 할 경우 쿠폰이 사용 처리되는 기이한 프로세스를 가진다.
- yoonho : 심야버스 첫차는 9호선 출퇴근보다 혼잡하다는 것을 알게 되었다.
- hwan : 저수준 JDBC 직접 구현할 때:
+
[source,java]
----
DataSource#getConnection#createStatement 이후에

statement.close 뿐 아니라
connection.close 도 꼭 같이 해줘야 한다
----
+
JdbcTemplate 같은거 오래 쓰다보니 이 기본을 놓쳐 삽질 4시간 했다 ㅠㅠ

- youjin: link:https://flowingdata.com/2015/12/15/a-day-in-the-life-of-americans/[미국인의 하루 flowing data] 를 확인해보면서 "데이터"가 제공하는 가치, 그리고 데이터를 어떻게 가공하고 시각적으로 표현하는지에 따라 어떻게 하면 사용자들에게 정보를 신선하게 제공할 수 있을까 생각해볼 수 있었다.

[[section-202205-W1]]
== 2022년 5월 1주

- hwan : 구현 비용, graceful shutdown 대응 등을 고려, 기성품인 spring kafka 를 도입했다. 그런데 `KafkaListener` 가 무조건 비동기라서 메시지 수신 이후 특정동작 수행 같은 통합 테스트 시나리오 구현이 어려웠다. 테스트 검증은 결국 메시지 수신 이후의 기대동작을 poll 하는 형태로 구현했다.
- gon : kotlin의 sql 프레임워크인 exposed를 사용해보았다. 생각보다 가벼워서 좋은 프레임워크이지만 아직? 좀 불편하다. 
- yoonho : 최근 읽는 쉽게 만드는 클린아키텍처라는 책에서 '패키지 구조는 아키텍처와 코드간의 갭을 줄이는데 도움을 줄 수 있다.' 라는 문구가 기억에 남았다.
- youjin: 데이터를 수집하고 학습하고 정보제공, 결과 등의 반복을 통한 머신러닝을 "link:https://www.tensorflow.org/[tensorflow]"라는 시스템을 통해 쉽게 해볼 수 있다는 것을 알게 되었다. tensorflow는 수치를 계산하고 기계학습을 하는 오픈소스 라이브러리이다. 현재는 tensorflow.js 로 지원해주고 있어서 js로도 사용해볼 수 있을 것 같다.

[[section-202205-W2]]
== 2022년 5월 2주

- youjin: link:https://thegithubshop.com/[github Shop]에서 티셔츠를 판다.. 우연히 알고리즘에 이끌려 개발자들의 데일리룩에 대해서 인터넷 서핑을 해보다가 깃헙쇼핑몰을 알게 되었다. 언젠가 한번은 대한민국 개발자들에게 데일리룩 설문조사를 해보고 싶다. 현재까지는 개발자 데일리룩에 대한 떠도는 밈들만 있지만 통계자료가 있다면 재밌을 것 같다. 무엇보다 너무 궁금하다.
- hwan: CLI 에서 Github deploy key 를 쓰는 법은 다음과 같다.
. 키 생성:
+
[source,shell]
----
ssh-keygen -t ed25519 -C "your_email@example.com"
----
. github project 에 에 1단계에서 생성한 deploy key 추가
. ssh-agent 에 identity 추가
+
[source,shell]
----
eval `ssh-agent -s`
ssh-add ~/.ssh/id_ed25519_<SSH_KEY>
----
. `~/.ssh/config`` 에 다음과 같이 추가
+
[source,shell]
----
Host github.com          # 이거 이름 아무거나 지어도 됨
  HostName github.com
  User git               # 중요
  IdentityFile /home/alice/.ssh/alice_github.id_rsa  # Private Key 여야 함
  IdentitiesOnly yes     # 중요
----
. `git clone` 으로 체크아웃

이렇게 하면 조직 기능 없이도 이용자들을 접근제한 하는게 가능해진다. 외주 업체와의 협업 시나리오에서 유용하다.

- wongue: 지난주에 link:https://ohou.se/productions/773067/selling?utm_source=google_shop&utm_medium=cpc&utm_campaign=uc_web-all-all-google_shop_pmax&utm_term=773067&utm_content=ssc&affect_type=UtmUrl&gclid=Cj0KCQjw1N2TBhCOARIsAGVHQc7niZxsyOaIf8aJEuGwjTs0BvScixjyYm-V77uFrHvjTp7Jt2NncDoaAn7rEALw_wcB[카페트 타일]이라는 인테리어 소품을 발견해서 바로 사서 자취방에 시공해봤다.
셀프 인테리어는 하지 말자는 결론을 얻게 되었다... 비싼 돈을 받는데에는 이유가 있는거구나. +
기술적으로는 한창 dart의 언어 특성에 대해서 공부하는 중이다.

- gon : git브랜치의 구조를 잘 다루게된 한주가 되었다 체리픽과 리셋만 잘 다루어도 pr 나누기 등 다양한 조작이 가능해진다.

- yoonho : 외국어는 자신감이 중요하다는 것을 새삼 깨달았다.

[[section-202205-W3]]
== 2022년 5월 3주
- hwan: Flutter 명령이 hang 될때:
. https://stackoverflow.com/questions/54191643/flutter-doctor-hangs-on-start-no-output
. OSX 에서는 '인터넷에서 다운로드한 프로그램을 실행하시겠습니까?' ui 로 인해서 hang 될 수도 있음. `ps` 로 좀비 프로세스 아닌거 확인한 뒤에는, ui 를 바로 확인해 보자.
. 우리 OSX CI 서버에서 flutter app 빌드가 안되는 문제는 바로 osx 의 UI 가 hang 을 걸어서 발생한 문제였었다... System UI 를 켤 일이 잘 없다 보니 발생하는 문제였음
. OSX CI 서버의 빌드가 잘 안 될 때는 Remote desktop 등으로 UI 를 바로 확인해 보자.

- youjin: 개인적으로는 CLI를 활용하여 파일을 찾거나 실행하는 것을 선호한다. Android Studio SDK의 link:https://developer.android.com/studio/command-line[cmdline-tools]을 주말동안 뜯어보았다. 그리고 Android Studio를 실행하지 않고 emulator에 연결되어있는 avd를 실핼할 수 있었다. 먼저 sdk 에 대해서 알아야했는데 처음에 sdk 경로가 어딨는지 몰라서 한참을 헤맸다. 알고보니 Android Studio > Preference에서 SDK Location을 보면 확인할 수 있었다. link:https://developer.android.com/studio/build/building-cmdline?hl=ko[명령줄에서 바로 앱 빌드]하는 방법은 셸 스크립트를 사용하면 가능했다. 
[source,shell]
----
./emulator --list-avds    // emulator 에 연결되어 있는 것 찾기
----
[source,shell]
----
emulator @avd_name [ {-option [value]} … ]    // emulator 에 연결되어 있는 avd(Android Virtual Device)를 실행하기
----
[source,shell]
----
./gradlew task-name    // Mac, Linux에서 앱 빌드하기
----
관련된 헷갈린 용어들은 avd(Android Virtual Device), adb(Android Debug Bridge), apk(Android Application Package) 등이 있었고 이는 약자를 풀어보니 이해할 수 있었다.

- gon: 설로인 생일 쿠폰은 한번에 사용해야합니다. 20만원어치 고기파티 각 

- wongue: flutter의 flutter_bloc, bloc, provider 세 가지의 상태 관리 모듈에 대해 알아보는 중입니다. +
  모듈의 사용방법을 습득하는것과 동시에 React에서는 화면의 UI구성을 먼저 생각하고 화면을 그리기 위한 state를 구현했다면, bloc을 그 의도에 맞게 사용하기 위해서는 먼저 사용할 data 클래스를 정의한뒤 비즈니스 로직을 정의하고, 그 뒤 화면을 구현하는 방식으로 구현하는 사고 과정을 완전히 다르게 생각하기를 요구하는 느낌을 받았습니다.
  
  - yoonho : 코드리뷰 관련 영상을 보면서 인상이 갔던 댓글이 있었다. +
  1. actionable한 제안없이 애매모호한 comment를 남기는 것 +
  2. 자신도 잘 알지 못하는 document를 가지고 와서 더 좋은 방법이 있을 수 있으니 찾아보라는 것 +
  3. PR blocing 할만한 것이 아닌데 nit picking comment로 merge를 막는 것 +
  을 지양해야한다는 댓글이었다. +
  신경을 써야겠다는 생각이 들었고, 소프트 스킬이 중요하다는 것을 새삼 깨달았다. 

[[section-202205-W4]]
== 2022년 5월 4주
- hwan: 
. dart 에는 Pattern matching 이 없어서 불편한데, link:https://github.com/dart-lang/language/blob/master/working/0546-patterns/patterns-feature-specification.md[이런 Proposal] 이 올라와 있는 것을 발견했다.
. 2022-05 현재 Linux IntelliJ 에서  flutter web 을  개발할때 GPU 렌더링이 느린 이유는 link:https://github.com/flutter/flutter/issues/96919[Github issue link]의 내용대로, snap store 에서 내려받는 google chrome 에 뭔가 이상한 문제가 있기 때문이다.

- wongue::
```
취업 준비를 할 때 많은 도움을 주셨던 멘토님이 최근 성공적으로 이직을 하시게 되어 그동안 도와주신 부분에 대한 감사를 표시할 겸,
커리어 코칭을 받기 위한 겸 점심 식사를 대접하며 어떠한 방식으로 커리어를 성장해야 하고, 임하는 태도는 어때야 하는지에 대한 많은 대화를 나누었다.

정말 신기할 정도로 환님이 반복적으로 강조하시는 부분을 중요하게 생각하시는 것을 확인하게 되었던 경험이었다.
크게 새 가지 부분을 강조해 주셨는데,

첫째로는 기술에 매몰되지 말아야 한다.
학교의 교수님들이 같은 내용을 30년 넘게 강의하실 수 있는 이유는
아무리 기술이 발전해도 결국은 이러한 지식을 가진 개발자여야 제약 없이 개발할 수 있기 때문이라고 한다.
프레임워크나 라이브러리는 생애주기가 빠르지만,
OOP, TDD, 계층 분리, 의존성 관리 등 핵심 디자인 패턴과 이를 가능하게 하는 관련 CS 지식은 사람이 생각하는 방식이 변화하지 않는 이상 꾸준히 도움이 될 지식이라는 것.

둘째로는 블로그 포스팅을 통한 자신의 PR의 중요성에 대하여 말씀해주셨다.
자신이 기술적으로 얼마나 성장했든 간에 이 성장이 가치가 있으려면 타인이 이를 인정해줄 때 가치가 생기는 것 하지만,
이에 관해 노력하는 개발자들이 그리 많지. 않다는 말씀이셨다.
남들이 잘하지 않는다는 것은, 내가 조금만 노력해도 투자 대비 더 많은 이득을 볼 수 있다는 것.
블로그 포스팅을 할 때 찾아볼 수 있는 글을 적는 것 보다는 그 횟수를 줄이더라도 고유하고 나만의 특성을 강조할 수 있는 글이여야 한다.
동시에 예상 독자들이 관심을 가질만한 주제를 선정해 적어야 한다고 말씀해주셨다.
플랫폼은 링크드인을 추쳔해주심.

마지막으로는 지속해서 성장을 하기 위해서는 오프라인 위주의 개발자 커뮤니티가 필요하지 않나 고민하고 계신다고 말씀해주셨다.
내가 많이 약한 부분이 아닐까 생각이 들었다.
같은 일을 하는 학교 동기를 찾기 힘든 상황에서 나는 어떤 식으로 커뮤니티를 구성하고 이를 확장해야 하는지에 대한 숙제를 얻게 되었다.
```

- gon: 코틀린에서의 block: T.() -> R과 block: (T) -> R차이를 알게되었다. 전자는 리시버로 묵시적전달, 후자는 파리미터로 명시적 전달이다.
그래서 람다내 코드블록에서 this와 it의 범위의차이가 있다.

- youjin: flutter 3.0이 출시되면서 업그레이드 된 점을 간단히 알 수 있었다. 
1. link:https://github.com/flutter/flutter/issues/91605[material design 3]을 Flutter 3.0과 함께 사용할 수 있게 된다. 
2. link:https://firebase.google.com/docs/flutter/setup?hl=ko&platform=ios[flutter용 firebase] firebase에서 공식적으로 flutter를 지원한다.

- yoonho: 객체간 비교에서 comparable을 구현하면 비즈니스 코드의 로직을 줄일 수 있다.
          비교하는 로직이 복잡할수록 빛을 발한다.

[[section-202205-W5]]
== 2022년 5월 5주

- hwan: 

. `* whois.co.kr` 에 등록한 도메인을 AWS Route 53 으로 변경하기

.. Route 53 의 NS Record 에 있는 ns domain 들의 목록을 확인
.. whois.co.kr 접속 후 네임서버 정보 변경 항목에서 NS Host 이름들을 Route 53 의 정보로 변경
.. A 레코드 등록
.. 5분 정도 대기
.. `dig @ns-1264.awsdns-30.org meatgo.co.kr` 커맨드로 ns 등록 잘 되었나 확인 (ns 값은 서비스에 따라 다를 수 있음)

. AWS 에서 `*.meatgo.co.kr` 도메인 인증서를 발급하기 위해:

.. AWS Certificate Manager 페이지에 접속해 `meatgo.co.kr` 및 `*.meatgo.co.kr` 도메인의 인증서를 발급한다. 유형은 DNS Validation 으로 결정한다.
.. Pending Validation 상태의 CNAME Record 를 확인할 수 있다.
.. CNAME name, CNAME value 항목을 AWS 53 의 해당 site 의 CNAME record 로 추가한다.
.. 몇분 기다린다.
.. Issued 상태로 나오나 확인한다.
.. `dig meatgo.co.kr` 커맨드로 ns 등록 잘 되었나 확인한다.
.. 인증서 정보를 확인해 보자.
.. 단, AWS CM 에서 발급받은 인증서는 export 가 불가능하기 때문에 사실상 AWS 서비스 내에서만 쓸 수 있다. 강력한 Lock-in effect 를 노린 것 같은데... 무서운 녀석들.

- youjin: flutter에서 theme 속성(테마 속성)은 앱의 일괄되는 테마를 정할 수 있다. 기본적으로는 `theme: ThemeData(
        primarySwatch: Colors.red
      ),` 이라고 쓴다. primarySwatch는 theme 속성 덩어리기 때문에 Colors는 Accent가 붙은 키워드는 사용 할 수 없다. (예시: pinkAccent) `theme: ThemeData(
        // POINT : 나중에 primarySwatch custom 해보기 - 모듈 작성
        primaryColor: Colors.pinkAccent,
      ),`Accent가 붙은 키워드를 사용하려면 단일 color 속성으로 지정해야한다. 다크테마도 사용할 수 있는데 휴대폰 자체에서 다크테마를 사용하면 다크테마가 자동으로 된다고 한다. 다음에 활용하면 업데이트 해봐야겠다. 
- yoonho: 응급(?)환자를 위한 대처 방법에 대해 알아두는 것이  느꼈다.

- gon : spring data mongo를 활용해 mongodb에 다하여 알게된 한주 였습니다.
