= 2022년 3분기 07월-09월 LWIL(Last week I learnt) 모음
// Metadata:
:description: Last Week I Learnt
:keywords: study, til, lwil
// Settings:
:doctype: book
:toc: left
:toclevels: 4
:sectlinks:
:icons: font


[[section-202207]]
== 2022년 7월

[[section-202207-W2]]
=== 2022년 7월 2주

- wongue: flutter 의 material 에서 제공해주는 MaterialStateColor와 FocusNode를 arg로 받는 Inkwell을 이용해 위젯을 구현하려고 시도했지만, material 에서 default로 세팅된 값이 너무 많아서 의도한 디자인 대로 위젯을 동작사키기가 힘든 단점이 있다. +
가능하면 materialState를 사용하는것 보다는 flutter core 에서 제공해주는 focus 위젯등을 사용해 직접 stateful 하게 위젯을 구현하는것이 더 좋은 방향인것 같다. + 
직접 위젯의 상호작용을 구현해놓으면, 타 패키지의 의존성을 줄임 + 의도한 바 대로 위젯의 디자인을 구현하기 쉬움 + 차후 side effect 가 날 가능성이 적어지는 정도의 장점을 가진다. +
물론 차후 상호작용을 담당하는 부분에 대한 코드가 위젯별로 파편화되어있어 유 보수가 진행되야 할 경우 비용이 올라간다는 단점또한 같이 생기게 되지만, front의 코드 특성상 재작성될 확률이 크다 판단하였다.

- youjin: https://github.com/features/copilot[github copilot]이 진짜 나왔다. github copilot 은 코딩할 때 자동완성 스타일 제안을 제공하는 AI 페어 프로그래머이다. + 
	유료라서 당장 사용하진 못하지만, vscode, intellJ, Android Studio 등 몇몇 IDE 환경에서 Extension 과 Plugin 형태로 제공해준다. +
	설치 후 도구 > github copilot > login to github 을 하면 승인요청을 할 수 있다. 특히 Python, JavaScript, TypeScript, Ruby, Go, C# 및 C++ 에서 잘 작동된다고 한다. +
	클래스를 생성하거나, 함수를 작성하려고 이름을 선언할 때, 코드의 컨텍스트와 스타일이 일치되는 코드를 회색라인으로 자동생성한다. 혹은 자동생성코드를 원할때, 주석으로 아래와 같이 입력을 통해 실행시킬 수 있다. 
+
[source, java]
----
	// find all images without alternate text
	// and give them a red border
	void process () {
		... // github copilot 이 주석명령을 알아듣고 알아서 코드를 생성시킴
	}
----
+ 
내가 코드를 직접 짜지 않고 github copilot 을 사용하여 코드를 자동생성하더라도, 코드퀄리티나 보안은 `개인의 책임` 에 있다고 한다. 즉, 앞으로 코드를 작성할 때는 명확한 변수명 선언(클린코드)과 가능한 작은 단위의 함수 생성(클린아키텍쳐)의 중요성이 더 키질 것으로 생각된다. dart 도 지원이 된다면, 한번 사용해보고 싶다 !

- hwan: 
+
. AWS 의 네트워크 관련 설정은 대부분 낙장불입이라, 처음 만들때부터 잘 해야 한다. 개인적으로 매우 불편하다.

. lwil: EC2 NAT instance 를 쓰려면 masquerade 설정만으로는 안 되고, AWS console 에서 networking > Change Source/Dest. Check 를 반드시 비활성화 해 줘야 한다.
+
이것 때문에 또 삽질 2시간 했다.
+
설정 제대로 되었나 확인하려면:
+
[source, shell]
----
# 다음 명령 실행 결과가 1이어야 함
$ cat /proc/sys/net/ipv4/ip_forward

$ sudo iptables -nL POSTROUTING -t nat -v
Chain POSTROUTING (policy ACCEPT 27 packets, 2222 bytes)
 pkts bytes target     prot opt in     out     source               destination         
   96  6529 MASQUERADE  all  --  *      eth0    0.0.0.0/0            0.0.0.0/0            /* NAT routing rule installed by fck-nat */
----

. `net-tools` 의 도구들은 이제 가급적 쓰지 말라고 하는데 아직까지 `iptables` 의 대체재인 `nftables` 는 사용법을 잘 모르겠다.
+
[source, shell]
----
# NAT 규칙 추가
$ iptables -t nat -A PREROUTING -p tcp -i eth0 --dport ${LOCAL_PORT} -j DNAT --to ${REMOTE_HOST}:${REMOTE_PORT}

# NAT 규칙 확인
$ iptables -t nat -L --line-numbers

# NAT 규칙 삭제
$ sudo iptables -t nat -D PREROUTING {rule-number-here}
----

- gon : 코틀린에서 다음과 같은 mokito를 이용한 검증 부분을 짯는데 에러가 낫다

[source, kotlin]
---
then(mockRepo).should(times(1)).save(any())
---

npe가 발생하였는데 이유를 알아보자 하니 any() 이 부분이 자바mokito를 사용하여 그렇다 
자바mokito는 any()는 null을 주입한다 save파리미터는 not null의 타입이라 에러가 발생하는것이다
그래서 다음과같은 모듈을 사용하여야한다

[source, kotlin]
---
then(mockRepo).should(times(1)).save(org.mockito.kotlin.any())
---

[[section-202207-W3]]
=== 2022년 7월 3주

- hwan: firewall 뒤에 있어서 direct access 가 불가능한 host 에 local ssh tunnel 로 접근하는 법
+
[source,shell]
----
ssh -NT -L ${LOCAL_ADDR}:${LOCAL_PORT}:${REMOTE_HOST}:${REMOTE_PORT} ${SSH_JUMPHOST_USER}@$${SSH_JUMPHOST}
----
+
이때 `REMOTE_HOST` 나 `REMOTE_PORT` 는 `SSH_JUMPHOST` 기준에서 보이는 IP 주소로, localhost 에서 보이지 않더라도 상관없다.
+
이렇게 SSH Tunnel 을 만들면 외부에 공개되지 않은 private network 에도 접근할 수 있다.


- gon :
jpa로 Kotlin JDSL Reactive도 사용이 가능하다
하이버네이트가 반응형을 이제 지원한다고 한다.
https://github.com/line/kotlin-jdsl/blob/main/reactive-core/README.md
지난주 영화 헤어질결심을 봤는데 강추드린다. 아가씨나 올드보이, 박쥐 등을 재미있게 보셧다면 강추 +

- youjin : 이태원에 갔었는데 택시를 잡는 게 너무 어려워서 카카오택시 어플을 사용하는 것 보다 iM 택시가 조금 비싸더라도 잘 잡힌다. 이류를 물어보니 iM 택시 1500 대를 더 풀었다고 한다. +
- yoonho : 주말동안 탑건을 봤다. 예전 탑건을 보셨던분들이 무척 감명깊게 보셨다고 하는 말이 있는데 어떠한 관점일지.. 궁금했다. 영화는 좋았다.

[[section-202207-W4]]
=== 2022년 7월 4주

- youjin: flutter provider 패키지를 만든 사람이 https://riverpod.dev/ko/docs/getting_started[riverpod] 이라는 데이터바인딩 프레임워크를 만들었다. (참고로 riverpod 는 provider 의 철자로 만들어진 단어이다.) 이는 provider 의 단점을 보완한다. `ProviderNotFoundException` 예외를 발생시키지 않고, `BuildContext` 없이 Provider를 수신할 수 있는 기능이 포함되어 있다.

- yoonho: +
admin task를 진행하면서 commerce-api-core의 product domain에서 여러가지 enum class 를 만들고 수정을 해야했다.+
from method에 유효하지 않은 값이 인입시 null 을 반환해야하는지, 에러를 발생시켜야하는지, 아니면 UNDEFINED 라는 element를 반환해야하는지에 따라 +
admin 에서도 여러번의 수정을 거쳐야 했다. +
객체지향 사실과 오해 초반부의 '객체지향 애플리케이션의 아름다움을 결정하는 것이 협력이라면 협력이얼마나 조화를 이루는지를 결정하는 것은 객체다.' 문단을 읽으면서 이러한 수정을 거쳐야했던 기억이 떠올랐다. +
우리가 만드는 어플리케이션 또한 작은 객체들의 협력의 모음으로 구성이되고,
각 객체가 어떻게 설계되는지에 따라 협력 또한 얼마나 잘 할수있는지가 결정된다. +
라는 생각이 들었다.

- wongue: dart TEST 파일을 parts 로 분할 할 때, part 의 파일명을 _test.dart 로 끝내면 melos run test 에서 part 의 파일이 실행되어 package 를 찾을 수 없어 test fail 이 난다. + 
+ TDD는 미리 안해놓으면 일이 두배가 된다.

- hwan: spring boot 에서 testcontainer 쓸 때 다음처럼 환경설정을 해 주면
+
[source,yml]
----
spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mysql://localhost:59306/platform_commerce?serverTimezone=UTC&useUnicode=true&character_set_server=utf8mb4&TC_REUSABLE=true;
----
테스트에서 직접 testcontainer 를 환경설정 해 주지 않더라도 테스트 lifecycle 동안 알아서 container 가 올라갔다가 내려온다.
ContainerDatabaseDriver 내부에서 container 를 자동 실행시키고 proxy 하는 기능이 있다.
+
참고 URL: https://github.com/testcontainers/testcontainers-java/blob/master/modules/jdbc/src/main/java/org/testcontainers/jdbc/ContainerDatabaseDriver.java#L124


[[section-202207-W5]]
=== 2022년 7월 5주

- hwan: `autossh` 를 이용해 ssh tunnel 을 항상 서비스처럼 실행하도록 하는 법
+
. 환경변수 파일을 만든다. `yourjumpsshserver` 는 적당한 문자열로 바꿔줄 것.
+
[source,shell]
----
## 파일명: /etc/default/secure-tunnel@yourjumpsshserver

TARGET=yourjumpsshserver
LOCAL_ADDR=0.0.0.0
LOCAL_PORT=22
# port that will be use to ssh at remote server
REMOTE_PORT=54322
# change user as per remote server
USERNAME=user
# change SSH port used at jump server
SSH_TARGET_PORT=22
----

. `systemd` 서비스 정의 파일을 만든다.
+
[source,shell]
----
## 파일명: /etc/systemd/system/secure-tunnel@.service

[Unit]
Description=Setup a secure tunnel to %I
After=network.target

[Service]
Environment="LOCAL_ADDR=localhost"
EnvironmentFile=/etc/default/secure-tunnel@%i
Environment="AUTOSSH_GATETIME=0"
ExecStart=/usr/bin/autossh -M 0 -o "ExitOnForwardFailure=yes" -o "ServerAliveInterval 30" -o "ServerAliveCountMax 3" -NR ${REMOTE_PORT}:${LOCAL_ADDR}:${LOCAL_PORT} -p ${SSH_TARGET_PORT} ${USERNAME}@${TARGET}

# Restart every >2 seconds to avoid StartLimitInterval failure
RestartSec=5
Restart=always

[Install]
WantedBy=multi-user.target
----

. 서비스를 등록한다.
+
[source,shell]
----
# systemctl enable secure-tunnel@yourjumpsshserver.service && systemctl start secure-tunnel@yourjumpsshserver.service
----

. service 동작 여부를 확인해 본다.
+
[source,shell]
----
# systemctl status secure-tunnel@yourjumpsshserver.service
----
+
- youjin: 인스타를 이용하다가 어느 날부터 개인정보 동의를 구하는 버튼이 뜨기 시작했다. 자세히 알아보니, 메타가 다음 달 8일까지 필수적으로 개인정보 관련한 동의를 구한다고 한다. 총 6가지로 개인정보의 수집 및 이용, 개인정보의 제공, 개인정보의 국가 간 이전, 위치 정보, 개인정보 처리방침 업데이트, 이용 약관 등이다. 메타는 개인정보에 따라 '맞춤형 정보'를 제공하기 위해서라고 한다. 이는 한국 이용자들에게 반발을 사고 있고, 국내 개인정보보호법에서도 "이용자가 필요 최소한의 개인정보 이외의 개인정보를 제공하지 않는다는 이유로 서비스의 제공을 거부해서는 안 된다"고 규정하고 있다고 한다. 앞으로도 어떻게 콘텐츠가 전달될지 궁금하다. 
그리고, 인스타 UX UI 가 업데이트 되었는데 개인적으로는 너무 불편하다. 친구들과 얘기를 해보니 랜덤하게 업데이트 된 것 같다. 나는 우연히 업데이트가 된 것 같은데, 북마크 기능이 바로 보이지 않으며 피드를 무조건 하나씩만 볼 수 있게 변경되었다. +
- wongue: 주말동안 남는 시간에 flutter docs를 짬짬이 읽어봤다. flutter 는 ui를 C++ 기반의 엔진인 Skia에 의존하여 표현한다는걸 알게됬다. +
따라서 flutter ui의 기능의 한계 또한 skia 엔진에 제한될 꺼라 생각되니, 앞으로 간단하게 skia 엔진을 알아볼 생각이다. +
+ flutter widget test에서 find.byType메소드로 넘겨쥬는 인자중, 제너릭을 받는 타입은 이를 명시하여야만 한다. +
(ex find.byType(Radio<int>);)
- gon: kotlin으로 jpa를 사용하던 도중 lazy로딩이 예상과 다르게 동작하였다 원인을 살펴보니 코틀린은 모든 클래스를 final로 상속불가로 만든다 하지만 jpa는 엔티티를 상속받아 프록시객체를 만들어 동작하는데 이부분에서 오는 차이때문이라고 생각된다. 그래서 entity어노테이션이 붙으면 상속가능하도록 설정하니 문제해결되었다. +
- yoonho: 
엑셀의 함수를 이용해 UUID를 생성할 수 있다.
+
[source,excel]
----
=CONCATENATE(DEC2HEX(RANDBETWEEN(0,4294967295),8),"-",DEC2HEX(RANDBETWEEN(0,65535),4),"-",DEC2HEX(RANDBETWEEN(16384,20479),4),"-",DEC2HEX(RANDBETWEEN(32768,49151),4),"-",DEC2HEX(RANDBETWEEN(0,65535),4),DEC2HEX(RANDBETWEEN(0,4294967295),8))
----
+
but 새로운 내용이 입력될 때마다 값이 매번 갱신되므로 값(이미 나온 UUID)를 한번 복사해주어야한다.


[[section-202208]]
== 2022년 8월

[[section-202208-W1]]
=== 2022년 8월 1주

- hwan: Android studio 에서 Flutter project 를 열면 간혹 Logcat, Profiler 등이 안 뜨는 경우가 있어 굉장히 불편하다. 이 때는, File > Project Structure 메뉴에 진입한 후, Project Facet 에 Android 설정이 빠져있는건 아닌지 한번 확인해 보자. 간단한 설정인데 3주동안 못 찾아서 고생했다. ㅜㅜ

- wongue: dart와 node.js 비슷한 특성을 공유한다. dart 의 병렬성을 정리한 김에 node.js 에서는 어떤 방식으로 구현했나 찾아봤는데, cluster 모듈을 사용해 멀티코어 프로그레밍을 구현 할 수 있다고 한다. +
++ 메모리를 공유하지 못하는걸 보아하니 thread 보다는 isolate 에 가까운것 같다.

- gon: 젯브레인에서 인텔리제이를 이은 차세대 ide를 개발하고 있다 한다 https://www.jetbrains.com/ko-kr/fleet/?_ga=2.128332367.2134819592.1659250788-12276751.1658968519&_gac=1.224601576.1659250790.CjwKCAjwrZOXBhACEiwA0EoRD00otOS5qQT8mjf9oI1JvymbgaLOh4NsCWqJZiXaOlBGLoemRoBM3xoCTNAQAvD_BwE&_gl=1*1gl9j9d*_ga*MTIyNzY3NTEuMTY1ODk2ODUxOQ..*_ga_9J976DJZ68*MTY1OTI1MDc4OC42LjEuMTY1OTI1NDg0My41Mw

- youjin: 딥링크란, 앱에서 링크를 타고 들어가는 링크를 의미한다. 안드로이드에서는 '앱링크'를 사용하고, iOS에서는 '유니버셜 링크'를 활용한다고 한다. 그런데, 이 방식은 몇몇 브라우저에서는 잘 적용되지 않을 가능성이 있어서 Deferred DeepLink를 많이 활용한다. 이는 앱이 설치되어 있으면: 앱이 바로 열리면서 해당 컨텐츠 실행하고, 앱이 설치되어 있지 않으면: 딥링크 동작을 지연시켰다가 앱설치이후 실행되었을때 해당 컨텐츠를 실행하는 방식이다. 친구 추천코드로 활용할 때 많이 쓰인다고 한다.

[[section-202208-W2]]
=== 2022년 8월 2주

- wongue: flutter에서 UI를 위해 사용되는 Tree는 한 종류만 있지 않다는걸 알게되었다. +
그 중, paint와 layout을 담당하는 트리가 있는데, 이러한 tree의 순회를 O(n)의 시간에 구현하기 위해 트리의 상위 노드는 자식 노드에 대해 아무런 정보도 들고 있지 않고, 이를 위해 BuildContext가 필요함을 알게되었다. +
++ await 으로 동기화 시키지 않은 비동기함수는 동작을 예상하기도, 이를 검증하기도 쉽지 않다는것을 느꼈다.

- hwan: AsciiDoc 은 MD 와 달리 Passthrough Block 라는 기능을 명시적으로 선언해야 HTML tag 를 삽입할 수 있다. 그렇지 않으면 HTML tag 는 전부 escape 된다.
+
HTML 을 그냥 삽입할 수 있는 MD 대비 보안상 더 나은 모델인 것 같다.
+
[source,asciidoc]
----
++++
<a download="example.txt" href="data:application/octet-stream;base64, ...">Download example.txt</a>
++++
----
+
같은 형태로 활용 가능하다.

- gon: jpa에서 soft delete를 지원한다 서버 api에 적용해보면 굉장히 편리할것 같다
- youjin: 노션과 비슷한 옵시디언 노트가 출시되었다. 아직은 major 버전이 0 이긴하지만 유심히 살펴볼 필요가 있다. 노션보다 웹접근성은 조금 떨어지지만, 아무리 많은 파일을 생성해도 노션처럼 버벅이거나 무거워지지 않는 장점이 있다. 그리고 무엇보다, 노션은 디렉토리 구조처럼 파일을 정리할 수 있는 장점이 있지만 옵시디언노트는 사람의 뇌구조와 비슷하게, 파일들과 연결여부를 선으로 연결시켜, 시각적으로 보여준다.

[[section-202208-W3]]
=== 2022년 8월 3주
- gon: sql에서 uuid를 직접 인서트할려고 다음과 같은 방법으로 진행하였다
+
[source,sql]
----
insert into someTbl(fk_id, uuid) values (17, '2A6270D93F724FCBB270BF66ABD75100');
----
+
하지만 에러가 발생하였다 원인을 살펴보니 uuid를 직접인서트해야할땐 
+
[source,sql]
----
(unhex(replace(''2A6270D93F724FCBB270BF66ABD75100'',''-'','''')))
----
+
이런식으로 uuid를 변환해야한다
+
추가로 mysql 8부터 UUID_TO_BIN 같은 함수가 지원된다 한다 
mysql에서 해결하였으나 현재 h2에서 막혀있다

- hwan: dart 에서 conditional import 하기
+
[source,dart]
----
import '_file_downloader_native.dart'
    if (dart.library.html) '_file_downloader_web.dart' as file_downloader;
----
+
근데 이 기능이 왜 dart language tour 에는 없는지 궁금하다. 아무튼 이렇게 하면 조건부 import 를 할 수 있다.
+
https://github.com/dart-lang/sdk/issues/34262#issuecomment-416129832
+
여기 보면 적용 범위가 매우 제한되어 있음을 확인할 수 있다. 그래서 공식 문서에는 안 나와 있나 보다.

- youjin: 인터스텔라 같은 컴퓨터 영화중에 명작이 없을까 찾아보다가 다들 매트릭스를 추천해주어서 매트릭스 1을 봤다. 거기에 인스턴스들과 오퍼레이터 등등 아는 단어가 나와서 다시 한번 다들 보는 걸 추천드린다.

- wongue: goole 에서 새로 발표한 carbon lang 에 관심이 가 조금 알아봤다.
+ 처음에 기대한 것은 c++ 의 로우 레벨을 담당할 다음 세대 언어를 기대했는데, (Rust 의 경쟁자 언어) 알아보니 그런 목적보다는, 이미 구글은 수많은 c++ 기반 레거시 코드들을 가지고 있는 상황인데, c++ 언어의 기능 추가를 구글에서 원하는 방향대로 진행 할 수 없다보니, 내부의 유-보수 를 위해 c++ 호환 언어 하나를 만들었다는 느낌이 강하다.

[[section-202208-W4]]
=== 2022년 8월 4주
- hwan: 삼복 더위라고 일컫는 초복, 중복, 말복은 고대 중국에서 유래한 풍습이라고 한다. 닭이나 개를 잡아먹은 이유는 소, 돼지와 달리 키우는 비용이 매우 저렴하며 농경 사회에서 단백질과 지방 섭취 기회가 흔하지 않았기 때문이란다. 그리고 닭과 개는 십이지의 끝쪽에 있는 동물들이며 오행 사상에서는 이들이 가을을 상징한다고 보았단다. 이 동물들을 하늘에 제물로 바침으로써 더위가 빨리 물러가고, 가을이 빨리 오기를 기원하는 의미라고 한다.

- wongue: 지난주간 저수준 문자열에 관래 다룰 일이 생기며 알게된 사실인데, 고수준 문자열 타입 String 의 첫글자가 대문자로 시작하는건 Java에서 String은 Primitive Type 이 아닌 Object 로 구현되었던 점 부터 유래한 관습적인 명명법인것을 알게되었다. +
하지만 꼭 모든 언어에서 지켜지는것은 아닌듯하다. 반례로 c++ 에서는 <string> 은 소문자로 시작한다. 

- gon : mysql에서 JSON type의 컬럼일 경우 안에 컬럼 안족 값에 검색을 걸수 있다는 것을 알게되었다. 물론 속도이슈나 여러 조인시 어떠한 인덱스를 타는지 확인은 해봐야겠지만 가끔 검색하는 api나 데이터 분석용으로 넣는 데이터를 json으로 넣는건 고려해볼만 한것 같다.

- youjin: 사람들이 하는 활동에는 최적으로 느끼는 각도가 있다고 한다. 업무,게임,독서 등은 108도, 영화,TV는 130도, 휴식,취침은 170도가 인체공학적인 자세각도이다. 바른 자세의 습관이 평생습관을 좌우할할테니 앞으로 바른 자세로 코딩을 하자.

[[section-202209]]
== 2022년 9월

[[section-202209-W1]]
=== 2022년 9월 1주
- wongue: dart 는 내부적으로 Map 을 https://api.dart.dev/be/175791/dart-collection/LinkedHashMap-class.html[_LinkedHashMap Class] 로 구현한다. +
linkedHashmap은 hask table 과는 다르게, 입력된 키의 순서를 보장한다. +
이러한 특성을 보장하기 위해, hashtable과 별개로 키의 입력 정보가 저장된 Doubly-Linked List 를 추가로 들고있기 때문에, 단순한 hash table(or dictionary) 에 비해 메모리를 더 소모하는 단점또한 가지고 있다.

- hwan: Infra 를 이용한 Test 는 항상 `@SpringBootTest` 만 써서 하다보니 몰랐지만 `@SpringBootTest` 가 느린 환경에서 Test slice 를 적용할 경우 Repository 등을 내가 수동으로 등록해 줘야 하는 테스트 환경이 생기기 시작한다.
+
특히 jpa 의 경우 spring-data-jpa + hibernate 가 JPA 의 전체인양 착각하고 있었는데, Test slice 환경에서는 EntityManager 를 저수준에서 직접 제어해야 하는 경우가 종종 있다. 가령, Read-only repository 를 테스트해야 하는 상황이라던지.
+
Slice 환경에서 Test 를 작성하다 보면 Persistent context 와 Entity Lifecycle 을 왜 자세히 알아야 하는지 몸으로 체감할 수 있다.
+
.System Under Test
[source,kotlin]
----
interface ReadOnlyUserRepository {
    fun findById(id: Long): User
}

interface UserRepository : ReadOnlyUserRepository {
    fun save(user: User): User
}
----
+
.UserRepository Test code
[source,kotlin]
----
@SpringBootTest
class RepositorySpec {
    @Autowired
    private lateinit var sut: UserRepository

    @Test
    fun `저장한 자료를 잘 찾아올 수 있다`() {
        // given:
        val data = randomUser()

        // when:
        val saved = sut.save(data)

        // then:
        val found = sut.findById(saved.id)

        // expect:
        assertThat(found, `is`(saved))
    }
}
----
+
.ReadOnlyUserRepository Test code
[source,kotlin]
----
@SpringBootTest
class RepositorySpec {
    @Autowired
    private lateinit var sut: ReadOnlyUserRepository

    @Autowired
    private lateinit var em: EntityManager

    @Test
    fun `저장한 자료를 잘 찾아올 수 있다`() {
        // given:
        val data = randomUser()

        // when:
        em.persist(data)
        em.flush()

        // then:
        val found = sut.findById(data.id)

        // expect:
        assertThat(found, `is`(saved))
    }
}
----

[[section-202209-W2]]
=== 2022년 9월 2주
- wongue: dart 의 제너릭을 제대로 이해하지 못해서 1시간동안 삽질을 하며 알게 된 사실.
+
[source,dart]
----
String testFuntion(String parm) => parm;

class TestClass<String, T> {
	String get testArg;
	Function<String> testmethod() => testFunction(testArg);
}
----
+
이거 신텍스 에러 난다. 왜냐면 제너릭의 타입 지정은 사용하는 측에서 해야하기 때문. ... 그러면 원시타입 관련해서는 예약어로 만들어주면 안됬을까.

- hwan: jpa 의 `@Embeddable` 안에 있는 `@Column` 은 적용 안된다. 또한 `@AttributeOverrides` 로 column 을 override 할 경우 @Lob 설정 등이 날아가기 때문에 조심해야 한다.

- gon : 제주도의 날씨예보는 믿지 않는것이 좋다 4일동안 비100%였지만 비가안왔다 파도도 안높았다;
기술 애기 : 코틀린/js로 개발시 라이브 뷰? 기능이 굉장히 느리게 작동한다 이유는 kotlin -> js로 컴파일을 거친다음 랜더링을 해야하기때문이다.
개인적은 맛보기 후기로는 이문제가 해결되지 않으면 FE의 메인기술이 되기가 힘들것으로 보인다

- youjin: testParams 로 테스트를 검증하는 로직을 작성했는데, 이때 `Late Initial Error` 가 났다. 그때 해결방법은 `TestWidgetFlutterBinding.ensureInitialized()` 를 해주면 됐다.
궁극적으로 이 에러가 난 이유는, test() 가 실행되는 순서때문이었는데, 먼저 late하게 변수가 선언되고(아직 할당이 되지 않은 채) setUp에서 할당을 바로 해줄꺼라고 기대하지만, 바로 expectTestParams() 함수가 실행이 된다. 그래서 late error 가 났던 것이다. `TestWidgetFlutterBinding.ensureInitialized()` 를 통해 초기화를 강제하니까 오류를 바로 잡을 수 있었다.
+
[source,dart]
----
void main() {

        group('', () {
          late MockType mockType;
          late Api api;
          late RepositoryImpl repositoryImpl;

          setUp(() {
	    mockType = = MockType(true);
            api = MockApi();
            repositoryImpl =
                RepositoryImpl.newInstance(mockType: mockType, api: api);
          });
	  
	  ...
	  void expectTestParams(){
	  	test('', (){});
	  }
	  ...
	  
----

[[section-202209-W4]]
=== 2022년 9월 4주
- gon: 이번 재고관리를 위한 cache용 솔루션을 redis를 선택하였다. +
단순히 빠르기를 위함이라면 mysql의 memory db를 사용하는 방법도 있었지만 redis를 선택한 결정적 이유는 다음과같습니다. +
`redis는 단일 쓰레드를 사용하여 분산 잠금이 필요없다 또한 Master - Slave의 구조로 되어있어 변경사항에대하여 동기화를 지원합니다`
mysql의 memory의 경우 lock이 테이블단위로 수정이 일어나면 모든 요청이 대기해야합니다. 즉 분산잠금이 필요합니다.

- hwan: 다음과 같은 값 객체가 있다고 하고,
+
[source, kotlin]
----
data class OrderedValue(
    val value: String,
    val order: Int
): Comparable<OrderedValue> {
    override fun compareTo(other: OrderedValue): Int = this.order.compareTo(other.order)
}
----
+
`OrderedValue` 를 담은 `Collection<OrderedValue>` 를 정렬된 Collection 으로 바꾸려면 

.. {empty}
+
[source, kotlin]
----
Collection<OrderedValue>.toSortedSet()          // returns Set<OrderedValue>
----
+
vs
.. {empty}
+
[source, kotlin]
----
Collection<OrderedValue>.toSet().ordered()      // returns List<OrderedValue>
----
+
둘 중 무엇을 써야 할까?
+
둘 중 1 은 만약 order는 같고 value가 다른 collection 들이 있을 경우, order 기준으로 하나만 남긴다.
+
따라서 이런 현상을 막으려면 모든 field 를 compare 시점에 활용하도록 구현해야 한다.
+
참고로 TreeSet 의 JavaDoc 을 읽어보면 이런 구문이 있다.
+
[source, java]
----
/*
 * <p>Note that the ordering maintained by a set (whether or not an explicit
 * comparator is provided) must be <i>consistent with equals</i> if it is to
 * correctly implement the {@code Set} interface.  (See {@code Comparable}
 * or {@code Comparator} for a precise definition of <i>consistent with
 * equals</i>.)  This is so because the {@code Set} interface is defined in
 * terms of the {@code equals} operation, but a {@code TreeSet} instance
 * performs all element comparisons using its {@code compareTo} (or
 * {@code compare}) method, so two elements that are deemed equal by this method
 * are, from the standpoint of the set, equal.  The behavior of a set
 * <i>is</i> well-defined even if its ordering is inconsistent with equals; it
 * just fails to obey the general contract of the {@code Set} interface.
 */
----

- wongue: testing을 위해 unique 하면서 random한 문자열이 필요한 일이 생겼다. +
처음에는 그리 어렵지 않을것이라 생각했지만, 두 조건을 모두 만족시키는 문자열을 생성하는 로직은 반복될수록 매우 무거운 연산이 필요하다는걸 알게됬다. +
timestamp나 counter등을 사용해서 생성하는것이 최선일 듯 하다.( O(n) 의 시간복잡도를 달성하려면. ) +
이것이 싫다면 칸토어의 대각선 논법을 응용해 O(NM) (N: 생성할 문자열의 개수 M: 문자열의 자리수) 로 다항식 시간내에 유일하고 임의적인 문자열을 생성할 수도 있을것이다.

- yoonho: 도메인 관련 내용을 테스트하는 경우에 외부 세계의 로직을 타는 경우가 있다. +
이런 경우 테스트 내용은 외부 세계의 detail에 관심이 없기 때문에 구체적인 구현 보다는 항상 pass하도록 통으로 mock을 만들거나 하여 +
테스트 내용과 상관 없는 부분에는 최대한 손이 가지 않도록 해야한다.

- youjin: 구글의 이스터에그를 발견했다. 크롬에서는 인터넷이 안될 때 뜨는 창에서 방향키로 공룡게임을 할 수 있다.
