= 2022년 LWIL(Last week I learnt) 모음
// Metadata:
:description: Last Week I Learnt
:keywords: study, til, lwil
// Settings:
:doctype: book
:toc: left
:toclevels: 4
:sectlinks:
:icons: font

[[section-202203-W5]]
== 2022년 3월 5주

- hwan: Apple M1 기기에 Jenkins 설치는 Java 8 설치부터 빡세다. AArch64 용 OpenJDK 8 이 없어서, Azul 같은 배포판을 이용해야 한다.
- gon: aggregate에 대한 이해도가 상승하였다. 개념적 모델인 도메인은 물리적 모델과 연관을 끊고 순수해질수 있게하는 개념이다.
- yoonho: 네이비씰 승리의 기술을 보면서 우선 순위를 정하는 것의 중요성을 알았다. 전체적인 그림에 있어서 한가지 업무에 매몰되면 목표 달성에 있어서 차질이 생길수도 있다.

[[section-202204-W1]]
== 2022년 4월 1주
- gon: 코틀린의 operator에 대하여 학습하였다. 연산자 오버라이딩을 할 경우 객체의 표현으 좀 더 다양하게 할 수 있게 되었다.
- yoonho: 프로그래머, 열정을 말하다를 읽으면서 특정 기술에 종속되는 것은 좋지 않다는 것을 알게 되었다. 기술을 이루는 근본(?)에 대한 앎이 중요하다고 생각했다.
- youjin: 코드없이 UI를 제작하고 firebase, API를 지원해서 빌드까지 할 수 있는 flutterflow 개발이 있다는 것을 알게 되었고 빠르게 프로토타입을 제작해야 할 때는 부분적으로 활용해볼 수 있겠다고 생각했다. 
- hwan: javascript 에서는 *A = C, B = C 이면 A = B 다* 라는 명제가 성립하지 않는 케이스가 있다. 이렇게.
+
[source,shell]
0 == "0"  // true
0 == []   // true
"0" == [] // false  << 헐?!?!
  
[[section-202204-W3]]
== 2022년 4월 3주

- hwan: 유튜브 미트러버 채널 보면서 육류에 대한 지식을 좀 더 늘려갈 수 있을 것 같다.
- gon : 지도 API는 국내 한정으론 카카오가 제일 좋은것 같다. 네이버는 위치를 지정해서 검색이 불가능하다.
- yoonho : '이용자가 많은 생각을 하게 만드는 서비스를 만들지 않도록 해야겠다.' 라는 생각을 '소프트웨어 누가 개떡같이 만든거야'를 읽으면서 하게되었다.
- youjin: Xcode로 실행을 시켜보려다 이런 에러를 마주쳤다. 이는 루비의 패키지 매니저인 gem이 mac에 의존적이면서 생기는 문제였다. rbenv를 통해 문제를 해결할 수 있었다.
+
[source,shell]
$ gem install bundler
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.3.0 directory.
    
    
[[section-202204-W4]]
== 2022년 4월 4주

- gon : B햄버거프랜차이즈는 쿠폰을 사용하여 결제하고 취소 할 경우 쿠폰이 사용 처리되는 기이한 프로세스를 가진다.
- yoonho : 심야버스 첫차는 9호선 출퇴근보다 혼잡하다는 것을 알게 되었다.
- hwan : 저수준 JDBC 직접 구현할 때:
+
[source,java]
----
DataSource#getConnection#createStatement 이후에

statement.close 뿐 아니라
connection.close 도 꼭 같이 해줘야 한다
----
+
JdbcTemplate 같은거 오래 쓰다보니 이 기본을 놓쳐 삽질 4시간 했다 ㅠㅠ

- youjin: link:https://flowingdata.com/2015/12/15/a-day-in-the-life-of-americans/[미국인의 하루 flowing data] 를 확인해보면서 "데이터"가 제공하는 가치, 그리고 데이터를 어떻게 가공하고 시각적으로 표현하는지에 따라 어떻게 하면 사용자들에게 정보를 신선하게 제공할 수 있을까 생각해볼 수 있었다.

[[section-202205-W1]]
== 2022년 5월 1주

- hwan : 구현 비용, graceful shutdown 대응 등을 고려, 기성품인 spring kafka 를 도입했다. 그런데 `KafkaListener` 가 무조건 비동기라서 메시지 수신 이후 특정동작 수행 같은 통합 테스트 시나리오 구현이 어려웠다. 테스트 검증은 결국 메시지 수신 이후의 기대동작을 poll 하는 형태로 구현했다.
- gon : kotlin의 sql 프레임워크인 exposed를 사용해보았다. 생각보다 가벼워서 좋은 프레임워크이지만 아직? 좀 불편하다. 
- yoonho : 최근 읽는 쉽게 만드는 클린아키텍처라는 책에서 '패키지 구조는 아키텍처와 코드간의 갭을 줄이는데 도움을 줄 수 있다.' 라는 문구가 기억에 남았다.
