= 2022년 LWIL(Last week I learnt) 모음
// Metadata:
:description: Last Week I Learnt
:keywords: study, til, lwil
// Settings:
:doctype: book
:toc: left
:toclevels: 4
:sectlinks:
:icons: font

[[section-202203]]
== 2022년 3월

[[section-202203-W5]]
=== 2022년 3월 5주

- hwan: Apple M1 기기에 Jenkins 설치는 Java 8 설치부터 빡세다. AArch64 용 OpenJDK 8 이 없어서, Azul 같은 배포판을 이용해야 한다.
- gon: aggregate에 대한 이해도가 상승하였다. 개념적 모델인 도메인은 물리적 모델과 연관을 끊고 순수해질수 있게하는 개념이다.
- yoonho: 네이비씰 승리의 기술을 보면서 우선 순위를 정하는 것의 중요성을 알았다. 전체적인 그림에 있어서 한가지 업무에 매몰되면 목표 달성에 있어서 차질이 생길수도 있다.

[[section-202204]]
== 2022년 4월

[[section-202204-W1]]
=== 2022년 4월 1주
- gon: 코틀린의 operator에 대하여 학습하였다. 연산자 오버라이딩을 할 경우 객체의 표현으 좀 더 다양하게 할 수 있게 되었다.
- yoonho: 프로그래머, 열정을 말하다를 읽으면서 특정 기술에 종속되는 것은 좋지 않다는 것을 알게 되었다. 기술을 이루는 근본(?)에 대한 앎이 중요하다고 생각했다.
- youjin: 코드없이 UI를 제작하고 firebase, API를 지원해서 빌드까지 할 수 있는 link:https://flutterflow.io/[flutterflow] 개발이 있다는 것을 알게 되었고 빠르게 프로토타입을 제작해야 할 때는 부분적으로 활용해볼 수 있겠다고 생각했다. 
- hwan: javascript 에서는 *A = C, B = C 이면 A = B 다* 라는 명제가 성립하지 않는 케이스가 있다. 이렇게.
+
[source,shell]
0 == "0"  // true
0 == []   // true
"0" == [] // false  << 헐?!?!
  
[[section-202204-W3]]
=== 2022년 4월 3주

- hwan: 유튜브 미트러버 채널 보면서 육류에 대한 지식을 좀 더 늘려갈 수 있을 것 같다.
- gon : 지도 API는 국내 한정으론 카카오가 제일 좋은것 같다. 네이버는 위치를 지정해서 검색이 불가능하다.
- yoonho : '이용자가 많은 생각을 하게 만드는 서비스를 만들지 않도록 해야겠다.' 라는 생각을 '소프트웨어 누가 개떡같이 만든거야'를 읽으면서 하게되었다.
- youjin: Xcode로 실행을 시켜보려다 이런 에러를 마주쳤다. 이는 루비의 패키지 매니저인 gem이 mac에 의존적이면서 생기는 문제였다. rbenv를 통해 문제를 해결할 수 있었다.
+
[source,shell]
$ gem install bundler
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.3.0 directory.
    
    
[[section-202204-W4]]
=== 2022년 4월 4주

- gon : B햄버거프랜차이즈는 쿠폰을 사용하여 결제하고 취소 할 경우 쿠폰이 사용 처리되는 기이한 프로세스를 가진다.
- yoonho : 심야버스 첫차는 9호선 출퇴근보다 혼잡하다는 것을 알게 되었다.
- hwan : 저수준 JDBC 직접 구현할 때:
+
[source,java]
----
DataSource#getConnection#createStatement 이후에

statement.close 뿐 아니라
connection.close 도 꼭 같이 해줘야 한다
----
+
JdbcTemplate 같은거 오래 쓰다보니 이 기본을 놓쳐 삽질 4시간 했다 ㅠㅠ

- youjin: link:https://flowingdata.com/2015/12/15/a-day-in-the-life-of-americans/[미국인의 하루 flowing data] 를 확인해보면서 "데이터"가 제공하는 가치, 그리고 데이터를 어떻게 가공하고 시각적으로 표현하는지에 따라 어떻게 하면 사용자들에게 정보를 신선하게 제공할 수 있을까 생각해볼 수 있었다.

[[section-202205]]
== 2022년 5월

[[section-202205-W1]]
=== 2022년 5월 1주

- hwan : 구현 비용, graceful shutdown 대응 등을 고려, 기성품인 spring kafka 를 도입했다. 그런데 `KafkaListener` 가 무조건 비동기라서 메시지 수신 이후 특정동작 수행 같은 통합 테스트 시나리오 구현이 어려웠다. 테스트 검증은 결국 메시지 수신 이후의 기대동작을 poll 하는 형태로 구현했다.
- gon : kotlin의 sql 프레임워크인 exposed를 사용해보았다. 생각보다 가벼워서 좋은 프레임워크이지만 아직? 좀 불편하다. 
- yoonho : 최근 읽는 쉽게 만드는 클린아키텍처라는 책에서 '패키지 구조는 아키텍처와 코드간의 갭을 줄이는데 도움을 줄 수 있다.' 라는 문구가 기억에 남았다.
- youjin: 데이터를 수집하고 학습하고 정보제공, 결과 등의 반복을 통한 머신러닝을 "link:https://www.tensorflow.org/[tensorflow]"라는 시스템을 통해 쉽게 해볼 수 있다는 것을 알게 되었다. tensorflow는 수치를 계산하고 기계학습을 하는 오픈소스 라이브러리이다. 현재는 tensorflow.js 로 지원해주고 있어서 js로도 사용해볼 수 있을 것 같다.

[[section-202205-W2]]
=== 2022년 5월 2주

- youjin: link:https://thegithubshop.com/[github Shop]에서 티셔츠를 판다.. 우연히 알고리즘에 이끌려 개발자들의 데일리룩에 대해서 인터넷 서핑을 해보다가 깃헙쇼핑몰을 알게 되었다. 언젠가 한번은 대한민국 개발자들에게 데일리룩 설문조사를 해보고 싶다. 현재까지는 개발자 데일리룩에 대한 떠도는 밈들만 있지만 통계자료가 있다면 재밌을 것 같다. 무엇보다 너무 궁금하다.
- hwan: CLI 에서 Github deploy key 를 쓰는 법은 다음과 같다.
. 키 생성:
+
[source,shell]
----
ssh-keygen -t ed25519 -C "your_email@example.com"
----
. github project 에 에 1단계에서 생성한 deploy key 추가
. ssh-agent 에 identity 추가
+
[source,shell]
----
eval `ssh-agent -s`
ssh-add ~/.ssh/id_ed25519_<SSH_KEY>
----
. `~/.ssh/config`` 에 다음과 같이 추가
+
[source,shell]
----
Host github.com          # 이거 이름 아무거나 지어도 됨
  HostName github.com
  User git               # 중요
  IdentityFile /home/alice/.ssh/alice_github.id_rsa  # Private Key 여야 함
  IdentitiesOnly yes     # 중요
----
. `git clone` 으로 체크아웃

이렇게 하면 조직 기능 없이도 이용자들을 접근제한 하는게 가능해진다. 외주 업체와의 협업 시나리오에서 유용하다.

- wongue: 지난주에 link:https://ohou.se/productions/773067/selling?utm_source=google_shop&utm_medium=cpc&utm_campaign=uc_web-all-all-google_shop_pmax&utm_term=773067&utm_content=ssc&affect_type=UtmUrl&gclid=Cj0KCQjw1N2TBhCOARIsAGVHQc7niZxsyOaIf8aJEuGwjTs0BvScixjyYm-V77uFrHvjTp7Jt2NncDoaAn7rEALw_wcB[카페트 타일]이라는 인테리어 소품을 발견해서 바로 사서 자취방에 시공해봤다.
셀프 인테리어는 하지 말자는 결론을 얻게 되었다... 비싼 돈을 받는데에는 이유가 있는거구나. +
기술적으로는 한창 dart의 언어 특성에 대해서 공부하는 중이다.

- gon : git브랜치의 구조를 잘 다루게된 한주가 되었다 체리픽과 리셋만 잘 다루어도 pr 나누기 등 다양한 조작이 가능해진다.

- yoonho : 외국어는 자신감이 중요하다는 것을 새삼 깨달았다.

[[section-202205-W3]]
=== 2022년 5월 3주
- hwan: Flutter 명령이 hang 될때:
. https://stackoverflow.com/questions/54191643/flutter-doctor-hangs-on-start-no-output
. OSX 에서는 '인터넷에서 다운로드한 프로그램을 실행하시겠습니까?' ui 로 인해서 hang 될 수도 있음. `ps` 로 좀비 프로세스 아닌거 확인한 뒤에는, ui 를 바로 확인해 보자.
. 우리 OSX CI 서버에서 flutter app 빌드가 안되는 문제는 바로 osx 의 UI 가 hang 을 걸어서 발생한 문제였었다... System UI 를 켤 일이 잘 없다 보니 발생하는 문제였음
. OSX CI 서버의 빌드가 잘 안 될 때는 Remote desktop 등으로 UI 를 바로 확인해 보자.

- youjin: 개인적으로는 CLI를 활용하여 파일을 찾거나 실행하는 것을 선호한다. Android Studio SDK의 link:https://developer.android.com/studio/command-line[cmdline-tools]을 주말동안 뜯어보았다. 그리고 Android Studio를 실행하지 않고 emulator에 연결되어있는 avd를 실핼할 수 있었다. 먼저 sdk 에 대해서 알아야했는데 처음에 sdk 경로가 어딨는지 몰라서 한참을 헤맸다. 알고보니 Android Studio > Preference에서 SDK Location을 보면 확인할 수 있었다. link:https://developer.android.com/studio/build/building-cmdline?hl=ko[명령줄에서 바로 앱 빌드]하는 방법은 셸 스크립트를 사용하면 가능했다. 
[source,shell]
----
./emulator --list-avds    // emulator 에 연결되어 있는 것 찾기
----
[source,shell]
----
emulator @avd_name [ {-option [value]} … ]    // emulator 에 연결되어 있는 avd(Android Virtual Device)를 실행하기
----
[source,shell]
----
./gradlew task-name    // Mac, Linux에서 앱 빌드하기
----
관련된 헷갈린 용어들은 avd(Android Virtual Device), adb(Android Debug Bridge), apk(Android Application Package) 등이 있었고 이는 약자를 풀어보니 이해할 수 있었다.

- gon: 설로인 생일 쿠폰은 한번에 사용해야합니다. 20만원어치 고기파티 각 

- wongue: flutter의 flutter_bloc, bloc, provider 세 가지의 상태 관리 모듈에 대해 알아보는 중입니다. +
  모듈의 사용방법을 습득하는것과 동시에 React에서는 화면의 UI구성을 먼저 생각하고 화면을 그리기 위한 state를 구현했다면, bloc을 그 의도에 맞게 사용하기 위해서는 먼저 사용할 data 클래스를 정의한뒤 비즈니스 로직을 정의하고, 그 뒤 화면을 구현하는 방식으로 구현하는 사고 과정을 완전히 다르게 생각하기를 요구하는 느낌을 받았습니다.
  
  - yoonho : 코드리뷰 관련 영상을 보면서 인상이 갔던 댓글이 있었다. +
  1. actionable한 제안없이 애매모호한 comment를 남기는 것 +
  2. 자신도 잘 알지 못하는 document를 가지고 와서 더 좋은 방법이 있을 수 있으니 찾아보라는 것 +
  3. PR blocing 할만한 것이 아닌데 nit picking comment로 merge를 막는 것 +
  을 지양해야한다는 댓글이었다. +
  신경을 써야겠다는 생각이 들었고, 소프트 스킬이 중요하다는 것을 새삼 깨달았다. 

[[section-202205-W4]]
=== 2022년 5월 4주
- hwan: 
. dart 에는 Pattern matching 이 없어서 불편한데, link:https://github.com/dart-lang/language/blob/master/working/0546-patterns/patterns-feature-specification.md[이런 Proposal] 이 올라와 있는 것을 발견했다.
. 2022-05 현재 Linux IntelliJ 에서  flutter web 을  개발할때 GPU 렌더링이 느린 이유는 link:https://github.com/flutter/flutter/issues/96919[Github issue link]의 내용대로, snap store 에서 내려받는 google chrome 에 뭔가 이상한 문제가 있기 때문이다.

- wongue::
```
취업 준비를 할 때 많은 도움을 주셨던 멘토님이 최근 성공적으로 이직을 하시게 되어 그동안 도와주신 부분에 대한 감사를 표시할 겸,
커리어 코칭을 받기 위한 겸 점심 식사를 대접하며 어떠한 방식으로 커리어를 성장해야 하고, 임하는 태도는 어때야 하는지에 대한 많은 대화를 나누었다.

정말 신기할 정도로 환님이 반복적으로 강조하시는 부분을 중요하게 생각하시는 것을 확인하게 되었던 경험이었다.
크게 새 가지 부분을 강조해 주셨는데,

첫째로는 기술에 매몰되지 말아야 한다.
학교의 교수님들이 같은 내용을 30년 넘게 강의하실 수 있는 이유는
아무리 기술이 발전해도 결국은 이러한 지식을 가진 개발자여야 제약 없이 개발할 수 있기 때문이라고 한다.
프레임워크나 라이브러리는 생애주기가 빠르지만,
OOP, TDD, 계층 분리, 의존성 관리 등 핵심 디자인 패턴과 이를 가능하게 하는 관련 CS 지식은 사람이 생각하는 방식이 변화하지 않는 이상 꾸준히 도움이 될 지식이라는 것.

둘째로는 블로그 포스팅을 통한 자신의 PR의 중요성에 대하여 말씀해주셨다.
자신이 기술적으로 얼마나 성장했든 간에 이 성장이 가치가 있으려면 타인이 이를 인정해줄 때 가치가 생기는 것 하지만,
이에 관해 노력하는 개발자들이 그리 많지. 않다는 말씀이셨다.
남들이 잘하지 않는다는 것은, 내가 조금만 노력해도 투자 대비 더 많은 이득을 볼 수 있다는 것.
블로그 포스팅을 할 때 찾아볼 수 있는 글을 적는 것 보다는 그 횟수를 줄이더라도 고유하고 나만의 특성을 강조할 수 있는 글이여야 한다.
동시에 예상 독자들이 관심을 가질만한 주제를 선정해 적어야 한다고 말씀해주셨다.
플랫폼은 링크드인을 추쳔해주심.

마지막으로는 지속해서 성장을 하기 위해서는 오프라인 위주의 개발자 커뮤니티가 필요하지 않나 고민하고 계신다고 말씀해주셨다.
내가 많이 약한 부분이 아닐까 생각이 들었다.
같은 일을 하는 학교 동기를 찾기 힘든 상황에서 나는 어떤 식으로 커뮤니티를 구성하고 이를 확장해야 하는지에 대한 숙제를 얻게 되었다.
```

- gon: 코틀린에서의 block: T.() -> R과 block: (T) -> R차이를 알게되었다. 전자는 리시버로 묵시적전달, 후자는 파리미터로 명시적 전달이다.
그래서 람다내 코드블록에서 this와 it의 범위의차이가 있다.

- youjin: flutter 3.0이 출시되면서 업그레이드 된 점을 간단히 알 수 있었다. 
1. link:https://github.com/flutter/flutter/issues/91605[material design 3]을 Flutter 3.0과 함께 사용할 수 있게 된다. 
2. link:https://firebase.google.com/docs/flutter/setup?hl=ko&platform=ios[flutter용 firebase] firebase에서 공식적으로 flutter를 지원한다.

- yoonho: 객체간 비교에서 comparable을 구현하면 비즈니스 코드의 로직을 줄일 수 있다.
          비교하는 로직이 복잡할수록 빛을 발한다.

[[section-202205-W5]]
=== 2022년 5월 5주

- hwan: 

. `* whois.co.kr` 에 등록한 도메인을 AWS Route 53 으로 변경하기

.. Route 53 의 NS Record 에 있는 ns domain 들의 목록을 확인
.. whois.co.kr 접속 후 네임서버 정보 변경 항목에서 NS Host 이름들을 Route 53 의 정보로 변경
.. A 레코드 등록
.. 5분 정도 대기
.. `dig @ns-1264.awsdns-30.org meatgo.co.kr` 커맨드로 ns 등록 잘 되었나 확인 (ns 값은 서비스에 따라 다를 수 있음)

. AWS 에서 `*.meatgo.co.kr` 도메인 인증서를 발급하기 위해:

.. AWS Certificate Manager 페이지에 접속해 `meatgo.co.kr` 및 `*.meatgo.co.kr` 도메인의 인증서를 발급한다. 유형은 DNS Validation 으로 결정한다.
.. Pending Validation 상태의 CNAME Record 를 확인할 수 있다.
.. CNAME name, CNAME value 항목을 AWS 53 의 해당 site 의 CNAME record 로 추가한다.
.. 몇분 기다린다.
.. Issued 상태로 나오나 확인한다.
.. `dig meatgo.co.kr` 커맨드로 ns 등록 잘 되었나 확인한다.
.. 인증서 정보를 확인해 보자.
.. 단, AWS CM 에서 발급받은 인증서는 export 가 불가능하기 때문에 사실상 AWS 서비스 내에서만 쓸 수 있다. 강력한 Lock-in effect 를 노린 것 같은데... 무서운 녀석들.

- youjin: flutter에서 theme 속성(테마 속성)은 앱의 일괄되는 테마를 정할 수 있다. 기본적으로는 `theme: ThemeData(
        primarySwatch: Colors.red
      ),` 이라고 쓴다. primarySwatch는 theme 속성 덩어리기 때문에 Colors는 Accent가 붙은 키워드는 사용 할 수 없다. (예시: pinkAccent) `theme: ThemeData(
        primaryColor: Colors.pinkAccent,
      ),` Accent가 붙은 키워드를 사용하려면 단일 color 속성으로 지정해야한다. 
      다크테마도 사용할 수 있는데 휴대폰 자체에서 다크테마를 사용하면 다크테마가 자동으로 된다고 한다. 다음에 활용하면 업데이트 해봐야겠다. 
- yoonho: 예상치 못한 상황에서 응급(?)환자를 조우했을 때 필요한 대처법에 대해서 알아두는 것이 필요하다고 느꼈다.

- gon : spring data mongo를 활용해 mongodb에 다하여 알게된 한주 였습니다. +
  sql과 다르게 Document를 쌓는 방식으로 데이터를 관리하는데 덕분에 데이터를 쌓는데에 있어서는 굉장히 빠르다. + 
  더불어 데이터를 사용하기위해 정제해야하는데 aggregation method를 이용하여 가공하는 쿼리도 제공한다. 단점으론 연관관계가 없어 cascade가 지원이 안된다. 또한 메모리를 더 많이 사용하는것으로 알고있다.
  
- wongue: https://arxiv.org/abs/2205.11916 GPT-3 모듈에 질문을 던질때, “Let’s think step by step” 이라는 구문을 넣으면 정확도가 올라간다는 논문을 읽었다.
약한 의식이 있다는 소리일까...? +
flutter에서 다루는 state가 react와 어떻게 다른지 체감하는 한주였습니다. +

[[section-202206]]
== 2022년 6월

[[section-202206-W1]]
=== 2022년 6월 1주

- hwan: BLoC 에서 API Call -> API success / API fail 동작에 동일한 화면 연출이 필요해서 이를 패턴화 하고 싶었다. 그런데 이를 다음처럼 구현할 경우 컴파일 에러가 발생한다.

[source,dart]
----
// BLoC Event
abstract class ApiCallBlocMessage {}
class ApiCallStartMessage extends ApiCallBlocMessage {}

// BLoC State
abstract class ApiCallBlocState {}
class ApiCallStartedState extends ApiCallBlocState {}

// BLoC template
abstract class ApiCallBlocTemplate<M extends ApiCallBlocMessage, S extends ApiCallBlocState> extends Bloc<M, S> {
  ApiCallBlocTemplate(super.initialState) {
    on<ApiCallStartMessage>((message, emit) => emit(ApiCallStartedState()));
    // ^^^^^^^^^^^^^^^^^^^^                         ^^^^^^^^^^^^^^^^^^^
    // compile error:
    // (1)                                          (2)
    // 
    // (1) 'ApiCallStartMessage' doesn't conform to the bound 'M' of the type parameter 'E'.
    // (2) The argument type 'ApiCallStartedState' can't be assigned to the parameter type 'S'.
  }
}
----
이유는:

(1): `ApiCallBlocTemplate` 의 타입 `M` 은 공변(Covariance) 타입이기 때문에 `on` 메소드 호출 시점에 구체 타입을 알 수 없다.

(2): `on` 메소드의 `EventHandler` 가 `State` 타입의 공변(Covariance)을 허용하지 않기 때문에, `ApiCallBlocTemplate` 의 `State` 는 고정 타입이어야 한다. 하지만 이로 인해 `ApiCallBlocTemplate` 의 사용 범위가 넓어질 수록 `ApiCallBlocState` 단일 타입 참조가 넓게 퍼지게 된다.

즉, `ApiCallBlocTemplate` 의 하위 구현체에서, `on...(message -> state)` 의 state 를 실수해도 컴파일러가 문제를 인식할 수 없다.

- wongue: OOP 관련 학습이  필요하다 생각되어, http://www.kyobobook.co.kr/product/detailViewKor.laf?mallGb=KOR&ejkGb=KOR&barcode=9788998139940[스프링 입문을 위한 자바 객체 지향의 원리와 이해] 를 구매해 읽기 시작했습니다. +
js와 JVM 메모리 구조의 큰 차이점 중 하나는, jS에는 callstack과 heap영역만 존재하지만, JVM의 메모리 구조에서는 static영역이라는 공간에 정보들을 등록, 관리하면서 OOP라는 개념을 구현 했다는 점인것을 알게되었습니다. +
+ 추가로 조사해보니 dart의 메모리 구조는 JVM의 구조와는 다르게, isolate라는 각각의 메모리 영역안에 heap이 존재하고, heap 안에 static 메모리 공간이 존재하는 차이점이 있는것 같습니다. https://images3.programmersought.com/536/bd/bd8786390503f97155e4cb60e5b7d338.JPEG[관련 이미지]

- gon:
[source, kotlin]
----
fun main() = runBlocking<Unit> {
    try {
        val sum = failedConcurrentSum()
        println("출력이 안되어야 함 result : $sum")
    } catch(e: ArithmeticException) {
        println("main 함수 캐치")
    }
}

suspend fun failedConcurrentSum(): Int = coroutineScope {
    val one = async<Int> {
        try {
            delay(Long.MAX_VALUE)
            42
        } finally {
            println("첫번째 async finally")
        }
    }
    val two = async<Int> {
        println("Exception 발생")
        throw ArithmeticException()
    }
    one.await() + two.await()
}
----

실행결과


----
Exception 발생
첫번째 async finally
main 함수 캐치
----

코루틴은 여러 비동기 함수가 같이 실행될때 만약 하나라도 에러난다면 실행한 비동기 함수전부에서 예외를 발생한다

yoonho: '만들면서 배우는 클린아키텍처' 책을 마저 읽으면서 은총알은 존재하지 않는다는 문구가 기억에 남았다. +
상황에 맞는 판단을 할 수 있어야한다.

youjin: 플러터 기본 앱 레이아웃 만드는법(Scaffold)을 정리해보았다.

- Scaffold 위젯 +
[source,dart]
----
    MaterialApp(
    home: Scaffold(
            appBar: AppBar( title: Text('앱제목') ), 
            body: Text('앱본문'), 
            bottomNavigationBar: BottomAppBar( child: Text('앱하단') )
        )
    ); 
----

    - :heavy_exclamation_mark: body 속성은 반드시 있어야한다. +
    
- Row, Column 위젯 +
[source,dart]
----
    Row(
      mainAxisAlignment: MainAxisAlignment.spaceEvenly,
      children: [ Icon(Icons.star), Icon(Icons.star)]
    );
----

- mainAxisAlignment +
  * .spaceEvenly 모든 여백 동일 +
  * .spaceBetween 좌우 끝에 우선 배치 +
  * .spaceAround는 모든 여백 동일인데 좌우 마지막 여백은 절반만큼 +
  * .start는 시작 부분에 다 모여 +
  * .end는 끝 부분에 다 모여 +
  * .center 중간에 다 모여 +
       
[[section-202206-W2]]
=== 2022년 6월 2주

- wongue: OOP 관련 공부를 진행하던 중에, 멀티스레딩 관련한 내용에서 말하는 쓰레드의 의미가 내가 알고있는 CPU의 N코어 M'스레드' 를 말할때의 스레드와 다르다는 느낌을 받았다. +
관련해 구글링해보니, 쓰레드는 물리적, 논리적 스레드로 라는 두 종류로 분류가 가능하고, 물리적 스레드는 병렬성을 담당하고, 논리적 스레드는 프로그렘이 실행될 때의 동시성을 담당한다고 한다. + 
nodejs나 dart가 싱글스레드로 동작한다는건 서버를 올려 동작시킬때, 1코어만 갈군다는 뜻이 아니라 논리적 스레드가 1개로 구성되었다는 뜻인거 같다.. https://imgur.com/a/4vkYdo7[참고이미지]

- hwan: letsencrypt 로 wildcard 인증서 '자동'발급받기
+
*주의: manual 방식으로는 자동 발급 불가능. AWS route 53 을 이용한다고 가정한다.*

. AWS cli 설치
. letsencrypt certbot 및 dns plugin 설치 (https://certbot.eff.org/instructions)
. `sudo su` 로 super user 권한 획득
. `AWS_ACCESS_KEY_ID` 및 `AWS_SECRET_ACCESS_KEY` 환경변수 설정 후 아래 명령 실행
  (보안 문제로 여러개의 aws cli profile 을 쓸 경우, `AWS_PROFILE` 환경변수를 설정하는 편이 좋음)
+
[source,shell]
----
certbot certonly \
  --dns-route53 \
  -d "meatgo.co.kr" \
  -d "*.meatgo.co.kr" \
  --agree-tos \
  --manual-public-ip-logging-ok \
  --rsa-key-size 4096
----
. `certbot renew --dry-run` 로 자동 재시작 여부를 확인해 본다.
. crontab 에 `certbot renew` 를 적절한 기간동안 자동 재시작하도록 등록해 둔다. (https://crontab.guru/ 같은 사이트 이용하면 cron 쉽게 확인 가능)
+
그 외에 https://eff-certbot.readthedocs.io/en/stable/using.html#dns-plugins 에 다른 플러그인들도 있음
. `*.meatgo.co.kr` 같은 인증서로는 `api.meatgo.co.kr` 호스트명은 인증 가능하지만, `openbeta.api.meatgo.co.kr` 같은 호스트이름은 인증할 수 없다(https://www.rfc-editor.org/rfc/rfc6125#page-27).

- yoonho: +
1. PR을 분리하면서 여러개의 커밋을 cherrypick 해야했다. +
git cherry-pick commitnumber^..commitnumber 를 이용해 여러개의 커밋을 한번에 cherrypick 할 수 있다. +
^ 는 시작 커밋 포함 여부를 표현한다. +
2. 아침에 날씨가 좋아서 신논현에서 걸어왔다. +
때로는 주변을 돌아보며 환기를 하는 것도 좋은 것 같다.

- gon: 코루틴이 활동중 취소가 잘되려면 취소에 협조적으로 짜여야한다. 이 키워드를 yield가 담당한다
- youjini: 깃헙에서 . 를 누르면 리소스를 vscode로 바로 확인가능하다.


[[section-202206-W3]]
=== 2022년 6월 3주

- gon : 자바의 최상위 시간타입인 Instant의 경우 기준이 UTC이다 그래서 만약 KST를 zoneoffest없이 그대로 변환하면 KST가 UTC기준이 되기 때문에 주의하여야한다. 타임존에 관한정보는 ZoneDateTiem으로 표현할수 있다.

- hwan: lwil: flyway 를 이용한 database schema 형상관리
https://www.popit.kr/%EB%82%98%EB%A7%8C-%EB%AA%A8%EB%A5%B4%EA%B3%A0-%EC%9E%88%EB%8D%98-flyway-db-%EB%A7%88%EC%9D%B4%EA%B7%B8%EB%A0%88%EC%9D%B4%EC%85%98-tool/

- youjin: 
. 챗봇이용시 꼭 알아야 하는 단어
+
[source, shell]
----
	// Intent : 목적 , 사용자가 어떤 의도로 챗봇에 요청한 것인지를 판단한다 
	
	오늘 날씨 어때? 내일 날씨 어때? 어제는 날씨 어땠어? :: 날씨정보
	넌 코끼리 좋아해 ? 호랑이 좋아해 ? :: 선호동물 정보 
	
	// Entity : 실체 (변수) , 사용자의 의도중 실체가 되는 변하는 경우

	오늘, 내일, 어제 :: date
	코끼리, 호랑이 :: animals

	// Context : 문맥 , 대화의 앞뒤 흐름

	오늘날씨 어때? ~~~ 그럼  내일은? :: 내일 (날씨)는 (어때)? 처럼 이어서 요청할 때
----

. `GestureDetector()` -> 여러 세밀한 클릭기능(확대, 축소 drag 등)들을 제공하지만, 잉크가 퍼지듯한 애니메이션효과(리플애니메이션 Ripple Animation)를 제공하지 않고 있다.
    대신, `InkWell()` -> 기본 탭들은 제공하지만. `GestureDetector`보다는 세밀하지 않고, 그 수가 적고 간단하지만, 터치시 효과주는 리플 애니메이션효과를 제공한다.
    
. 사용자 프로필을 원으로 나타내고 싶을 때에는 https://api.flutter.dev/flutter/material/CircleAvatar-class.html[CircleAvatar class] 를 활용하면 더 깔끔하게 구현가능하다.


- yoonho: 출근시 행단보도쪽에서 바로 올라오는 것보다는 미리 골목에 들어와서 올라오는 것이 덜 힘들수도 있다.

- wongue: flutter 의 route를 사용하는것과, Navigator.push(), .pop()을 사용하는건 완전히 같은 동작이라는것을 알게 되었습니다. +
  웹 url 에 따른 라우팅을 구현하기 위해서 Navigator ver.2 라는것도 출시되었다고 하는데, 향후 웹앱을 개발할 시점에는 반드시 숙지해야할 기술이라 생각이 들었습니다.

[[section-202206-W4]]
=== 2022년 6월 4주

- hwan: AWS 의 VPC 자동생성 기능.. 잘못하면 삽질만 할 가능성이 커짐. 하기전에 문서 잘 읽어보자...
+
.일반적인 service network 구성도
----
       Internet
          |
+-------------------- [ VPC ] ---------------------+
|         |                                        |
| +-- subnet-public --+     +-- subnet-private --+ |
| |       |           |     |                    | |
| |     GATEWAY <------------->                  | |
| |                   |     |                    | |
| +-------------------+     +--------------------+ |
|                                                  |
+--------------------------------------------------+
----
+
위 구조의 Gateway(Bastion) 설정 하는데 삽질 3시간, 결국 손으로 30분만에 구축 성공...
+
VPC 자동생성 기능을 쓰면:
+
. VPC
. Subnet >
. Routing Table (public: public subnet 및 internet gateway, private: private subnet 에 연결) >
. EC2 에 사용할 Network Interface 생성 및 public subnet 에 소속 
. ACL 및 Security rule 설정

+
정도를 다 해주긴 하는데 정작 EC2 NAT instance 설정을 안 해줘서 결국 저 메뉴들 다 들어가서 확인하는 수고는 여전히 필요하다. 처음 이 기능을 봤을땐 이거 하나만 누르고 ec2 인스턴스 만든 뒤, Network Interface 만 붙여주면 끝날 줄 알았는데 현실은 그렇지 않았다. ㅜㅜ

- youjin: AnimatedBuilder() -> 내가 원하는 위젯만 감싸서 애니메이션을 넣으려면, animation 레퍼런스를 넣어서 값을 조작해주는 부분의 위젯을 AnimatedBuilder로 감싸면 된다.

- gon : kotlin의 suspend 함수는 default 파라미터로 지정할 수 없다.

- wongue: Flutter I/O Extended Korea 2022 발표중 클린 아키택처를 flutter package 에서 구현하는 방법을 알게되었다. +
https://www.notion.so/flutter-5f6dd66df7e245079026f6e07d7c7258[참고 링크]

[[section-202207]]
== 2022년 7월

[[section-202207-W1]]
=== 2022년 7월 1주

- wongue: flutter 의 material 에서 제공해주는 MaterialStateColor와 FocusNode를 arg로 받는 Inkwell을 이용해 위젯을 구현하려고 시도했지만, material 에서 default로 세팅된 값이 너무 많아서 의도한 디자인 대로 위젯을 동작사키기가 힘든 단점이 있다. +
가능하면 materialState를 사용하는것 보다는 flutter core 에서 제공해주는 focus 위젯등을 사용해 직접 stateful 하게 위젯을 구현하는것이 더 좋은 방향인것 같다. + 
직접 위젯의 상호작용을 구현해놓으면, 타 패키지의 의존성을 줄임 + 의도한 바 대로 위젯의 디자인을 구현하기 쉬움 + 차후 side effect 가 날 가능성이 적어지는 정도의 장점을 가진다. +
물론 차후 상호작용을 담당하는 부분에 대한 코드가 위젯별로 파편화되어있어 유 보수가 진행되야 할 경우 비용이 올라간다는 단점또한 같이 생기게 되지만, front의 코드 특성상 재작성될 확률이 크다 판단하였다.

- youjin: https://github.com/features/copilot[github copilot]이 진짜 나왔다. github copilot 은 코딩할 때 자동완성 스타일 제안을 제공하는 AI 페어 프로그래머이다. + 
	유료라서 당장 사용하진 못하지만, vscode, intellJ, Android Studio 등 몇몇 IDE 환경에서 Extension 과 Plugin 형태로 제공해준다. +
	설치 후 도구 > github copilot > login to github 을 하면 승인요청을 할 수 있다. 특히 Python, JavaScript, TypeScript, Ruby, Go, C# 및 C++ 에서 잘 작동된다고 한다. +
	클래스를 생성하거나, 함수를 작성하려고 이름을 선언할 때, 코드의 컨텍스트와 스타일이 일치되는 코드를 회색라인으로 자동생성한다. 혹은 자동생성코드를 원할때, 주석으로 아래와 같이 입력을 통해 실행시킬 수 있다. 
+
[source, java]
----
	// find all images without alternate text
	// and give them a red border
	void process () {
		... // github copilot 이 주석명령을 알아듣고 알아서 코드를 생성시킴
	}
----
+ 
내가 코드를 직접 짜지 않고 github copilot 을 사용하여 코드를 자동생성하더라도, 코드퀄리티나 보안은 `개인의 책임` 에 있다고 한다. 즉, 앞으로 코드를 작성할 때는 명확한 변수명 선언(클린코드)과 가능한 작은 단위의 함수 생성(클린아키텍쳐)의 중요성이 더 키질 것으로 생각된다. dart 도 지원이 된다면, 한번 사용해보고 싶다 !
