= 2023년 3분기 07월-09월 LWIL(Last week I learnt) 모음
// Metadata:
:description: Last Week I Learnt
:keywords: study, til, lwil
// Settings:
:doctype: book
:toc: left
:toclevels: 4
:sectlinks:
:icons: font

[[section-202307]]
== 2023년 7월

[[section-202307-W1]]
=== 2023년 7월 1주
- hwan: JPA 에서 Shared PK 를 `@Id` 처럼 쓰려면 `@IdClass` 를 쓸 수 있다. `@EmbeddedId` 도 쓰는데 각각 장단점이 있다. 물리적인 DB Table 관점에서는 `@IdClass` 가 좀 더 낫고, 의미론적인 관점에서는 `@EmbeddedId` 가 좀 더 낫다.

- youjin: dart 에서 interface class 에 메소드를 적으려면, 무조건 body block 을 작성해야한다.
+
[source, dart]
----
  interface class FlyBehavior {
    // void fly();
    void fly(){ }
  }
----
+
옵저버 패턴을 활용할 때, ‘주인공’이 누구냐에 따라 이기적인 요인이 작용된다.
즉, 주체(Subject)가 있고 관찰자(Observer)가 있을 때, 
주인공이 ‘주체(Subject)’라면, 모든 정보를 일괄적으로 모든 관찰자에게 PUSH 하고 싶어한다. (이기적 요인)
주인공이 ‘관찰자(Observer)’라면, 내가 받고 싶은 정보만 주체에서 꺼내오는 PULL 하고 싶어한다. (이기적 요인)
+
하지만, 주로 코드를 작성할 때, 옵저버패턴은 주체는 하나이고 관찰자가 N개인 상황이기 때문에, 관찰자의 편의로 PULL 받아오는 패턴이 일반적으로 좋은 패턴이라고 칭한다.

- wongue: Dart 의 Recode 의 extention 중에는 (Future<T1>, ... , Future<T10) 으로만 이루어진 Recode 에 한해 wait method 를 제공해준다. +
++ window 의 블루스크린이 'blue' 인 이유는 특별한 의도가 담겨있다기 보단 그 당시 작업자의 펌웨어 화면색을 그대로 따라갔다고 한다. +
출처: https://www.youtube.com/watch?v=KgqJJECQQH0

- gon: mysql에서 레코드 하나당 관리하는 저장 용량의 크기가  65,535 바이트 라고 한다.
그래서 varchar 타입으로 10000의 크기로 7개를 만들면 에러가 발생한다

[[section-202307-W2]]
=== 2023년 7월 2주
- hwan: spring-data 이용시 두 개 이상의 `DataSource` 및 `TransactionManager` 를 쓸 경우, `@Transactional` 에 `transactionManager` 속성을 다음과 같이 지정해 주지 않으면 오류가 발생한다. +
+
[source, kotlin]
----
@Transactional(transactionManager = "someTransactionManager")
----
+
다만 매번 Transaction manager 를 지정하는 것이 번거로울 수 있고 또한 Infrastructure Service Logic 이 특정 DataSource 를 대상으로만 동작해야 한다는 전제가 깔려 있는 경우가 있을 때도 많다. 이런 경우에는, 기본 TransactionManager 를 지정해 줄 수 있다. +
+
[source, kotlin]
----
@Configuration
internal class DefaultTransactionManager(
    private val applicationContext: ApplicationContext
): TransactionManagementConfigurer {
    @Bean
    override fun annotationDrivenTransactionManager(): TransactionManager =
        applicationContext.getBean(SomeTransactionManager.NAME) as TransactionManager
}
----
- youjin: 저번주에 확인했었던 `interface class` 의 경우, 바디에 block 을 사용하고 싶지 않다면, `abstract interface class` 라고 작성하면 된다.

[[section-202307-W3]]
=== 2023년 7월 3주
- hwan: 대한민국 공공 API 를 신청하면 `serviceKey` 라는 API Key 를 받는다. 문제는, 이 Key 가 URL Safe 하지 않다는 것이다. 이 때문에, 전달받은 serviceKey 를 제대로 쓰려면 반드시 다음 코드처럼 URL Safe encode 해 줘야 한다.
+
[source, kotlin]
----
import java.net.UrlEncoder

fun String.urlEncode() = URLEncoder.encode(this, StandardCharsets.UTF_8.toString())
----

- gon: 리눅스에서는 어플리케이션에서 접근 할 수 있는 경로를 제공하기위해 시스템 콜의 경로를 파일디스크립션이라는 형태로 추상화를 제공한다.
그래서 tcp/ip 같은 네트워크도 보면 fd형태로 접속정보를 관리한다.

- wongue: Computer Vison 에서는, 이미지의 Affine 변환과 perspective 변환을 용이하게 수행하기 위해, 이미지 소스의 차원에 + w 차원을 더한, Homogeneous coordinate 를 사용한다.

[[section-202307-W4]]
=== 2023년 7월 4주
- hwan: AWS S3 의 특정 bucket 을 공공 접근하게 설정하는 법:
+
. 환경 설정의 'Block _all_ public access' 체크를 해제한다.
+
. Permissions 의 Bucket Policy 에 다음 설정을 추가한다.
+
[source, javascript]
----
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "AddPerm",
      "Effect": "Allow",
      "Principal": "*",
      "Action": "s3:GetObject",
      "Resource": "arn:aws:s3:::<<MY_BUCKECT_NAME>>/*"
    }
  ]
}
----
+
AWS 가 이런 방법을 문서로 딱히 제공하지 않는 이유: S3 에 접근하는 트래픽마다 비용이 발생하기 때문에, 접근 횟수가 비정상적으로 많거나 큰 파일을 누구나 접근하게 허용할 경우 네트워크 사용 비용이 기하급수적으로 늘어나기 때문. 따라서 Bucket 을 public open 할 때는, CDN 설정을 추가로 고려해 보는 편이 좋다. AWS 의 CloudFront, Azure CDN, Akamai, Cloudflare 같은 서비스가 대표적인 CDN 서비스라고 할 수 있다.

gon: 이번 재시도 관련 함수를 짜면서 배운것이 있다.
제너럴한 인터페이스나 기능을 만들땐 최대한 기능이 단순하며 보편적이어야한다 
필요한 조건은 함수로 받아서 작업해서 함수를 호출하는 쪽에서 조건을 제어하게 해주자

wongue: 우리가 '밝기'를 인식하는 방법은 소리의 '크기'를 인식하는 방법과 유사하다. +
Logscale 로 그 세기를 인식하는데, 간단히 설명하면, 밝기(조도)가 1lx에서 10lx 까지 증가한 것과, 10lx 에서 100lx 까지 증가 했을때, 우리는 밝기가 1, 2, 3 처럼 선형적으로 증가했다 인식한다. +
이 특징은 광학 디스플레이의 설계와 사용에서도 충분히 반영되어야만 사람은 화상에서 자연스러운 밝기를 인식할 수 있는데,
소프트웨어 엔지니어로서 주의해야할 점은 이미지를 RGB 색공간에서 다룬다고 가정할때, 원 이미지의 밝기를 0~255 의 단계로 인코딩 할 시, 각 단계가 선형적인 간격을 가지게 하는것이 아니라 로그 스케일의 간격을 가지도록 저장해야만 우리 눈이 상대적은 둔감한 밝은 영역의 정보에 무의미한 투자를 막을 수 있다.

[[section-202307-W5]]
=== 2023년 7월 5주

- gon: 인코딩중 EUC-KR 은 한글을 2byte로 처리한다 많이 쓰는 UTF-8은 한글을 보통 3바이트로 처리한다.

- youjin: EGL 을 통해서 window manager 과 통신할 수 있다. EGL 에서 얻어올 수 있는 디스플레이의 갯수는 평균적으로 1개이다. 

- wongue: Mac OS 에는 EGL 의 구현체가 존재하지 않아서 glfw 등을 사용해야만 한다.

- hwan: 2023년 7월 마지막 주말을 뜨겁게 달궜던 신비의 물질 lk-99 에 관해 조사하며 배운 지식. 고교 물리학 시간에 배우는 내용이라고 한다. 그랬던것 같기도 하고 아닌 것 같기도 하고.
+
* 강자성체(ferromagnetism): 자석에 강하게 반응하는 물질. 대표 응용사례로는 하드 디스크, 테이프 레코더 등이 있다.
* 상자성체(paramagnetism) : 특정한 조건 내에서만 자석에 반응하는 물질. 대표 응용사례로는 MRI 등이 있다.
* 반자성체(diamagnetism)  : 자석을 밀어내는 물질. 초전도체의 여러 응용 사례가 반자성을 이용한 것으로, 우주 엘리베이터, 레일건 등에 사용할 수 있다.
+
실험 결과로 증명 되기만 하면 우리가 어릴 때 상상했던, 과학이 극도로 발달한 미래의 모습이 어느 정도 사실로 다가온다니 결과가 좋게 나왔으면 하는 바람이다.

- wongue: openGL 은 스래드 세이프하지 않다. +
멀티스레드에서 openGL 함수를 호출하는순간 어플리케이션이 죽어버린다고 한다. +
이유는 gl 이 만들어질 시절, 멀티스레드 라는 개념이 모호해서...

[[section-202308-W2]]
=== 2023년 8월 2주
- hwan: Kotlin 의 `data class` 에는 `copy` 라는 복사 생성자가 있다. 여기서 주의할 점은 이 복사 생성자는 *shallow copy*, 즉 값이 아니라 참조만을 복사한다는 것이다. 이 때문에 복사로 새로운 객체를 만들었다고 해서 참조형 자료를 수정하면 원본 자료도 함께 수정되는 일이 벌어질 수 있으니 조심해야 한다. 혼란을 피하려면 data class 에는 가급적 immutable value 들만 담는 편이 좋다.

- gon: 만약 여러 도메인을 수정해야할 일이 있다면 어떤 방식으로 레이어를 구분하여 아키텍쳐를 가져가야할까?
최범균님의 ddd start 책에서 다음과 같은 글이 있어 참고하면 좋을것 같아 가져왔습니다
```
특정 기능이 응용 서비스인지 도메인 서비스인지 감을 잡기 어려울 때는 해당 로직이 애그리거트의 상태를 변경하거나 애그리거트의 상태 값을 계산하는지 검사해 보면 된다. 
예를 들어, 계좌 이체 로직은 계좌 애그리거트의 상태를 변경한다. 
결제 금액 로직은 주문 애그리거트의의 주문 금액을 계산한다. 
이 두로직은 각각 애그리거트를 변경하고 애그리거트의 값을 계산하는 도메인 로직이다. 도메인 로직이면서 한 애그리거트에 넣기 적합하지 않으므로 이 두 로직은 도메인 서비스로 구현하게 된다.
```

- wongue: 원인 미상의 이유로 dart analysis server 가 재귀호출을 하며 뻗어버리는 현상이 발생 할 때가 있다. +
이때 ~/.dartserver dir 전체를 날려버리고 인텔리제이를 재시작하면 해결할 수 있다.

[[section-202308-W3]]
=== 2023년 8월 3주
- hwan: Spring Boot 의 Test 실행속도를 향상시키려면 test slice 를 구성하는 편이 좋다. 그리고 JPA Repository 로직만을 테스트하는 `@DataJpaTest` 어노테이션은 데이터베이스 계층을 쓸 수 있는 bean 들만 로드할 수 있는 고마운 기능이다. 그런데, 다음과 같은 설정에서 테스트를 실행시키면:
+
.실제 로직:
[source, kotlin]
----
package com.bondaero.infra.jpa

@Repository
internal interface MyEntityJpaDao : JpaRepository<MyEntity, UUID>
----
+
.테스트:
[source, kotlin]
----
package testcase.medium

@DataJpaTest
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)    // 환경설정에서 지정한 DB 에서 테스트 실행
@MediumTest
internal class JpaMediumTestBase

internal class MyEntityJpaDaoSpec(
    @Autowired
    private val sut: MyEntityJpaDao
): JpaMediumTestBase()
----
+
이런 오류가 난다:
+
[source, shell]
----
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sut' defined in file [/home/hwan/git/myproject/build/classes/kotlin/test/testcase/medium/MyEntityJpaDaoSpec.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.bondaero.infra.jpa.MyEntityJpaDao' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
----
+
왜냐하면 `JpaRepository` 인터페이스를 실제로 실행할 구현체 - 이 사례에서는 `org.springframework.data.jpa.repository.support.SimpleJpaRepository` - 를 bean 으로 만들 방법을 제공하지 않았기 때문이다.
+
따라서 이 문제는 다음과 같이 `@EnableJpaRepositories` 어노테이션을 붙여줘야 해결할 수 있다.
+
.해결방법:
[source, kotlin]
----
@DataJpaTest
@EnableJpaRepositories    // JpaRepository 들을 전부 Proxy 로 생성후 Bean 으로 등록합니다.
@EntityScan               // JPA EntityManager 에 @Entity 들을 'Managed Type' 으로 등록합니다. 
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)    // 환경설정에서 지정한 DB 에서 테스트 실행
@MediumTest
internal class JpaMediumTestBase
----
+
가급적 `@DataJpaTest` 는 `@EnableJpaRepositories` 와, `@EntityScan` 를 달고 다닌다고 생각하는 편이 좋겠다.
+
- wongue: C 에서 List<String> 을 표현하는 방법. +
List<type>은 const type* 로 표현할 수 있다. type 이 뭔지 알고있으면, 첫번째 메모리주소 이후 그 사이즈만큼 뒤로가며 읽을수 있기 때문. +
따라서, String => const char* 로 표현될 수 있고, List<String> => String* 으로 표현이 가능하기때문에, +
List<String> => List<const char*> => const char* const* 가 되는것. 

- jaewon: 안녕하세요, 김재원입니다. 앞으로 잘 부탁드리겠습니다! 🙏
+
이번에 본대로 클라이언트 프로젝트를 통해 Monorepo를 처음 경험해 보는 건데, Monorepo 자체도 신기했지만 Melos라는 도구도 꽤 생소했습니다. 빨리 익숙해져 봐야겠다는 생각이 듭니다.
+
요즘 <The Bear>라는 드라마를 보고 있는데, 동네 햄버거집을 물려받은 젊은 미쉐린 스타 쉐프가 우여곡절을 겪으며 식당을 지켜내는 내용입니다. 주방 특유의 군기나 텃세, 스트레스 같은 걸 하이퍼 리얼리즘 수준으로 담아내서 흥미롭게 보고 있어요.

[[section-202308-W4]]
=== 2023년 8월 4주
- hwan: 최현우 마술쇼를 보고 왔다. 마술에 사용하는 트릭을 미스디렉션(misdirection) 이라고 하는데, 관객의 주의를 다른 곳으로 이끄는 일종의 속임수다. 물론 관객은 마술사의 트릭을 간파하려 눈을 부릅뜨고 보지만, 마술사도 당연히 그에 대한 대비가 되어 있다. 그런데 마술의 근본원리가 단순한 속임수 싸움이 아니라 미스디렉션이라는 용어까지 써 가며 설명하는 이유가 있다. 바로, 관객이 속는다는 사실도 눈치채지 못하도록 주의를 돌려야 하는데 여기에는 고도의 심리학, 광학, 시지각학, 수학, 물리학 원리가 필요하다고 한다. 즉, 정말 훌륭한 마술사는 머리가 좋을 수 밖에 없다는 사실. '알고도 당한다' 는 말이 딱 어울린다고 할 수 밖에 없다. 물론, 그 당한다는 것이 시청각적 즐거움이기에 사람들은 마술에 열광하는 것일 테고.

- wongue: dart 는 protected 를 keyword 가 아닌 annotation 으로 구현한다. +
참고: https://github.com/dart-lang/sdk/issues/25841

- gon: 샤딩과 파티셔닝(볼때마다 헷갈려서 한번 더 정리하여봅니다)

샤딩(Sharding):
샤딩은 데이터를 분산하여 여러 서버 또는 머신에 저장하는 방식입니다. 각 서버는 자신의 파티션(데이터 세트의 부분)만을 처리하며, 데이터를 전체 시스템에 걸쳐 분산시켜 부하를 분산합니다.
주로 대규모 분산 데이터베이스 시스템에서 사용되며, 수평적인 방식으로 데이터를 분할합니다. 즉, 레코드 또는 행 단위로 데이터를 나누어 다른 서버에 저장합니다

파티셔닝(Partitioning):
파티셔닝은 데이터베이스 테이블을 여러 파티션(데이터 세트의 부분)으로 분할하는 방식입니다. 하나의 테이블을 여러 개의 논리적인 논리적인 섹션으로 나누어 데이터를 분산시킵니다.
파티셔닝은 데이터를 저장하는 방법에 초점을 두고 있으며, 주로 데이터베이스 내부적으로 사용됩니다. 파티셔닝은 데이터를 논리적인 그룹으로 분할하여 해당 그룹 내에서만 쿼리나 조작을 수행할 수 있도록 합니다.
파티셔닝은 주로 관계형 데이터베이스 시스템에서 사용되며, 수직적인 방식과 수평적인 방식 모두 가능합니다. 수직적 파티셔닝은 열 단위로 데이터를 나누는 것이고, 수평적 파티셔닝은 행 단위로 데이터를 나누는 것입니다.

- jaewon: IoC(Inversion Of Control)의 구현 방법인 Service Locator와 DI에 대해 학습했습니다.
+
Service Locator::
필요로 하는 객체들을 (Service Locator에서) “직접 찾거나 생성하는” 방식
+
Service Locator는 전역적으로 사용할 서비스들을 제공할 책임을 갖는 객체이자, 해당 서비스들에 접근할 수 있게 하는 중개자 역할을 한다. 모든 의존성을 한곳에서 관리할 수 있어 편리할 것 같지만, 의존 객체에 문제가 생기면 Service Locator에도 그 문제의 영향이 미칠 수 있다는 치명적인 단점이 있다.
+
DI (Dependency Injection)::
필요로 하는 객체들을 직접 찾거나 생성하지 않고, “외부에서 넣어주는” 방식
+
_(‘매개변수를 갖는 생성자’와 같이)_ 사용할 서비스들을 외부에서 넣어줌으로써 해당 서비스들과의 의존 관계를 설정하게 되며, 이러한 방식으로 DI Container를 구성하면 Service Locator의 역할을 대신할 수 있다.

[[section-202308-W5]]
=== 2023년 8월 5주
- hwan: Spring 에서의 `@Async` 와 `@Scheduled` 에 대한 오해와 진실 (link:https://docs.spring.io/spring-framework/reference/integration/scheduling.html#scheduling-annotation-support-async[공식 문서])
+
`@Async` 에는 argument 를 붙일 수 있고 `@Scheduled` 에는 argument 를 붙일 수 없다. 그렇다면 다음 사례에서는 어떤 일이 일어날까?
+
[source, kotlin]
----
@Async
@Scheduled(cron = "0/60 * * * * *") // 매분마다 실행
fun onTriggered(myBean: MyBean) {
}
----
+
.실행 결과:
[source, kotlin]
----
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'idleTimeLargeBatchScheduler' defined in file [/home/hwan/myproject/build/classes/kotlin/main/com/bondaero/scheduler/MyScheduler.class]: Initialization of bean failed; nested exception is java.lang.IllegalStateException: Encountered invalid @Scheduled method 'onTriggered': Only no-arg methods may be annotated with @Scheduled
----
+
안된다. `@Scheduled` 의 제한 때문이다. Proxy 생성 규칙을 생각해 본다면... `@Async` 를 `@Scheduled` 로 감싸건 혹은 반대가 됐건 아무튼 `@Scheduled` 를 해석하는 순간 parameter 를 가진 method 는 불가능하다는 예외가 발생할 것이다.
+
그렇다면 다음으로 드는 의문은, '그렇다면 공식 문서에는 딱히 없지만 `@Scheduled` 와 `@Async` 를 같이 쓰는건 문제가 없나?' 일 것이다. 
+
[source, kotlin]
----
@Async
@Scheduled(cron = "0/60 * * * * *") // 매분마다 실행
fun onTriggered() {
    log.info("Job start...")
    log.info("Job finished")
}
----
+
.실행 결과:
[source, shell]
----
2022-12-31 00:00:00.235 INFO  1563449 [       task-3805] c.b.h.a.s.MyScheduler   : Job start...
2022-12-31 00:00:00.243 INFO  1563449 [       task-3805] c.b.h.a.s.MyScheduler   : Job finished
2022-12-31 00:01:00.001 INFO  1563449 [       task-3806] c.b.h.a.s.MyScheduler   : Job start...
2022-12-31 00:01:00.007 INFO  1563449 [       task-3806] c.b.h.a.s.MyScheduler   : Job finished
2022-12-31 00:02:00.000 INFO  1563449 [       task-3807] c.b.h.a.s.MyScheduler   : Job start...
2022-12-31 00:02:00.006 INFO  1563449 [       task-3807] c.b.h.a.s.MyScheduler   : Job finished
2022-12-31 00:03:00.001 INFO  1563449 [       task-3808] c.b.h.a.s.MyScheduler   : Job start...
2022-12-31 00:03:00.006 INFO  1563449 [       task-3808] c.b.h.a.s.MyScheduler   : Job finished
2022-12-31 00:04:00.000 INFO  1563449 [       task-3809] c.b.h.a.s.MyScheduler   : Job start...
2022-12-31 00:04:00.007 INFO  1563449 [       task-3809] c.b.h.a.s.MyScheduler   : Job finished
2022-12-31 00:05:00.000 INFO  1563449 [       task-3810] c.b.h.a.s.MyScheduler   : Job start...
2022-12-31 00:05:00.007 INFO  1563449 [       task-3810] c.b.h.a.s.MyScheduler   : Job finished
2022-12-31 00:06:00.001 INFO  1563449 [       task-3811] c.b.h.a.s.MyScheduler   : Job start...
2022-12-31 00:06:00.006 INFO  1563449 [       task-3811] c.b.h.a.s.MyScheduler   : Job finished
2022-12-31 00:07:00.000 INFO  1563449 [       task-3812] c.b.h.a.s.MyScheduler   : Job start...
2022-12-31 00:07:00.006 INFO  1563449 [       task-3812] c.b.h.a.s.MyScheduler   : Job finished
2022-12-31 00:08:00.001 INFO  1563449 [       task-3813] c.b.h.a.s.MyScheduler   : Job start...
2022-12-31 00:08:00.006 INFO  1563449 [       task-3813] c.b.h.a.s.MyScheduler   : Job finished
2022-12-31 00:09:00.000 INFO  1563449 [       task-3814] c.b.h.a.s.MyScheduler   : Job start...
2022-12-31 00:09:00.005 INFO  1563449 [       task-3814] c.b.h.a.s.MyScheduler   : Job finished
2022-12-31 00:10:00.001 INFO  1563449 [       task-3815] c.b.h.a.s.MyScheduler   : Job start...
2022-12-31 00:10:00.005 INFO  1563449 [       task-3815] c.b.h.a.s.MyScheduler   : Job finished
----
+
로그를 보면 딱히 문제 없는 것 같다. `@Async` 에 할당된 기본 Thread Scheduler 인 org.springframework.scheduling.concurrent.ThreadPoolTaskScheduler 가 Thread 를 계속 생성하며 `@Scheduled` 작업을 반복 실행하는 것을 확인할 수 있다.

- jaewon: Dart에서 ``hashCode``와 `==` 연산자가 무엇을 의미하고, 어떤 관계를 갖는지에 대해 학습했습니다.
+
``hashCode``는 기본적으로 각각의 객체가 참조하는 주솟값을 정수 형태로 제공하며, 애플리케이션이 실행되는 동안에는 특정 객체의 ``hashCode``를 여러 번 호출하더라도 같은 값이 반환되어야 합니다. 이때, 내용과 ``hashCode``가 같은 객체들은 `==` 연산자에 의해 동일한 객체로 판단되는 반면, 내용이 같더라도 ``hashCode``가 다르면 동일하지 않은 객체로 판단됩니다.
+
특정 클래스가 활용되는 맥락에 따라 다른 동등 관계를 지정해야 할 때가 발생할 수 있는데, 그땐 `==` 연산자를 재정의해야 하고, 일관성을 유지하기 위해 ``hashCode``도 같이 재정의합니다.

- gon: ThreadPoolTaskExecutor를 보면 prestartAllCoreThreads라는 필드가 있습니다. 
기본적으로는 false라서 ThreadPoolTaskExecutor를 생성하면 core 쓰레드는 1개만 생성되서 실행됩니다.
true로 설정해서 ThreadPoolTaskExecutor를 생성하면 처음 설정한 core pool size만큼 core쓰레드를 생성합니다.

[[section-202309-W1]]
=== 2023년 9월 1주
- hwan: MYSQL 의 `IF(condition, trueValue, falseValue)`` 함수가 H2Database 에서 없어 Medium Test 가 어려울 때:
+
. `CASE WHEN condition THEN trueValue ELSE falseValue END;` 로 변경하기
. Bridge 구현:
+
다음의 SQL 을 H2 Console 에서 실행하고,
+
[source, sql]
----
CREATE ALIAS IF NOT EXISTS HEX FOR "com.example.test.common.h2.H2Function.IF";
----
+
이런 adapter logic 을 작성해 준 뒤
+
[source, kotlin]
----
package com.example.test.common.h2;

class H2Function {
    companion object {
        @JvmStatic
        fun IF(condition: String, trueValue: String, falseValue: String): String {}
    }
}
----
+
H2Database JAR 를 로드한 Classpath 에 위치시켜 주면 된다. +

- wongue: 실무에서 종종 쓸만한 괜찮은 프로그램을 발견했다. 특히 Flutter Test 패키지 때문에 text compare 는 매우 자주 사용할것 같다. +
  https://devtoys.app/ +

- gon: 주말에 새로운 스프링 프로젝트를 하나 알게 되었다.
https://www.baeldung.com/spring-modulith 인데 모놀리식 서버를 구현하는데 지원하는 스프링 프로젝트이다. 

- jaewon: 생체, 도체와 같은 한우 관련 용어들과 그 유통 과정 등에 대해 익숙해지고 있는 와중에, 지난 목요일에는 경호님 주관하에 **"(한우)스펙"**에 대한 이해도를 높이는 시간을 가졌습니다. 다른 분야에서 쓰일 때의 의미와는 다르게, 한우의 스펙은 꽤 애매모호한 개념이라는 생각이 들었고, 해외에서는 이걸 어떻게 관리하고 있을지 궁금해지기도 했습니다...🤔

[[section-202309-W2]]
=== 2023년 9월 2주
- gon: 기술적인 애기는 아니지만 굉장히 감명갚게 읽은 책이 두권어서 소개시켜드릴겸 lwil에 적습니다.
  * 금리의 역습: 금리는 어떻게 부의 질서를 뒤흔드는가
  * 돈을 찍어내는 제왕, 연준
사실 책의 내용을 잘 이해 못한것 같지만 경제를 새로 바로 볼수 있다는 점에서 굉장히 재미있엇습니다.

- wongue: Flutter 의 Timer Class 의 정밀도는 micro sec 단위로는 그리 정밀하지 못하다.

- hwan: 서로 다른 두개의 Table 이 관계를 맺고 있을 때 테이블 A(`users`) 로부터 테이블 B(`users_personal_config`) 로 값을 복사하는 법:
+
[source, sql]
----
CREATE TABLE `users`
(
    `seq`       BIGINT      NOT NULL AUTO_INCREMENT UNIQUE,
    `id`        BINARY(16)  NOT NULL PRIMARY KEY,
    `nickname`  VARCHAR(32) NOT NULL UNIQUE
);

CREATE TABLE `users_personal_config`
(
    `users_seq`     BIGINT      NOT NULL UNIQUE,
    `users_id`      BINARY(16)  NOT NULL,
    `new_nickname`  VARCHAR(32) NOT NULL

    PRIMARY KEY (`users_id`)
        REFERENCES `users` (`id`)
        ON DELETE CASCADE
    CONSTRAINT `fk_users_personal_config_users_seq` FOREIGN KEY (`users_seq`)
        REFERENCES `users` (`seq`)
)
----
+
여기서 `users` 테이블의 `nickname` 컬럼을 `users_personal_config` 테이블의 `new_nickname` 컬럼 값으로 copy 하되,
'users_id' 로 서로 연결한 레코드의 값을 복사하는, 즉 자기 자신의 값으로 복사하려면 다음과 같은 Query 를 작성하면 된다.
+
[source, sql]
----
UPDATE `users_personal_config` upc
    JOIN `users` u ON upc.`users_id` = u.`id`
SET upc.`new_nickname`      = u.`nickname`
WHERE u.`id` IN (?)
----
+
다음처럼 복잡하게 FOR EACH 를 작성하는 것 보다 훨씬 더 직관적이다. 어렵게 생각하지 말자!
+
[source, sql]
----
DECLARE @userId BIGINT
DECLARE @nickname DATETIME

SET @userId = ?

WHILE @userId <= ?
BEGIN
    SELECT @nickname = `nickname`
    FROM `user`
    WHERE `id` = @userId

    UPDATE `users_personal_config`
    SET `new_nickname` = @nickname
    WHERE `users_id` = @userId

    SET @userId = @userId + 1
END
----
