= 2023년 3분기 07월-09월 LWIL(Last week I learnt) 모음
// Metadata:
:description: Last Week I Learnt
:keywords: study, til, lwil
// Settings:
:doctype: book
:toc: left
:toclevels: 4
:sectlinks:
:icons: font

[[section-202307]]
== 2023년 7월

[[section-202307-W1]]
=== 2023년 7월 1주
- hwan: JPA 에서 Shared PK 를 `@Id` 처럼 쓰려면 `@IdClass` 를 쓸 수 있다. `@EmbeddedId` 도 쓰는데 각각 장단점이 있다. 물리적인 DB Table 관점에서는 `@IdClass` 가 좀 더 낫고, 의미론적인 관점에서는 `@EmbeddedId` 가 좀 더 낫다.

- youjin: dart 에서 interface class 에 메소드를 적으려면, 무조건 body block 을 작성해야한다.
+
[source, dart]
----
  interface class FlyBehavior {
    // void fly();
    void fly(){ }
  }
----
+
옵저버 패턴을 활용할 때, ‘주인공’이 누구냐에 따라 이기적인 요인이 작용된다.
즉, 주체(Subject)가 있고 관찰자(Observer)가 있을 때, 
주인공이 ‘주체(Subject)’라면, 모든 정보를 일괄적으로 모든 관찰자에게 PUSH 하고 싶어한다. (이기적 요인)
주인공이 ‘관찰자(Observer)’라면, 내가 받고 싶은 정보만 주체에서 꺼내오는 PULL 하고 싶어한다. (이기적 요인)
+
하지만, 주로 코드를 작성할 때, 옵저버패턴은 주체는 하나이고 관찰자가 N개인 상황이기 때문에, 관찰자의 편의로 PULL 받아오는 패턴이 일반적으로 좋은 패턴이라고 칭한다.

- wongue: Dart 의 Recode 의 extention 중에는 (Future<T1>, ... , Future<T10) 으로만 이루어진 Recode 에 한해 wait method 를 제공해준다. +
++ window 의 블루스크린이 'blue' 인 이유는 특별한 의도가 담겨있다기 보단 그 당시 작업자의 펌웨어 화면색을 그대로 따라갔다고 한다. +
출처: https://www.youtube.com/watch?v=KgqJJECQQH0

- gon: mysql에서 레코드 하나당 관리하는 저장 용량의 크기가  65,535 바이트 라고 한다.
그래서 varchar 타입으로 10000의 크기로 7개를 만들면 에러가 발생한다

[[section-202307-W2]]
=== 2023년 7월 2주
- hwan: spring-data 이용시 두 개 이상의 `DataSource` 및 `TransactionManager` 를 쓸 경우, `@Transactional` 에 `transactionManager` 속성을 다음과 같이 지정해 주지 않으면 오류가 발생한다. +
+
[source, kotlin]
----
@Transactional(transactionManager = "someTransactionManager")
----
+
다만 매번 Transaction manager 를 지정하는 것이 번거로울 수 있고 또한 Infrastructure Service Logic 이 특정 DataSource 를 대상으로만 동작해야 한다는 전제가 깔려 있는 경우가 있을 때도 많다. 이런 경우에는, 기본 TransactionManager 를 지정해 줄 수 있다. +
+
[source, kotlin]
----
@Configuration
internal class DefaultTransactionManager(
    private val applicationContext: ApplicationContext
): TransactionManagementConfigurer {
    @Bean
    override fun annotationDrivenTransactionManager(): TransactionManager =
        applicationContext.getBean(SomeTransactionManager.NAME) as TransactionManager
}
----
- youjin: 저번주에 확인했었던 `interface class` 의 경우, 바디에 block 을 사용하고 싶지 않다면, `abstract interface class` 라고 작성하면 된다.

[[section-202307-W3]]
=== 2023년 7월 3주
- hwan: 대한민국 공공 API 를 신청하면 `serviceKey` 라는 API Key 를 받는다. 문제는, 이 Key 가 URL Safe 하지 않다는 것이다. 이 때문에, 전달받은 serviceKey 를 제대로 쓰려면 반드시 다음 코드처럼 URL Safe encode 해 줘야 한다.
+
[source, kotlin]
----
import java.net.UrlEncoder

fun String.urlEncode() = URLEncoder.encode(this, StandardCharsets.UTF_8.toString())
----

- gon: 리눅스에서는 어플리케이션에서 접근 할 수 있는 경로를 제공하기위해 시스템 콜의 경로를 파일디스크립션이라는 형태로 추상화를 제공한다.
그래서 tcp/ip 같은 네트워크도 보면 fd형태로 접속정보를 관리한다.

- wongue: Computer Vison 에서는, 이미지의 Affine 변환과 perspective 변환을 용이하게 수행하기 위해, 이미지 소스의 차원에 + w 차원을 더한, Homogeneous coordinate 를 사용한다.

[[section-202307-W4]]
=== 2023년 7월 4주
- hwan: AWS S3 의 특정 bucket 을 공공 접근하게 설정하는 법:
+
. 환경 설정의 'Block _all_ public access' 체크를 해제한다.
+
. Permissions 의 Bucket Policy 에 다음 설정을 추가한다.
+
[source, javascript]
----
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "AddPerm",
      "Effect": "Allow",
      "Principal": "*",
      "Action": "s3:GetObject",
      "Resource": "arn:aws:s3:::<<MY_BUCKECT_NAME>>/*"
    }
  ]
}
----
+
AWS 가 이런 방법을 문서로 딱히 제공하지 않는 이유: S3 에 접근하는 트래픽마다 비용이 발생하기 때문에, 접근 횟수가 비정상적으로 많거나 큰 파일을 누구나 접근하게 허용할 경우 네트워크 사용 비용이 기하급수적으로 늘어나기 때문. 따라서 Bucket 을 public open 할 때는, CDN 설정을 추가로 고려해 보는 편이 좋다. AWS 의 CloudFront, Azure CDN, Akamai, Cloudflare 같은 서비스가 대표적인 CDN 서비스라고 할 수 있다.

gon: 이번 재시도 관련 함수를 짜면서 배운것이 있다.
제너럴한 인터페이스나 기능을 만들땐 최대한 기능이 단순하며 보편적이어야한다 
필요한 조건은 함수로 받아서 작업해서 함수를 호출하는 쪽에서 조건을 제어하게 해주자

wongue: 우리가 '밝기'를 인식하는 방법은 소리의 '크기'를 인식하는 방법과 유사하다. +
Logscale 로 그 세기를 인식하는데, 간단히 설명하면, 밝기(조도)가 1lx에서 10lx 까지 증가한 것과, 10lx 에서 100lx 까지 증가 했을때, 우리는 밝기가 1, 2, 3 처럼 선형적으로 증가했다 인식한다. +
이 특징은 광학 디스플레이의 설계와 사용에서도 충분히 반영되어야만 사람은 화상에서 자연스러운 밝기를 인식할 수 있는데,
소프트웨어 엔지니어로서 주의해야할 점은 이미지를 RGB 색공간에서 다룬다고 가정할때, 원 이미지의 밝기를 0~255 의 단계로 인코딩 할 시, 각 단계가 선형적인 간격을 가지게 하는것이 아니라 로그 스케일의 간격을 가지도록 저장해야만 우리 눈이 상대적은 둔감한 밝은 영역의 정보에 무의미한 투자를 막을 수 있다.

[[section-202307-W5]]
=== 2023년 7월 5주

gon: 인코딩중 EUC-KR 은 한글을 2byte로 처리한다 많이 쓰는 UTF-8은 한글을 보통 3바이트로 처리한다.
