= 2023년 2분기 04월-06월 LWIL(Last week I learnt) 모음
// Metadata:
:description: Last Week I Learnt
:keywords: study, til, lwil
// Settings:
:doctype: book
:toc: left
:toclevels: 4
:sectlinks:
:icons: font

[[section-202304]]
== 2023년 4월

[[section-202304-W1]]
=== 2023년 4월 1주
- youjin: Flutter 에서 go-router 를 개인프로젝트에 도입해보았다. 생각보다 오래걸리진 않았지만, 본대로 플랫폼에 도입하게 된다면 해당하는 스크린들이 많아서 시간이 꽤 걸릴것으로 예상한다. +

- yoonho: + 
즐거움은 멀리있지 않다. +
만발한 벚꽃과 사람이 가득한 여의도 벚꽃 축제보다 +
집 앞의 핀 벚꽃 나무 한 그루의 잔잔힘이 더 큰 의미를 안겨줄수 있다.

- hwan: Kotlin 의 `Iterable<T>.first` 와 `Iterable<T>.single` extension function 의 차이 +
+
* `first` 는 여러개의 T 들 중 제일 먼저 나오는 한개만을 찾겠다는 의미
* `single` 은 여러개의 Iterable 로 감싸져 있는 T 의 갯수는 오직 하나여야 하며 그 하나만을 가져오겠다는 의미
+
즉, 이런 문맥의 코드에서는 `first` 보다 `single` 이 문맥상 더 올바르다.
+
[source, kotlin]
----
fun save(tag: ProductTag): ProductTag = saveAll(listOf(tag)).single()   // first 대신 single

fun saveAll(tags: Collection<ProductTag>): List<ProductTag>
----

- gon : CAS는 현재 스레드가 가지고 있는 기존값과 메모리가 가지고 있는 값을 비교해 같은 경우 변경할 값을 메모리에 반영하고 true를 반환한다. 다른 경우에는 변경값이 반영되지 않고 false를 반환한 다음 재시도를 하는 방식으로 동작한다. CAS방식을 통해 가시성과 원자성 문제를 해결할 수 있다.

- wongue:
 흔히 RH-O blood type 의 경우 모든 혈액형에 수혈이 가능하다 알려져 있지만, 사실 그렇게 쓰이진 않는다고한다. +
 1. RH-O 의 인구수가 적어 그 타입끼리 수혈하기도 빠듯하고, +
 2. 소량의 경우는 수혈이 가능하지만, 대량 수혈은 거부반응이 일어나기 떄문이다. +
 

[[section-202304-W2]]
=== 2023년 4월 2주
- wongue: Flutter 의 정체성은 "강력한 크로스 플랫폼 UI Framework"이다. +
즉, Flutter 의 한계또한 "크로스 플랫폼 UI Framework" 이라는 정체성에서 정해지게 된다. +
하드웨어에 밀접한 기능, OS 의 강력한 권한을 이용해야하는 기능, UI 가 없는 Background 에서 수행되어야 하는 기능 등을 개발할때는 Flutter 는 큰 도움이 되기 힘들다. +
결국 실행되는 환경에 따른 각각의 네이티브 로직이 들어서야 할 필요성이 있는데, +
아직 다룰 수 있는 기술 스텍이 Flutter 밖에 없는 나는 UI 개발자라고는 할 수 있지만, "클라이언트 개발자" 로서는 반쪽짜리가 아닌가 싶다. +
진정한 "크로스 플랫폼 클라이언트 전문가" 가 되기 위해선, 적어도 IOS, Android, Web 세 네이티브 환경에 대한 많은 경험과 지식이 동반되어야 하는게 아닐까.
- youjin: dart 에서는 같은 enum 타입의 value인지 비교하는 구문에서 컴파일러가 다른 타입과 비교하는지, 미리 잡아주지 않는다. +
```dart
  // ele.productImageType 이 ProductImageTypeDTO 이었지만, ProductImageType 으로 같은지 비교하고 있었다.
  // 하지만 컴파일타임에서 알수가 없고, false가 나올 것이기 때문에, orElse 구문을 항상 타고 있었다.
    HanwooMediaDto thumbNailDto = mediaDtoList.firstWhere((ele) => ele.productImageType == ProductImageTypeDTO.MAIN,
        orElse: () => HanwooMediaDto.whenReceivedNull());
```

- gon : 코드 품질이 사업에 영향을 담은 유튜브 영상이 있어서 가져왔다
https://www.youtube.com/watch?v=lcvZ9kBn2_M
결론은 코드 품질은 결국엔 더 빠른 개발, 더 적은 결함을 만들어준다고 한다
