= 2023년 3분기 10월-12월 LWIL(Last week I learnt) 모음
// Metadata:
:description: Last Week I Learnt
:keywords: study, til, lwil
// Settings:
:doctype: book
:toc: left
:toclevels: 4
:sectlinks:
:icons: font

[[section-202310]]
== 2023년 10월

[[section-202310-W1]]
=== 2023년 10월 1주
- hwan: 유명한 js 라이브러리인 lodash 에는 link:https://github.com/lodash/lodash/blob/main/src/sample.ts[sample] 과 link:https://github.com/lodash/lodash/blob/main/src/sampleSize.ts[sampleSize] 라는 로직이 있다. 테스트 뿐 아니라 이벤트 당첨자 추첨 같은 실제 비즈니스 로직에서도 종종 유용하게 사용했던 경험이 있다. 그런데 요즘 주로 사용하는 kotlin 에는 비슷한 함수가 없어 `Iterable<*>.shuffled().take(M)` 같은 호출을 해야 한다. 이 호출 chain 의 경우 입력 `Iterable` 의 크기를 `N` 이라고 하고, `take` 의 파라미터 크기를 `M` 이라 가정한다면, `M` < `N` 일수밖에 없음에도 시간과 공간 복잡도가 항상 `N` 이 나온다. 이 점이 이상하다고 생각해서, 시간과 공간 복잡도를 `M` 으로 줄여보려 했더니 Random Accessible `Iterable` 이라는 아주 한정적인 상황에서만 가능하다는 것을 알게 되었다. 왜냐면 `Iterable` 은 Random Access 가 불가능하기 때문에 `shuffle` 이 없는 `sample` 을 할 경우, 같은 `M` 에 대해 항상 같은 결과만 나오게 되어 로직이 그다지 쓸모 없게 된다.
+
Kotlin standard library 에서는 이 문제를 link:https://github.com/JetBrains/kotlin/blob/master/libraries/stdlib/native-wasm/src/kotlin/collections/Collections.kt#L83[이렇게 해결]하고 있었다. 나는 처음 `shuffle` 이라는 문제를 받아들였을 때 `shuffle` 의 결과는 입력과 무조건 달라야 한다고 생각했었는데 따지고 보면 그럴 필요가 없다. 섞더라도 원본이 나올 수 있으니까. 즉, 처음부터 접근을 잘못하면 이 문제는 쓸데없이 복잡해 지는 문제라는 것을 알게 되었다. 참고로 Kotlin native 의 구현은 Fisher-Yates shuffle algorithm 을 참고하고 있는데, 이 로직은 시간 복잡도와 공간 복잡도가 O(`N`) 이며, 입력과 섞은 결과가 일치할 확률은 `1/N²` 으로 N 이 커질수록 `shuffle` 의 결과가 같을 확률이 급격하게 0에 수렴하게 된다.
+
https://github.com/openjdk/jdk/blob/jdk-21-ga/src/java.base/share/classes/java/util/Collections.java#L482:[Java standard library 의 경우]에는 조금 더 최적화를 먹여서, Input `N` 이 5 미만일 때는 공간 복잡도가 `1` 이 되는 구현을 쓰고 있다. 다만 이는 *모든 `List` 는 mutable* 이라는 Java 언어의 강한 가정 위에 성립하는 로직이므로 Kotlin/JVM 에서는 주의해야 한다.

- wongue: Flutter 에서 Text Widget 이 화면에 글자를 그리기 위한 과정. +
 `TextWidget Build` -> `RichText createRenderObject` -> `RenderParagraph` -> `TextPainter` -> `layout` -> `paint` -> `drawParagraph` -> `nativeParagraph._paint` -> `(impala engine)` -> `(grapic backend)` +
impala engine 과 grapic backend(ex OpenGL ES) 안의 과정또한 flutter 내부의 과정과 비슷한 복잡도를 가진다. +
단순히 글자를 그리는 동작도 이런 많은 인스턴스를 생성하고 상호작용해야하기 때문에, Flutter 에서 widget 의 불필요한 rebuild 를 줄이는것이 앱 퍼포먼스의 향상으로 이어지는 이유. +

[[section-202310-W2]]
=== 2023년 10월 2주
- hwan: kotlin 에서 reflection 으로 어떤 `sealed class` 의 모든 하위 구현 타입들을 찾는 코드:
+
[source, kotlin]
----
val allSubTypes = 
    SomeSealedClass::class.nestedClasses.filter { it.isFinal && it.isSubclassOf(SomeSealedClass::class) }
----

- wongue: 한 주의 시작을 월요일로 볼지, 일요일로 볼지 에 대한 국제 표준은 월요일이 한주의 시작이라고 한다. +
한국에서 또한 이를 따라가기로 결정했다. link:https://e-ks.kr/streamdocs/view/sd;streamdocsId=72059203331956996[문서의 2.2.8 을 확인] +
그럼에도 불구하고, google calender, ios calender, kakao calender 는 한 주의 시작을 일요일로 표현하는데, 이는 기독교 사회 전통이 강한 미국의 영향이라고 한다. +

- gon: java에서 os쓰레드와 java에서의 쓰레드가 있다. 그런데 java에서의 쓰레드를 부르는데 여러가지 이름이 있다. 여러 아티클을 보면 그린쓰레드, 유저쓰레드 등등등 java의 Thread를 부르는 이름이 제각각이었다.
그런데 이번 가상쓰레드가 도입되면서 자바측에서 이름을 좀 정해준 느낌이 든다.
가상쓰레드를 생성하는 팩토리 메서드의 이름이 다음과 같다
+
[source, java]
----
Thread.ofVirtual() 
----
+
그럼 기존의 쓰레드를 생성하는 팩토리 메서드는 뭘까?
+
[source, java]
----
Thread.ofPlatform() 
----
다. java에서 이제 플랫폼쓰레드 라는 이름을 좀 밀어주는것 같다

- jaewon: 새로운 기능의 개발을 처음부터 맡게 되면서 배우게 된 것들이 많아 정리해 보았습니다.
+
도메인 주도 개발::
API 문서를 참고하여 Remote Service부터 구현한 뒤에 Repository, ViewModel, View의 순서대로 차근차근 개발해 나가면 된다고 생각했었는데, 먼저 구현해 둔 Remote Service와 그 DTO에 과도하게 의존하게 되어 Domain Object와 Repository를 정의할 때 어려움을 겪게 되었다.
+
도메인 주도 개발의 관점에서는 해결하고자 하는 문제의 주된 개념인 Domain Object를 개발 의도에 맞게 정의하는 것이 가장 우선시되어야 하며, 이를 기반으로 Repository와 ViewModel을 구현하여 비즈니스 로직이 원활하게 작동할 수 있도록 해야 한다. Remote Service와 그 DTO는 말 그대로 Data를 옮기는, 부수적인 역할을 할 뿐이다.
+
국제화/지역화::
국제화/지역화 관점에서 모든 문자 리터럴은 다른 국가에서 해당 국가의 언어로 대체될 수 있기 때문에 리소스로 추출해 관리하는 게 좋고, 내용이 같더라도 다른 맥락을 지닌 리소스는 따로 분리해 둬야 한다.
+
기타::
* 위젯을 분리할 때, Helper Method보다는 Widget으로 분리하는 게 좋다.
* 테스트 코드: Bad Case에 대해서도 사양에 포함되어야 한다.

[[section-202310-W3]]
=== 2023년 10월 3주
- hwan: 한우 식당 같은데서 종종 볼 수 있는 '우삼겹' 이란 부위를 업계에서는 '업진양지' 라고 부른다. 양지는 소의 뱃살 부근의 고기인데 특히 '업진양지' 는 대체로 기름이 많이 나오기 때문에 주로 구워먹는 편이다. 샤브샤브 등으로 먹기도 하지만 그렇게 하려면 매우 얇게 썰어야 한다.

- gon: kotlin에는 contract라는 기능이 있다.
일종의 컴파일러에 힌트를 주는것이라 보면됩니다 이걸 이용하면 null 타입인데 특정 구간에서부터는 not null로 처리 할 수 있다.

[[section-202310-W4]]
=== 2023년 10월 4주
- hwan: 노르웨이는 국어가 2개인 나라라고 한다. 한국인 입장에서는 잘 상상이 되지 않지만... 각각 Bokmål(보크몰), Nynorsk(뉘노르스크) 라고 하는데 보크몰은 덴마크, 스웨덴어의 잔재가 많이 남은 언어, 뉘노르스크는 옛 노르웨이어를 최대한 복원한 말이라고 한다. 두 언어 사이에는 뜻이 거의 통하지 않는단다. 마치 우리나라의 본토말과 제주도말의 차이 같은걸까?

- wongue: 
link:https://developer.chrome.com/blog/from-webgl-to-webgpu/#canvas-handling[참고자료]를 보면, 한 WebDocs 안에서 활용할 수 있는 WebGL canvas의 최대 개수는 16개라고 한다. +
그렇다면 flutter web 또한 graphic backend 를 webGL 을 사용하고 있을태니, 한 Docs 안에서 최대 16개의 flutter web app 을 띄울 수 있지 않을까? 란 궁금증이 생겼는데, +
flutter web embedding 은 한 web docs 안에서 하나의 캔버스에만 가능한듯 하다. (iframe 등을 사용하지 않는다면.) 

- gon: 뉴스 피드 시스템(혹 페북, 인스타그램)을 개발 할 때 크게 2가지 방법이 있다.
push 모델과 pull모델이 있는데 각각의 특징은 다음과 같다
```text
- Push 모델:
- Push 모델은 
- 유저가 새로운 정보나 업데이트가 발생할 때 정보를 유저의 친구의 포스팅 캐시에 미리 넣어놓는 방식을 애기합니다
- 항상 최신화된 정보를 빠르게 사용자에게 제공 할 수 있지만 비활성화 유저등의 포스팅 캐시도 업데이트 해야해서 비용이 큰 방식입니다.

- Pull 모델:
- Pull 모델은 피드 조회시점의 자기 친구들의 게시글을 가져오는 방식으로 동작합니다.
- 피드를 구성하는 속도면에서는 push에 비해 느리지만 비활성화 유저에 투자되는 비용이 없습니다
```
대형 서비스에서는 해당 두가지 모델을 섞어 쓰는것으로 알고있습니다.
유명인의 경우 pull모델을 적용시켜 리소스를 절약하고 일반사용자의 경우 push모델을 적용시켜 속도를 개선하는 방식으로 알고있습니다.

[[section-202310-W5]]
=== 2023년 10월 5주
- hwan: JVM 17, Spring 5.3.x 환경에서 Spring data mongo 쓸 때 Custom converter 를 등록하기 위해 `MappingMongoConverter` 를 직접 `@Bean` 으로 만들 때의 주의사항
+
java.time.Instant 를 필드로 쓰고 있는 `@Document` 를 사용할 때, MongoDb 환경설정을 요런 식으로 코딩할 경우 
+
[source, kotlin]
----
@Document("my_mongo_document")
class MyMongoDocument(
    val createdAt: java.time.Instant
)

@Configuration
@EnableMongoRepositories
class MongoConfig {
    @Bean
    fun mappingMongoConverter(mongoDbFactory: SimpleMongoClientDatabaseFactory): MappingMongoConverter {
        return MappingMongoConverter(DefaultDbRefResolver(mongoDbFactory), MongoMappingContext())
    }
}
----
+
이런 exception 이 발생
+
[source, shell]
----
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'myMongoRepository' defined in com.example.MyMongoRepository defined in @EnableMongoRepositories declared on com.example.appconfig.MongoConfig: Invocation of init method failed; nested exception is java.lang.reflect.InaccessibleObjectException: Unable to make private java.time.Instant(long,int) accessible: module java.base does not "opens java.time" to unnamed module @27082746
----
+
일단 문제 해결하려면 다음과 같이 코딩해야함. `MongoMappingContext` 를 Spring Boot 기본 설정으로부터 주입받아야 해결할 수 있음.
+
[source, kotlin]
----
@Configuration
@EnableMongoRepositories
class MongoConfig {
    @Bean
    fun mappingMongoConverter(mongoDbFactory: SimpleMongoClientDatabaseFactory, mongoMappingContext: MongoMappingContext): MappingMongoConverter {
        return MappingMongoConverter(DefaultDbRefResolver(mongoDbFactory), mongoMappingContext)
    }
}
----
+
`org.springframework.boot.autoconfigure.data.mongo.MongoDataConfiguration` 내부의 `MongoMappingContext` `@Bean` 생성과정에서 발생한 stack trace 를 따라가보면 문제 원인지점을 짐작할 수 있음
+
[source, shell]
----
java.lang.reflect.InaccessibleObjectException: Unable to make private java.time.Instant(long,int) accessible: module java.base does not "opens java.time" to unnamed module @27082746
    at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
    at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
    at java.base/java.lang.reflect.Constructor.checkCanSetAccessible(Constructor.java:188)
    at java.base/java.lang.reflect.Constructor.setAccessible(Constructor.java:181)
    at org.springframework.util.ReflectionUtils.makeAccessible(ReflectionUtils.java:202)
    ... 생략 ...
    at org.springframework.data.mongodb.core.mapping.MongoMappingContext.createPersistentEntity(MongoMappingContext.java:100)
    at org.springframework.data.mongodb.core.mapping.MongoMappingContext.createPersistentEntity(MongoMappingContext.java:41)
    at org.springframework.data.mapping.context.AbstractMappingContext.doAddPersistentEntity(AbstractMappingContext.java:430)   << 이 지점 주목
    at org.springframework.data.mapping.context.AbstractMappingContext.addPersistentEntity(AbstractMappingContext.java:406)
    ... 생략 ...
----
+
그리고 Spring data mongo 의 기본 `MongoMappingContext` `@Bean` 구현은 다음과 같은데,
+
[source, java]
----
class MongoDataConfiguration {
    @Bean
    @ConditionalOnMissingBean
    MongoCustomConversions mongoCustomConversions() {
        return new MongoCustomConversions(Collections.emptyList());
    }
}

public class MongoCustomConversions extends org.springframework.data.convert.CustomConversions {
    private static final StoreConversions STORE_CONVERSIONS;

    static {
        // ... 생략 ...

        STORE_CONVERSIONS = StoreConversions.of(MongoSimpleTypes.HOLDER, STORE_CONVERTERS);     // MongoSimpleTypes 에 주목
    }

    // 생략
}
----
+
`org.springframework.data.mongodb.core.mapping.MongoSimpleTypes` 에는 `java.time.Instant` 변환 규칙이 추가되어 있고, 이 구현은 아래에서 확인할 수 있다.
+
[source, java]
----
public class MongoCustomConversions extends org.springframework.data.convert.CustomConversions {
    // ... 생략 ...
    /**
     * Create a new {@link MongoCustomConversions} instance registering the given converters.
     *
     * @param converters must not be {@literal null}.
     */
    public MongoCustomConversions(List<?> converters) {
        this(MongoConverterConfigurationAdapter.from(converters));
    }

    /**
     * Create a new {@link MongoCustomConversions} given {@link MongoConverterConfigurationAdapter}.
     *
     * @param conversionConfiguration must not be {@literal null}.
     * @since 2.3
     */
    protected MongoCustomConversions(MongoConverterConfigurationAdapter conversionConfiguration) {
        super(conversionConfiguration.createConverterConfiguration());  // createConverterConfiguration 호출에 주목
    }

    public static class MongoConverterConfigurationAdapter {
        // ... 생략 ...
        private boolean useNativeDriverJavaTimeCodecs = false;

        /**
         * Create a {@link MongoConverterConfigurationAdapter} using the provided {@code converters} and our own codecs for
         * JSR-310 types.
         *
         * @param converters must not be {@literal null}.
         * @return
         */
        public static MongoConverterConfigurationAdapter from(List<?> converters) {

            Assert.notNull(converters, "Converters must not be null");

            MongoConverterConfigurationAdapter converterConfigurationAdapter = new MongoConverterConfigurationAdapter();
            converterConfigurationAdapter.useSpringDataJavaTimeCodecs();
            converterConfigurationAdapter.registerConverters(converters);

            return converterConfigurationAdapter;
        }

        ConverterConfiguration createConverterConfiguration() {
            // ... 생략 ...

            /*
             * We need to have those converters using UTC as the default ones would go on with the systemDefault.
             */
            List<Object> converters = new ArrayList<>(STORE_CONVERTERS.size() + 3);
            converters.add(DateToUtcLocalDateConverter.INSTANCE);
            converters.add(DateToUtcLocalTimeConverter.INSTANCE);
            converters.add(DateToUtcLocalDateTimeConverter.INSTANCE);
            converters.addAll(STORE_CONVERTERS);

            StoreConversions storeConversions = StoreConversions
                    .of(new SimpleTypeHolder(JAVA_DRIVER_TIME_SIMPLE_TYPES, MongoSimpleTypes.HOLDER), converters);

            return new ConverterConfiguration(storeConversions, this.customConverters, convertiblePair -> {
                // ... 생략 ...
            }, this.propertyValueConversions);
        }
    }
}
----
+
Spring data mongo 가 이 문제를 해결하는 과정은 다음과 같다.
+
1. `MongoCustomConversions(List)` 생성자 호출
2. `protected` 생성자는 기본 `MongoConverterConfigurationAdapter` 구현 인스턴스를 생성하고 `createConverterConfiguration()` 호출
3. 별다른 `MongoConverterConfigurationAdapter` 설정이 없기 때문에 `MongoCustomConversions` 생성시 등록된 `STORE_CONVERTERS` 를 변환규칙에 추가
4. `STORE_CONVERTERS` 내에 있는 `java.time.Instant` 변환규칙이 자동으로 실행

- gon : 카프카가 흔히들 빠르다고 한다. 카프카는 어떻게 데이터를 빠르게 처리할까?
답은 zero copy라는 방법을 써서 빠르게 데이터를 보낼수있다
좀 더 자세히 설명하면
기존의 전송 방식은 disk - os버퍼 -> app버퍼 -> 소켓버퍼 -> nic 버퍼라면
zero-copy는 disk -> os버퍼 -> nic버퍼로 바로 데이터를 복사시킨다
java에선 transferTo() 메서드를 이용하면 된다

- wongue: 하나의 컴퓨터 안에서는 데이터를 저장/로드시 동일한 엔디안을 사용하므로 유저는 이를 알지 못해도 되지만 컴퓨터 외부로 데이터를 이동시킬 땐 문제가 발생한다. +
이는 자릿수를 역순으로 읽을건가 정순으로 읽어야 하냐의 문제다. 이때 endian 이라는 단어는 조너선 스위프트의 '걸리버 여행기' 에서 유래했다고 한다.

- jaewon: Dart에서 변수를 선언할 때, `late` 키워드를 활용하면 해당 변수의 초기화를 뒤로 미룰 수 있다. 예를 들어, 비동기 통신의 결괏값이 할당되기 전까지 변수의 초기화를 지연시키고 싶은데, 해당 변수가 non-nullable하게 유지되어야 한다면 `late` 키워드로 그 변수에 "늦은" 초기화를 허용할 수 있다.
+
다만 ``late``가 적용된 변수에 대해서는 Compile-time에서의 검사가 생략되기 때문에, 만약 Runtime에서 초기화/할당에 성공하지 못한 변수에 접근하게 된다면 그 즉시 예외가 발생한다. 따라서 Compile-time에서 진행될 수 있는 검사가 불필요하게 Runtime으로 미뤄지지 않도록 ``late``의 사용을 최소화하는 것이 좋다. +

[[section-202310-W6]]
=== 2023년 10월 6주

- wongue: dart/Flutter WebApp 에서는, 의존하는 패키지가 너무 많아지면 main.dart(); 의 초기화 시간이 늘어나는 문제가 있다. +
이는 패키지 임포트를 deferred 로 선언하며 일부분 해결 할 수 있다.
+
[source ,dart]
----
import 'package:somePackagename.dart' deferred as SomePack; // 이렇게 선언하고

....codes...

// 필요한 시점에서 이런식으로 lazy하게 로딩할 수 있다.
SomePack.loadLibrary();
----

- hwan: `@DataJdbcTest`, `@DataJpaTest` 등을 쓸 때 주의사항
+
. Medium Test 가 성공했다고 해서 내 로직이 제대로 돌 거라는 착각 금지. 테스트 스케일 내의 `@Transactional` 때문에 된 것일 수도 있다. Medium Test 로 검증한 조회로직이라 하더라도 Large Test 에서 이용자 시나리오 기반으로 한 번 더 확인하는 편이 정신건강에 이롭다.
+
. `@Transactional` 을 이용한 auto rollback 을 너무 믿지 말라는 것. 프로젝트 구조가 복잡해지고, JPA 와 JdbcTemplate 를 이용한 Raw Query, MongoDB, Redis, Neo4j 등 Persistent storage 의 종류가 다양해 지면 데이터의 정확한 보존 및 제거 경계가 애매해지기 쉽다. 특히 어떤 Test 에서 Persistent storage 에 write 를 했다면, '`@Transactional` 이 있으니까 cleanup 을 안 해도 괜찮아~' 같은 생각은 위험할 수 있다. 프로젝트가 한참 복잡해 진 뒤에 잘 되던 테스트가 갑자기 실패할 수 있는데, 가령 test 갯수가 2000개라면 2000개를 다 돌리는 중에 문제가 발생하기 쉽상이다. 이 경우 문제 원인을 찾는 과정은 정말 지옥이다.
