= 2024년 1분기 01월-03월 LWIL(Last week I learnt) 모음
// Metadata:
:description: Last Week I Learnt
:keywords: study, til, lwil
// Settings:
:doctype: book
:toc: left
:toclevels: 4
:sectlinks:
:icons: font

[[section-202401]]
== 2024년 01월

[[section-202401-W1]]
=== 2024년 01월 1주
- gon: Spring의 web 기반 ApplicationContext 구현은 관련 웹 애플리케이션이 종료될 때 Spring IoC 컨테이너를 우아하게 종료시키기(graceful shutdown)) 위한 코드를 이미 포함하고 있습니다. web이 아니라면 별도의 설정을 해줘야 한다.
- hwan: 거세(후덜덜)를 표현하는 영 단어를 이때까지는 `castrate` 만 알고 있었는데, `neuter` 라는 표현도 있다고 한다.  후자는 거세 뿐 아니라 '중성화' 라는 의미에 더 가까우며 동물에게만 쓸 수 있는 말이다. 반면 전자는 정확하게 동물의 수컷 혹은 인간 남성을 거세해 버리는 것을 의미한다고 한다. 영 단어에도 우리나라의 '머리' 혹은 '대가리' 같은 개념이 있다는 것도 신기했고, 아직 축산용어에 대해 여전히 많이 모른다는 사실을 알게 되어 조금은 부끄러운 한 주였다.
- wongue: 위치정보를 획득하는 일반적인 방법은 GPS(Global Positioning System) 이다. 하지만, 통신 방법의 특성상 지하, 건물 안에서는 GPS 위성 신호를 청취 할 수 없는 문제가 있다. +
이럴 때 사용하는 방법은 BLE(Bluetooth Low Energy) beacon (apple 은 iBeacon 이라 부른다.)을 사용한다고 한다. 특히 한국 서울시민의 경우 이동 경로에 지하철을 주로 사용하는 경우가 많으므로, +
위치 정보를 이용한 소프트웨어 어플리케이션을 작성 할 시, 두 매체를 모두 능숙하게 다루어야 할 필요성이 있다.
- gyeongtae : DB connection pool을 그저 사용만 하고 있었는데, 메모리에 올라가는 객체이고 스레드가 이 커넥션 객체를 사용 후 반납하는 개념이라는 걸 알았다. pool이란 개념때문에 내부적으로 스레드가 생성되지 않을까 했었는데 그런건 아니라고한다.

[[section-202401-W2]]
=== 2024년 01월 2주
- gon: 프로세스의 생성과 종료는 어떻게 될까?
생성: 프로세스 생성은 보통 부모 프로세스가 fork() 시스템 콜을 사용하여 자식 프로세스를 생성하는 방식으로 이루어집니다. 이때 자식 프로세스는 부모 프로세스의 복사본으로 생성되며, 필요한 경우 exec() 시스템 콜을 통해 다른 프로그램으로 교체될 수 있습니다. 이렇게 할 경우 부모프로세스가 자식프로세스를 관리하기가 굉장히 쉬워지고 프로세스를 처음부터 생성하는것보다 복사후 덮어씌우는게 더 빠릅니다.
종료: 프로세스는 작업을 완료하거나 종료 시스템 콜을 통해 종료될 수 있습니다. 프로세스가 종료되면 운영 체제는 해당 프로세스에 할당된 자원을 회수합니다.
