= 2024년 2분기 04월-06월 LWIL(Last week I learnt) 모음
// Metadata:
:description: Last Week I Learnt
:keywords: study, til, lwil
// Settings:
:doctype: book
:toc: left
:toclevels: 4
:sectlinks:
:icons: font

[[section-202404]]
== 2024년 04월

[[section-202404-W1]]
=== 2024년 04월 1주
- hwan: Kotlin 에서는 extension function 도 상속을 이용한 확장 구현이 된다. Template pattern 에서 유용하게 활용할 수 있는 테크닉인듯...
+

[source, kotlin]
----
abstract class Converter<T, U> {
    protected abstract fun T.convert(): U
}

class StringToNumberConverter : Converter<String, Number> {
    override fun String.convert(): Number {
        // ..
    }
}

class StringToUuidConverter : Converter<String, Uuid> {
    override fun String.convert(): Uuid {
        // ..
    }
}
----

- gon :
```
@Transactional
@Schedule(3)
fun scheduleTask() {
    if(list.isEmpty()) { return }
    // doSomething
}
```
위 코드를 보시면 어떤 문제가 있을것으로 생각되나요? +
@Transactional을 너무 습관적으로 붙힌 안좋은 대표적인 예라고 생각합니다. +
위 코드의 경우 task가 어떠한 일을 하지않아도 3초마다 트랜잭션을 열고 닫습니다. +
그것이 스케줄링에서 원하는 행동이라면 상관없지만 보통은 스케줄링돌때 아무일도 안하는 경우에 트랜잭션을 열 이유는 없기때문에 +
@Transactional을 사용한다면 꼭 그뒤의 동작을 잘 예상하면서 사용해야 한다.

- gyeongtae: 어제 AI engineer랑 Front 앞으로의 미래에 대해서 얘기를 나눴다. 요즘 AI를 활용한 UI 개발이 아주 빨라지고 있는데 과연 앞으로도 React가 쓰일까? HTML + CSS + jquery 같은 단순한 형태로 가도 되지 않을까란 얘기가 주였다. 삼신기라고 하면서 설명을 했는데 비슷한 생각을 나 또한 하고 있다. 앞으로 FE의 미래가 궁금해지긴 한다. 관련 자료들을 찾아보면 좋을거같다.

[[section-202404-W2]]
=== 2024년 04월 2주
- hwan: MacOS 에서 Android Build 를 하면 환경변수로 설정한 JAVA_HOME 을 무시하고 /Applications/Android Studio.app/Contents/jre/Contents/Home 를 강제로 JAVA_HOME 으로 설정해 버린다. 이 때문에 Android Studio 의 JDK 보다 높은 버전의 라이브러리를 이용할 경우 JDK Version 이 맞지 않는 문제가 발생한다. Android Studio 를 삭제해서 당장 문제를 해결하긴 했지만 근본적인 해결책이 무엇일까...
