= 2024년 1분기 01월-03월 LWIL(Last week I learnt) 모음
// Metadata:
:description: Last Week I Learnt
:keywords: study, til, lwil
// Settings:
:doctype: book
:toc: left
:toclevels: 4
:sectlinks:
:icons: font

[[section-202401]]
== 2024년 01월

[[section-202401-W1]]
=== 2024년 01월 1주
- gon: Spring의 web 기반 ApplicationContext 구현은 관련 웹 애플리케이션이 종료될 때 Spring IoC 컨테이너를 우아하게 종료시키기(graceful shutdown)) 위한 코드를 이미 포함하고 있습니다. web이 아니라면 별도의 설정을 해줘야 한다.
- hwan: 거세(후덜덜)를 표현하는 영 단어를 이때까지는 `castrate` 만 알고 있었는데, `neuter` 라는 표현도 있다고 한다.  후자는 거세 뿐 아니라 '중성화' 라는 의미에 더 가까우며 동물에게만 쓸 수 있는 말이다. 반면 전자는 정확하게 동물의 수컷 혹은 인간 남성을 거세해 버리는 것을 의미한다고 한다. 영 단어에도 우리나라의 '머리' 혹은 '대가리' 같은 개념이 있다는 것도 신기했고, 아직 축산용어에 대해 여전히 많이 모른다는 사실을 알게 되어 조금은 부끄러운 한 주였다.
- wongue: 위치정보를 획득하는 일반적인 방법은 GPS(Global Positioning System) 이다. 하지만, 통신 방법의 특성상 지하, 건물 안에서는 GPS 위성 신호를 청취 할 수 없는 문제가 있다. +
이럴 때 사용하는 방법은 BLE(Bluetooth Low Energy) beacon (apple 은 iBeacon 이라 부른다.)을 사용한다고 한다. 특히 한국 서울시민의 경우 이동 경로에 지하철을 주로 사용하는 경우가 많으므로, +
위치 정보를 이용한 소프트웨어 어플리케이션을 작성 할 시, 두 매체를 모두 능숙하게 다루어야 할 필요성이 있다.
- gyeongtae : DB connection pool을 그저 사용만 하고 있었는데, 메모리에 올라가는 객체이고 스레드가 이 커넥션 객체를 사용 후 반납하는 개념이라는 걸 알았다. pool이란 개념때문에 내부적으로 스레드가 생성되지 않을까 했었는데 그런건 아니라고한다.

[[section-202401-W2]]
=== 2024년 01월 2주
- gon: 프로세스의 생성과 종료는 어떻게 될까? +
생성: 프로세스 생성은 보통 부모 프로세스가 fork() 시스템 콜을 사용하여 자식 프로세스를 생성하는 방식으로 이루어집니다. 이때 자식 프로세스는 부모 프로세스의 복사본으로 생성되며, 필요한 경우 exec() 시스템 콜을 통해 다른 프로그램으로 교체될 수 있습니다. 이렇게 할 경우 부모프로세스가 자식프로세스를 관리하기가 굉장히 쉬워지고 프로세스를 처음부터 생성하는것보다 복사후 덮어씌우는게 더 빠릅니다. +
종료: 프로세스는 작업을 완료하거나 종료 시스템 콜을 통해 종료될 수 있습니다. 프로세스가 종료되면 운영 체제는 해당 프로세스에 할당된 자원을 회수합니다.

- hwan: Kotlin/JVM 에서 Value class 를 사용할 경우 `@JvmInline` 특성 때문에 타입 이름 및 필드명과 실 구현체의 정보가 달라 mockito(및 mockito-kotlin) 라이브러리의 `any()` 가 잘 동작하지 않는 문제가 있다. 가령:
+
[source, kotlin]
----
@JvmInline value class Foo(val realValue: String)
----
+
을 파라미터로 사용하는 어떤 객체의 mock 조건을 다음처럼 `any()` 로 설정할 경우:
+
[source, kotlin]
----
given(someMockRepository.findByFoo(any())).willReturn(bar)
----
+
다음과 같은 예외가 발생한다.
+
[source, kotlin]
----
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method Foo.box-impl, parameter v
----
+
이는 코틀린 컴파일러가 컴파일타임에 주입해준 정보와 로직이 런타임에 Reflection 으로 실제 얻어낸 정보가 불일치해 발생하는 현상이다. 코드상에서는 `Foo` 라는 타입을 파라미터로 쓰지만 실제로는 `String` 을 쓰도록 컴파일하기 때문에 mock 라이브러리가 이를 감안해줘야 하는데 그 과정이 2024-01 현재 업데이트 되지 않아 발생하는 것이다. 따라서 이 문제를 해결하려면 다음과 같은 구현을 추가해 주고 `any()` 사용처를 `anyValueClass()` 로 바꿔 주면 된다.
+
[source, kotlin]
----
/**
 * Kotlin 의 value class 들은 Mockito-Kotlin 라이브러리의 [ArgumentMatchers.any] matcher 를 쓸 수 없다.
 * 이 문제를 해결해 주기 위한 함수. 이 구현 내에서 반환하는 기본값은 구색 맞추기에 불과하고 ArgumentMatcher 내부에서는
 * 클래스의 Canonical name 을 비교하기 때문에, 이 함수를 통해 반환되는 객체는 실제로는 사용되지 않는다.
 *
 * @author yh@sirloin.co.kr
 * @since 2023-12-03
 */
inline fun <reified T: Any> anyValueClass(): T {
    val (javaClass, emptyValue) = when {
        NumberValueHolder::class.java.isAssignableFrom(T::class.java) -> Number::class.java to NumberValueHolder.EMPTY_VALUE_INT
        UuidValueHolder::class.java.isAssignableFrom(T::class.java) -> UUID::class.java to UuidValueHolder.EMPTY_VALUE
        StringValueHolder::class.java.isAssignableFrom(T::class.java) -> String::class.java to StringValueHolder.EMPTY_VALUE
        else -> throw NotImplementedError("${T::class} 타입의 기본값 전략을 구현해 주세요.")
    }
    val constructor = T::class.constructors.find { it.parameters.size == 1 }
    val emptyInstance = constructor?.call(emptyValue)

    return (ArgumentMatchers.any(javaClass) ?: emptyInstance) as T
}
----

- wongue: 기하학, 혹은 컴퓨터 그래픽에서 종종 다루게 되는 언어 법선(法線). +
법선에서 법(法)이 가지는 의미에 대해 종종 궁금점을 가지고 있었는데, 메가스터디의 현우진 강사의 유튭 쇼츠에서 perpendicular의 'per-' 의 중국식 음차에 기반했다는 주장을 듣게되었다. +
이를 듣고 조금 미심쩍었는데, 비슷한 생각을 가진 글을 발견했다. link:https://orbi.kr/00056500907[오르비 게시물] +
[per] 와 法 의 중국식 발음 [Fa] 는 그리 비슷한 발음은 아니기 떄문에 단순 음차로서 결정됬다기 보단, plumb line (link:https://ko.wikipedia.org/wiki/%EB%8B%A4%EB%A6%BC%EC%B6%94[다림추]) 와 같이 [기준이 되는] 이라는 의미를 전달하기 위함이 아니였을까 하는 주장이다. +
여기에 또한 의문인게, '법선' 은 perpendicular line 보다는 normal line 이라고 주로 표현된다. + 
두 단어의 유래를 찾아보면, link:https://www.etymonline.com/kr/word/perpendicular#etymonline_v_12733[perpendicular]이 '완벽하게 수직한' 이라는 뜻을 가진 시기는 1590 년이고, link:https://www.etymonline.com/kr/word/normal#etymonline_v_9799[normal] 이 '수직의' 이라는 뜻을 가지게 된건 1640 년이라고 한다. +
18~19 세기즈음 중국에서 '법선' 이라는 단어를 번역했을때의 원 단어가 'perpendicular line' 이 아닌 'normal line' 일 확률이 더 높다 생각되고, + 
normal 에는 공통되는 표준, 규칙에 따른, 일반적인 이라는 의미또한 따르니, 이를 의미하는 글자 法 을 선택한게 아닐까 하는 개인적인 추측이다.

- gyeongtae: line/JDSL 공식문서 JPQL with Kotlin JDSL에는 다음과 같은 문장이 있습니다. JpqlRenderer는 상태를 가지지 않기 때문에 객체의 재사용이 가능하며 멀티 쓰레드 환경에서 사용하기에 안전합니다. Immutable이 아니라면 어떻게 되길래 이런 문구를 써놨을까 궁금했습니다. 객체에서 상태란 조건이나 특성 필드 등을 말하는데 이 정보들이 가변 상태로 외부로부터 변경이 가능하다면 내부 상태가 다른 스레드로 부터 변경되어 원하는 동작이 안할 수도 있다고 합니다. jdsl에서 SelectQuery 객체를 받아 sql string value로 바꿔주는 동작을 하는 JpqlRenderer기 가변상태라면 select * from member 가 나와야하는 SelectQuery를 파라미터로 요청해도 다른 스레드로 인해 다른 쿼리가 실행될 수 있는 것입니다. 그렇기 때문에 line 에서는 해당 객체를 불변 상태로 외부에서 변경 가능하지 않게 한 것입니다. 

앞으로 Base64 같은 외부에서 선언해주는 객체들이 정말 Thread-safe한가 고민해보고 선언해야되겠습니다.
