= 2024년 1분기 01월-03월 LWIL(Last week I learnt) 모음
// Metadata:
:description: Last Week I Learnt
:keywords: study, til, lwil
// Settings:
:doctype: book
:toc: left
:toclevels: 4
:sectlinks:
:icons: font

[[section-202401]]
== 2024년 01월

[[section-202401-W1]]
=== 2024년 01월 1주
- gon: Spring의 web 기반 ApplicationContext 구현은 관련 웹 애플리케이션이 종료될 때 Spring IoC 컨테이너를 우아하게 종료시키기(graceful shutdown)) 위한 코드를 이미 포함하고 있습니다. web이 아니라면 별도의 설정을 해줘야 한다.
- hwan: 거세(후덜덜)를 표현하는 영 단어를 이때까지는 `castrate` 만 알고 있었는데, `neuter` 라는 표현도 있다고 한다.  후자는 거세 뿐 아니라 '중성화' 라는 의미에 더 가까우며 동물에게만 쓸 수 있는 말이다. 반면 전자는 정확하게 동물의 수컷 혹은 인간 남성을 거세해 버리는 것을 의미한다고 한다. 영 단어에도 우리나라의 '머리' 혹은 '대가리' 같은 개념이 있다는 것도 신기했고, 아직 축산용어에 대해 여전히 많이 모른다는 사실을 알게 되어 조금은 부끄러운 한 주였다.
- wongue: 위치정보를 획득하는 일반적인 방법은 GPS(Global Positioning System) 이다. 하지만, 통신 방법의 특성상 지하, 건물 안에서는 GPS 위성 신호를 청취 할 수 없는 문제가 있다. +
이럴 때 사용하는 방법은 BLE(Bluetooth Low Energy) beacon (apple 은 iBeacon 이라 부른다.)을 사용한다고 한다. 특히 한국 서울시민의 경우 이동 경로에 지하철을 주로 사용하는 경우가 많으므로, +
위치 정보를 이용한 소프트웨어 어플리케이션을 작성 할 시, 두 매체를 모두 능숙하게 다루어야 할 필요성이 있다.
- gyeongtae : DB connection pool을 그저 사용만 하고 있었는데, 메모리에 올라가는 객체이고 스레드가 이 커넥션 객체를 사용 후 반납하는 개념이라는 걸 알았다. pool이란 개념때문에 내부적으로 스레드가 생성되지 않을까 했었는데 그런건 아니라고한다.

[[section-202401-W2]]
=== 2024년 01월 2주
- gon: 프로세스의 생성과 종료는 어떻게 될까? +
생성: 프로세스 생성은 보통 부모 프로세스가 fork() 시스템 콜을 사용하여 자식 프로세스를 생성하는 방식으로 이루어집니다. 이때 자식 프로세스는 부모 프로세스의 복사본으로 생성되며, 필요한 경우 exec() 시스템 콜을 통해 다른 프로그램으로 교체될 수 있습니다. 이렇게 할 경우 부모프로세스가 자식프로세스를 관리하기가 굉장히 쉬워지고 프로세스를 처음부터 생성하는것보다 복사후 덮어씌우는게 더 빠릅니다. +
종료: 프로세스는 작업을 완료하거나 종료 시스템 콜을 통해 종료될 수 있습니다. 프로세스가 종료되면 운영 체제는 해당 프로세스에 할당된 자원을 회수합니다.

- hwan: Kotlin/JVM 에서 Value class 를 사용할 경우 `@JvmInline` 특성 때문에 타입 이름 및 필드명과 실 구현체의 정보가 달라 mockito(및 mockito-kotlin) 라이브러리의 `any()` 가 잘 동작하지 않는 문제가 있다. 가령:
+
[source, kotlin]
----
@JvmInline value class Foo(val realValue: String)
----
+
을 파라미터로 사용하는 어떤 객체의 mock 조건을 다음처럼 `any()` 로 설정할 경우:
+
[source, kotlin]
----
given(someMockRepository.findByFoo(any())).willReturn(bar)
----
+
다음과 같은 예외가 발생한다.
+
[source, kotlin]
----
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method Foo.box-impl, parameter v
----
+
이는 코틀린 컴파일러가 컴파일타임에 주입해준 정보와 로직이 런타임에 Reflection 으로 실제 얻어낸 정보가 불일치해 발생하는 현상이다. 코드상에서는 `Foo` 라는 타입을 파라미터로 쓰지만 실제로는 `String` 을 쓰도록 컴파일하기 때문에 mock 라이브러리가 이를 감안해줘야 하는데 그 과정이 2024-01 현재 업데이트 되지 않아 발생하는 것이다. 따라서 이 문제를 해결하려면 다음과 같은 구현을 추가해 주고 `any()` 사용처를 `anyValueClass()` 로 바꿔 주면 된다.
+
[source, kotlin]
----
/**
 * Kotlin 의 value class 들은 Mockito-Kotlin 라이브러리의 [ArgumentMatchers.any] matcher 를 쓸 수 없다.
 * 이 문제를 해결해 주기 위한 함수. 이 구현 내에서 반환하는 기본값은 구색 맞추기에 불과하고 ArgumentMatcher 내부에서는
 * 클래스의 Canonical name 을 비교하기 때문에, 이 함수를 통해 반환되는 객체는 실제로는 사용되지 않는다.
 *
 * @author yh@sirloin.co.kr
 * @since 2023-12-03
 */
inline fun <reified T: Any> anyValueClass(): T {
    val (javaClass, emptyValue) = when {
        NumberValueHolder::class.java.isAssignableFrom(T::class.java) -> Number::class.java to NumberValueHolder.EMPTY_VALUE_INT
        UuidValueHolder::class.java.isAssignableFrom(T::class.java) -> UUID::class.java to UuidValueHolder.EMPTY_VALUE
        StringValueHolder::class.java.isAssignableFrom(T::class.java) -> String::class.java to StringValueHolder.EMPTY_VALUE
        else -> throw NotImplementedError("${T::class} 타입의 기본값 전략을 구현해 주세요.")
    }
    val constructor = T::class.constructors.find { it.parameters.size == 1 }
    val emptyInstance = constructor?.call(emptyValue)

    return (ArgumentMatchers.any(javaClass) ?: emptyInstance) as T
}
----

- wongue: 기하학, 혹은 컴퓨터 그래픽에서 종종 다루게 되는 언어 법선(法線). +
법선에서 법(法)이 가지는 의미에 대해 종종 궁금점을 가지고 있었는데, 메가스터디의 현우진 강사의 유튭 쇼츠에서 perpendicular의 'per-' 의 중국식 음차에 기반했다는 주장을 듣게되었다. +
이를 듣고 조금 미심쩍었는데, 비슷한 생각을 가진 글을 발견했다. link:https://orbi.kr/00056500907[오르비 게시물] +
[per] 와 法 의 중국식 발음 [Fa] 는 그리 비슷한 발음은 아니기 떄문에 단순 음차로서 결정됬다기 보단, plumb line (link:https://ko.wikipedia.org/wiki/%EB%8B%A4%EB%A6%BC%EC%B6%94[다림추]) 와 같이 [기준이 되는] 이라는 의미를 전달하기 위함이 아니였을까 하는 주장이다. +
여기에 또한 의문인게, '법선' 은 perpendicular line 보다는 normal line 이라고 주로 표현된다. + 
두 단어의 유래를 찾아보면, link:https://www.etymonline.com/kr/word/perpendicular#etymonline_v_12733[perpendicular]이 '완벽하게 수직한' 이라는 뜻을 가진 시기는 1590 년이고, link:https://www.etymonline.com/kr/word/normal#etymonline_v_9799[normal] 이 '수직의' 이라는 뜻을 가지게 된건 1640 년이라고 한다. +
18~19 세기즈음 중국에서 '법선' 이라는 단어를 번역했을때의 원 단어가 'perpendicular line' 이 아닌 'normal line' 일 확률이 더 높다 생각되고, + 
normal 에는 공통되는 표준, 규칙에 따른, 일반적인 이라는 의미또한 따르니, 이를 의미하는 글자 法 을 선택한게 아닐까 하는 개인적인 추측이다.

- gyeongtae: line/JDSL 공식문서 JPQL with Kotlin JDSL에는 다음과 같은 문장이 있습니다. JpqlRenderer는 상태를 가지지 않기 때문에 객체의 재사용이 가능하며 멀티 쓰레드 환경에서 사용하기에 안전합니다. Immutable이 아니라면 어떻게 되길래 이런 문구를 써놨을까 궁금했습니다. 객체에서 상태란 조건이나 특성 필드 등을 말하는데 이 정보들이 가변 상태로 외부로부터 변경이 가능하다면 내부 상태가 다른 스레드로 부터 변경되어 원하는 동작이 안할 수도 있다고 합니다. jdsl에서 SelectQuery 객체를 받아 sql string value로 바꿔주는 동작을 하는 JpqlRenderer기 가변상태라면 select * from member 가 나와야하는 SelectQuery를 파라미터로 요청해도 다른 스레드로 인해 다른 쿼리가 실행될 수 있는 것입니다. 그렇기 때문에 line 에서는 해당 객체를 불변 상태로 외부에서 변경 가능하지 않게 한 것입니다. 

앞으로 Base64 같은 외부에서 선언해주는 객체들이 정말 Thread-safe한가 고민해보고 선언해야되겠습니다.


[[section-202401-W3]]
=== 2024년 01월 3주

- gon: 대표적인 동기화 메커니즘인 Mutex와 Semaphore의 핵심적 차이는 임계영역에 접근가능한 작업자가 1이냐 아니냐도 맞지만 또 다른 차이는 소유권(잠금)에 대한 해제의 권한의 차이도있다 +
Mutex는 잠금을 소유하면 소유한 작업자가 반드시 직접 해제를 해야한다. 반면 Semaphore는 잠금을 소유한 작업자가 아니더라도 다른 작업자가 잠금을 해제 가능하다 즉 잠금 해제에 대한 제한이 없다. 

- gyeongtae: linux에는 사용자가 시스템을 쉽게 구성하고 동작시키게 해주는 명령어인 service와 systemctl이 있다. systemctl은 좀 더 현대에 나온 기술이고 services는 이전 Linux에서 사용되는 전통적인 명령어이다. systemctl은 시스템 로그를 보고 활성 비활성 등의 다양한 작업이 가능하다. 하지만 service는 systemctl에 비해 기능이 제한적이라고 한다. 참고로 service는 init.d 기반 systemctl은 systemd 기반으로 기반 시스템도 다르다.

- hwan: Kotlin/JVM 에서 Jackson 라이브러리를 이용해 JSON file 을 다음과 같은 kotlin 코드로 파싱할 때:
+
[source, kotlin]
----
val objMapper = ObjectMapper().apply {
  registerModules(JavaTimeModule(), KotlinModule.Builder().build())
}

val data = objMapper.readValue(
  File("/my_json_file.json"),
  object : TypeReference<List<MyJsonData>>() {}
)

@JsonDeserialize
data class MyJsonData(
  @JsonProperty(name = "my_json_field")
  val field1: String
)
----
+
다음과 같은 에러가 발생할 수 있다:
+
[source, kotlin]
----
Exception in thread "main" com.fasterxml.jackson.module.kotlin.MissingKotlinParameterException: Instantiation of [simple type, class MyJsonData] value failed for JSON property my_json_field due to missing (therefore NULL) value for creator parameter my_json_field which is a non-nullable type
 at [Source: (File); line: 24, column: 3] (through reference chain: java.util.ArrayList[0]->com.bondaero.admin.HanwooProductMongoEntity["my_json_field"])
----
+
원인은 바로 JSON 은 내부에 개행 문자(Carrage Return)를 허용하지 않기 때문에 벌어지는 일이다. 따라서 JSON Minifier 등을 이용해 개행을 제거하고 재시도 해보자. 이걸로 30분 날렸다. ㅠㅠ

- jaewon: 본대로 앱에서 주문 조회 결과를 날짜별로 필터링하는 기능을 구현하면서 ``DateTimeRange``라는 타입을 처음 활용해 봤습니다. `DateTimeRange` 타입의 구현은 단순했습니다.
+
[source, dart]
----
DateTimeRange({
  required this.start,
  required this.end,
}) : assert(!start.isAfter(end));
----
+
`DateTimeRange` 는 두 개의 `DateTime` 값을 하나의 타입으로 관리할 수 있다는 점에서도 이점을 갖지만, ‘기간의 시작 값이 그 끝보다 늦지 않은지’에 대해 기본적인 검증을 거치고 있다는 점에서 DateTime의 “범위(Range)”라는 맥락을 명확하게 반영하고 있었습니다.
+
해당 맥락을 잘 활용하면 주문 조회 기간의 시작 값이 그 끝보다 늦은 경우를 예방할 수 있고, 경고 문구 노출과 같은 UI를 추가하지 않을 수도 있기 때문에 앞으로도 관련 업무에서 `DateTimeRange` 타입을 적극적으로 활용해 볼 예정입니다.

[[section-202401-W4]]
=== 2024년 01월 4주
- gon : lseek 함수는 UNIX 계열 시스템에서 파일 내에서 읽기/쓰기 포인터의 위치를 변경하는 데 사용되는 함수이다
가령 파일 내의 특정 위치로 이동하여 데이터를 읽거나 쓸 때 필요하다.
java에서는 lseek의 역할을 하는 함수가 있다 RandomAccessFile 의 seek() 함수이다.
파라미터로 pos를 받는데 파일 내에서 설정하고자 하는 포인터의 위치를 지정합니다. pos는 파일의 시작부터 바이트 단위로 측정되며, 0에서 시작합니다. 즉, 파일의 맨 처음 위치를 지정하려면 pos를 0으로 설정하면 됩니다.

- hwan: 100% 서버에서만 결제 못하는 이유. 클라이언트 사이드의 결제를 허용할 수 밖에 없는 이유.
+
ex) 네이버페이, 카카오페이 등은 클라이언트 SDK 에서 결제 수단을 충전하도록 되어 있음. 그리고 그들 페이 서비스는 서버측의 callback url 을 요구한다. 이 flow 에서 서버는 네이버/카카오페이의 영수증을 비교하는 것 말고는 할 수 있는 일이 없다.
이 때문에 고객의 지불과 상품의 주문 요청은 서로 다를 수 밖에 없다. 문제는 서버가 이 페이 서비스들의 callback url 호출을 놓쳤을 때다. 이 때는 페이 SDK 요청은 성공해 돈은 냈는데 우리 서버로의 주문 요청이 없어 서버가 고객의 돈만 먹고 주문을 처리하지 못하는 상황이 반드시 발생한다.
+
따라서 이 문제를 해결하려면 결국:
+
. 결제 대행 서비스의 웹훅 API 를 잘 이용하고, 메시지를 절대로 놓치지 않도록 잘 구현해야 함
. 결제 대행 서비스의 원장과 우리 주문정보를 잘 비교하고 원장에 대응하는 주문이 없다면 이를 후처리할 수 있어야 함
. 페이 서비스 창이 닫힌 이후 클라이언트도 서버에 지불 및 주문 상황을 주기적으로 poll 하며 상황을 판단하고, 일정 시간 이후에는 페이 서비스측에 자동 취소

+
하는 등의 대책을 세울 수 밖에 없다.

- wongue: Mac OS 에서 응용 프로그램을 빌드할 때, 사용하는 디렉토리가 Icloud 에 추적되고 있다면, 빌드 과정 중 많은 File I/O 로 인해 Icloud 의 버전과 싱크가 맞지 않게 되어 +
Icloud 측에서 conflict 를 직접 해결하라고 text 1.txt 와 같은 파일이 생성된다. +
이러한 conflict 파일들로 인해 빌드과정에 오류가 발생 할 수 있다.

- gyeongtae: kotlin delegation은 상속 없이 객체의 공통 멤버들을 특정 객체에 위임합니다. 예를 들어 

[source, kotlin]
----
interface Base {
    fun print()
}

class BaseImpl(val x: Int) : Base {
    override fun print() { print(x) }
}

class Derived(b: Base) : Base by b

fun main() {
    val b = BaseImpl(10)
    Derived(b).print()
}
----

by 키워드를 통해 Base를 위임 받아 Derived에 위임 해주면 Derived는 Base가 하는 일을 수행할 수 있습니다.
이는 kotlin의 모든 class가 final인 특성을 감안하여 불변 객체에서 상속의 특성을 이용해 보일러 플레이트 코드를 줄일 수 있다는 장점이 있습니다. 

[[section-202402-W1]]
=== 2024년 02월 1주

- gon : 코틀린에서 객체의 초기화시 순서는 다음과 같다
+
. constructor default argument
+
. property / init 둘은 선언 순서에 따라 달라질수있다
+
. constructor block
+
. 여기서 상속관계가 있다면
+
. child constructor default argument
+
. parent constructor default argument
+
. parent property / init
+
. parent constructor block
+
. child property / init
+
. child constructor block 순으로 진행된다
+
간단히 요약하자면 부모의 인스턴스를 전부 초기화후 자식의 인스턴스가 초기화 된다.

- wongue: Dart 에 macro 가 추가될 예정이라고 한다. (experimental branch 에는 이미 추가가 되었다.) +
link:https://github.com/dart-lang/language/blob/main/working/macros/motivation.md[관련링크]

- gyeongtae: form 태그 안에 button 태그가 있을 경우 발생하는 문제가 있다. 어떤 이벤트가 발생하든 해당 버튼을 누르면 reload가 된다. 그리고 이로인해 console에 error 로그가 사라져서 동작에는 문제가 없을 수 있지만 디버깅 하는데 어려움을 겪을 수 있다. 
+
[source, html]
----
<form>
  <button type="button">Sign in</button>
</form>
----
+
위 코드 처럼 type 을 button으로 주면 reload가 되지 않는다. 이는 default type이 submit이기 때문이다.

[[section-202402-W2]]
=== 2024년 02월 2주

- hwan: aws 의 private subnet 은 외부로부터의 접근을 차단할 수 있지만 public IP 도 없기 때문에 반대로 외부 접속도 못 하는 서버가 됨. 이를 해결하려면 NAT 설정을 추가로 해 줘야 한다.
+
이 때문에 긴급하게 호스트 하나 파서 뭔가 간단한 작업만 하고 종료할 때 이 지식이 기억나지 않는다면 엄청 헤매게 된다. 새로운 subnet 을 추가했음에도 이 subnet 을 사용하는 host 들이 public IP 가 없어 내/외부에서 접근할 수 없는 상황이 생기는 것이다.
+
이를 해결하려면 VPC > Subnets > [생성한 Subnet 선택] > Edit Subnet Settings 에 진입 후 'Enable auto-assign public IPv4 Address' 항목에 체크해 주면 된다.
+
단, AWS 에서 IP 주소를 더 이상 안 줄 때도 있으니 이 문제는 감안해야 한다.
+
또한 생성한 subnet 이 internet gateway 에 붙어있나도 확인해야 한다. VPC > Route Tables 메뉴에서 대상 Subnet 을 클릭하고  'Edit Routes' 를 고른 다음, Destination 항목에 0.0.0.0/0, Target 'Internet Gateway' 가 있나 확인해야 한다. 그렇게 하지 않으면 공공 IP 를 모두 할당받고 모든 작업을 다 끝냈음에도 외부와 통신할 수 없는 문제가 발생한다.

- gon : 
mac os 특정버전이상에서 임베디드 레디스가 제대로 작동안하는 버그가 있다
https://stackoverflow.com/questions/77304264/cant-start-redis-server-exception-occurs-when-trying-to-run-spring-boot-on-my
질문의 답변대로 새로운 임베디드 레디스 라이브러리를 사용하면 코드의 변경없이 문제 해결이 가능했다.

- wongue:
 흔히 냉철한 펙트를 기반한 과격한 피드벡이 사람을 보다 성장시킨다는 믿음(myth)을 가진 사람이 많다. +
 하지만, 이는 사실과는 거리가 멀다고 한다. 교육과 심리상담 양측 분야에서 모두 내담자를 존중하지 않는 방식은 장기적으로 효과가 없거나 부정적이였다는 것이고, 동시에 내담자들은 이 방식에 현혹될 가능성이 있다. +
 '쓰다고 모두 약은 아니다' 그리고 피드백을 핑계로 폭력성을 정당화하는것을 경계해야한다. +
 link:https://web.archive.org/web/20200227120819/http://agile.egloos.com/5931859[출처]

[[section-202402-W3]]
=== 2024년 02월 3주

- gon : 코틀린이 2.0 beta가 올라왔습니다. +
https://github.com/JetBrains/kotlin/releases +
https://kotlinlang.org/docs/whatsnew-eap.html

- wongue: mprotect() 라는 함수로 특정 메모리 구역의 접근 권한을 제어할 수 있다. +
따라서 서버가 나이브하게 요청으로 들어온 스크립트를 모두 실행하는 보안적 결함이 있다면, mprotect() 를 이용해 코드 세그먼트의 영역에 접근해 외부 소스코드를 덮어씌워버릴수 있는것. +
이러한 공격이 성공하게되면 공격자는 임의코드 실행, 시스템 권한 상승, 백도어 설치, 데이터 탈취및 조작등 상상할 수 있는 거의 모든 행동이 가능해진다. +

- hwan: NIC 가 여러 개 있는 machine 에서 local address 를 알아내는 방법: +
https://stackoverflow.com/questions/9481865/getting-the-ip-address-of-the-current-machine-using-java/38342964#38342964

[[section-202402-W4]]
=== 2024년 02월 4주
- hwan: 커피를 내려 마시는 방법에는 여러 가지가 있다. 그 중 우리가 흔하게 접할 수 있는 방식은 다음과 같다.
+
. 드립 커피: 독일식. 거름망을 깔때기(Dripper) 위에 설치하고, 분쇄한 커피 콩을 담아 온수를 천천히 부워 추출하는 커피. Brewed coffee 라는 표현도 쓴다. 특히 차 처럼 내려 마시는 방식과 유사해 일본에서 크게 발전했다고 한다.
. 에스프레소 커피: 이탈리아식. 곱게 간 원두에 고온 고압으로 소량의 물을 투과시키는 방식. 특유의 거품(Crema)이 많이 발생하며 카페인이 높게 추출된다. 대부분 기계를 이용한다. 기계를 이용한 방식이므로 쉬운 것 처럼 보이지만, 짧은 추출시간 내에 맛이 결정되기 때문에 오히려 더 어려운 방식이라고 한다.
. 튀르크 커피: 터키식. 커피 원조인 에티오피아 방식이, 당시 강대국이었던 터키로 넘어와 전 세계에 퍼져나간 것. 달임 커피라고도 한다. 제즈베(Cezve)라 부르는 손잡이 긴 작은 잔에 커피 가루와 물을 통째로 붓고, 끓인 다음 가루를 걸러내 마시는 방식. 직접 달이는 방식이므로 불이 필요하지만 최근에는 전기 제즈베도 판매하는 곳이 있다고 한다.

+
나는 커피를 차 처럼 마시는걸 좋아하는데, 이런 방식의 커피가 드립 커피란다. 좋은 상식을 하나 배웠다.

- gon : 스프링에서 흔히 @ErrorController를 이용해서 에러처리를 하는데 내부 구현이 정확히 어떻게 되어있는지 몰랏는데 이번 기회를 통해 알게되었다.
+
흔히 외부로 부터 요청이 들어오게되면 다음과 같은 순서를 타고 App의 Controller를 호출한다. 
+
```
WAS -> filter -> servlet -> interceptor -> Controller
```
+
이제 요청에서 에러가 발생하여 response.sendError()를 호출하면 WAS에게 까지 내용이 전파된다 +
(response.sendError() 호출안하면 그대로 client에게 was의 에러처리가 응답으로 보내진다) +
WAS는 오류 처리에 대한 정보를 찾아야하기 때문에 다시 요청을 보낸다 +
순서를 그리자면 다음과 같다. 
+
```
1. 처음 요청시
WAS -> filter -> servlet -> interceptor -> Controller

2. error 발생
WAS(error 전파 완) <- filter <- servlet <- interceptor <- Controller(response.sendError() 호출)

3. 에러 정보를 찾기위해 다시 요청
WAS("/error") -> filter -> servlet -> interceptor -> Controller("/error" 에 맞는 에러 api 호출)
```

+
이때 다시 요청을 보낼때 filter를 다시 거치게되는데 유저의 요청인지 에러 정보를 찾기위한 요청인지를 구분하기 위해 사용하는것이 `DispatcherType`이라는걸 추가로 사용한다. (servlet에서 제공하는 개념) +
REQUEST : 클라이언트 요청 +
ERROR : 오류 요청 +
이라 보면 된다 +
interceptor는 path를 제외하는 식으로 해결 가능하다.

- gyeongtae: Javascript에서 async/await로 생성되는 Promise를 처리할 때 microtaskQueue가 사용된다고 한다. 이벤트 루프에 일반적인 TaskQueue랑은 따로 존재하며 await 키워드가 붙은 작업이 모두 완료되면 microtaskQueue에 쌓인다. 이 후 event loop가 microtaskQueue에 접근하여 Queue가 비워질 때 까지 작업을 처리하고 이후 Task를 실행한다. 
+
[source, javascript]
----
Promise.resolve().then(() => console.log('Promise 실행됨'));

queueMicrotask(() => console.log('queueMicrotask 실행됨'));

console.log('메인 스크립트 실행됨');
----

+
실제로 위 함수를 실행시키면 메인 스크립트 실행됨이 먼저 출력 후 Promise 실행됨, queueMicrotask 실행됨이 출력된다. 이는 메인 스크립트가 완료된 직후 event loop가 microtaskQueue를 처리하기 때문이다.

- wongue: JIT 컴파일에 대해 조금 공부해보았다. Just In Time 컴파일링이라는것은 빌드 과정 이후, 런타임에서 필요한 시점에 바이너리 코드를 생성하는것을 의미한다. +
하지만, 여기서 의문이 들었다. linux 의 memory structure 를 보면 코드 세크먼트는 프로그렘 로드 과정에서 결정되고 그 이후에 동적으로 변경되지는 않는것으로 알고 있는데, 어떻게 런타임에 생성한 코드를 CPU 가 읽을 수 있도록 메모리에 할당하는걸까? +
대부분의 JIT 는 Java 나 JS 의 런타임 환경에서의 컴파일링을 말하는데, 두 런타임 모두 VM 위에서 돌아가기 때문에 힙 메모리 안에 컴파일된 바이너리 코드가 올라감을 확인할 수 있었다. +
하지만 아직 Cpp 의 JTP 컴파일에 대해서는 의문이다. OpenGL 등 쉐이더 코드는 프로그렘 런타임에 컴파일이 되는데, 이떄 컴파일된 코드는 메모리의 어떤 영역에서 관리되는걸까?

[[section-202403-W1]]
=== 2024년 03월 1주
- hwan: macOS 는 Document 디렉토리에 둔 파일들을 iCloud 에 자동 동기화 한다. 이 때문에 코딩 프로젝트처럼 파일을 대량으로 만들고 지우고 하는 일은 Document 디렉토리에서 **절대로** 하면 안 된다. 빌드가 아무 이유없이 깨지고, 분명히 IDE 에서 수정한 옛 내용이 갑자기 부활하는 등의 문제로 1년간 속 썩이다가 드디어 원인을 찾았다.
- gon : Cache Stampede (캐시 스탬피드)

캐시 스탬피드는 특정 시간에 캐시가 전체적으로 만료되거나 초기화되어 DB나 저장소 혹은 API등에 과도한 요청이 집중되는 현상을 의미합니다. 
예시로 1000건의 데이터를 5분 만료로 동시에 캐싱하였다하면 5분뒤에 해당 데이터를 전부 조회한다면 모든 데이터에 대해 캐시미스가 발생하게됩니다.

캐시 스탬피드를 방지하기위해서는 여러가지 전략이 있는데 
1. 캐시 만료 시간 무작위 : 캐싱을 할때 만료시간을 일정하게 하지말고 기준으로부터 약간의 변동을 주어 캐시가 동시에 만료되지 않게 합니다. 
2. 캐시 갱신 : 백그라운드에서 캐시된 데이터를 주기적으로 갱신하거나 만료되기전에 자동으로 갱신 합니다. 
3. Lock 메커니즘 : 캐시가 재생성 될 때 해당 데이터에 접근하는 다른 요청들을 대기 시킨후 캐시가 갱신된 이후에 요청을 진행시킵니다.

- wongue: Entity 와 VO(Value Object) 는 뭐가 다른거고, 새로운 클래스를 디자인할때 어떤 기준을 가지고 설계해야하는 걸까? +
link:https://martinfowler.com/bliki/EvansClassification.html[마틴 파울러의 블로그] 에서도 + 
"the trio(Entity, VO, Service Obj) are hard to define precisely, they are of the I know them when i see them category" 이를 정확히 나누는건 쉽지 않은 문제라른 사실을 말하고 있다. +
VO 와 Entity 의 명확한 구분법 중 하나는 VO 는 값을 기반으로 동등성 비교를 재정의하는 반면, Entity 는 그렇지 않다는 점이다. +
특정한 ID 를 기반으로 동일성을 비교한다면, Entity 모든 내부 필드의 동등성을 비교해야한다면 VO 라 생각할 수 있다. +
조금 더 정리해보자면, Entity 는 정보를 가져오는 방법에 대해 이야기하고 있다. (굳이 DB가 아니더라도) VO는 가저온 정보를 바탕으로 Domain Model 에 전달하기 위한 임시 객체 or Model 의 내부 필드로서 사용된다. +
따라서 Entity 는 데이터의 수집과 전달에 집중한 메서드를 가지고 있어야하고, VO는 가지고 있는 필드에 대한 연산에 집중한 메서드를 가지고 있는데 집중해야한다 생각한다.

[[section-202403-W2]]
=== 2024년 03월 2주

- wongue: flutter 커뮤니티에서도 요즘 떠오르는 신성인 Ondevice ai 를 위한 패키지가 주목을 받고 있다.
https://pub.dev/packages/google_ml_kit

- hwan: 시스템에 생성된 모든 docker container 들 한방에 지워버리기:
+
[source, shell]
----
for id in $(docker container ls -aq); do docker container rm $id; done
----

- gyeongtae: routify $goto function에 대해 알게 되었다. $goto function은 새로고침 없이 렌더링을 통해 상태를 유지한 상태로 재렌더링 하여 라우팅 하게 해준다. 이를 이용하면 페이지 변환이 빨라 UX를 향상시킬 수 있을 뿐만 아니라 store에 저장된 상태가 유지되게 할 수 있다.

[[section-202403-W3]]
=== 2024년 03월 3주
- hwan: `AUTO_INCREMENT` 를 미처 추가하지 않은 테이블에 나중에 `AUTO_INCREMENT` 를 추가하고 싶을 경우, 다음과 같은 방법을 써서 해결할 수 있다.
+

[source, sql]
----
ALTER TABLE `some_table` ADD COLUMN `seq` BIGINT;

SET @row_number = 0;
UPDATE `some_table`
SET `seq` = @row_number:=@row_number+1
ORDER BY `created_at`;

ALTER TABLE `some_table` MODIFY COLUMN `seq` BIGINT NOT NULL AUTO_INCREMENT, ADD UNIQUE INDEX `uk_some_table_seq` (`seq`);
----
+

단 이 방법은 아주 큰 단점이 몇가지가 있다.
+

. 당연히 Large data set 에서는 할 수 없다. 
. Table 에 어떤 비교순서로(대부분 Natural ordering) 정렬 가능한 기준 column 이 있어야 한다.
. 정렬 가능한 기준 column 이 Unique 하지 않은 경우(위 SQL 에서는 `created_at`) `some_table` 의 index order 에 따라 SEQ 가 결정됨. 이 때문에 결과가 의도대로 발생하지 않을 가능성이 있다.
. 중간 실패시 간단하게 돌아갈 수 있는 방법이 없다.
. 이 때문에 무중단 작업 진행은 불가능. 로직이 뒷받침되어야 하며 이 때문에 빠르게 작업하기 어려움

+

내부 관리용 Application 처럼 데이터 크기가 별로 크지 않은 상황에서 유용한 SQL 인듯.

- gon : 24년 3월 15일에 자택에서 회사 게이트웨이에 ssh로 접근이 안되는 문제를 해결 과정을 공유하여봅니다. +
이사전에는 본대로 게이트웨이에서 집의 현재 ip를 등록하면 ssh에 접속 할 수 있었습니다(rsa키는 다 맞추었다는 가정하에)  +
그런데 이사후 skt로 인터넷을 변경 이후에 게이트웨이에 ip를 등록시키고 ssh에 접근하는데 connetion timeout이 발생하며 접근이 되지않았습니다.  +
인터넷은 다 정상적으로 되지만 이상하게도 22번 port로만 요청을 하면 connetion timeout이 발생하였습니다.  +
인터넷에 검색해보니 skt에서 22번 포트를 막는다는 애기가있어 고객센터에 문의를 해보니  +
skt에서 22, 23, 80같은 port를 막는 경우도있다 하였는데 이경우는 내 인터넷으로 income일 경우만 막는것이었고  +
제 경우에는 22번 포트로 outgoing하는 경우를 막는거라 다른 상황이었습니다.  +
원인은 skt의 특정모뎀에서 아예 특정포트로 들어가고 나가는걸 둘다 막는 모뎀이 있다고 합니다(그게 하필 제가 걸린거고....)  +
그래서 모뎀만 변경하였는데 connetion timeout이 사라지고 정상적으로 접근이 가능하였습니다 
