= 본대로 서비스 소개
// Metadata:
:description: jd-bondaero
:keywords: Sir.LOIN, bondaero
// Settings:
:doctype: book
:toc: left
:toclevels: 4
:sectlinks:
:icons: font

[[we-are-hiring]]
== 동료를 찾습니다.
본대로 서비스를 함께 만들어 가실 분을 찾습니다.

[[service-introduction]]
=== '본대로' 란?

. 본대로는 무슨 서비스인가요?
+
저희는 육류 도매를 구매하는 고객 차원에서 다시 바라보고자 합니다.
+
기존의 육류 도매 서비스는 구매한 상품의 설명과 수령한 상품의 괴리가 커, 구매 고객님은 어느 정도의 뽑기운을 감수해야 했습니다. 저희 본대로는 이 문제를 해결하기 위해 구매 고객님에게 상품의 정확하고 다양한 정보를 컨텐츠로 제공하는 서비스입니다.

. 왜 육류 도매 시장에 뛰어들고자 하나요?
+
육류 도매 시장은 한국 기준으로만 해도 약 25조 정도에 달하는 큰 시장이에요. 우리가 초기에 집중하려는 시장인 한우 도매 시장도 연간 약 8조 정도에 달하는 정도의 큰 시장이죠.
+
육류 도매를 하는 고객 입장에서 가장 큰 불편함은 정보 탐색 자체의 어려움이죠. 내가 원하는 상품을 보유한 업체는 어디있는지, 쉽게 탐색할 장이 없으니 기존 거래처와의 거래를 유지하는 수 밖에 없는 경우가 대부분이에요. 판매자 입자에서도 수요를 잘 모아서 재고가 남지 않게 판매하는 생산설계를 하고 싶지만, 모든 구매자의 요청을 받아서 생산할 수 없다보니 비효율의 발생이 불가피한 경우가 많아요. 이 문제를 해결할 수 있는 서비스를 개발하고, 도매 거래의 투명성을 최대한으로 높이는 일에 집중하고자 해요.
+
물론 기존에 이 시장의 디지털 전환이 없던 것은 아니에요.
하지만 판매자 입장에서 만들어진 느낌이 강하고 구매 고객 입장에서의 불편한 점이 아직 많이 있어서 널리 쓰이고 있지 않아요. 기존 거래처와의 메신저 거래처럼 편리하고, 호텔 컨시어지 같이 친절한 경험을 준다면 시장을 뚫고 들어가서 확대할 수 있는 기회가 있다고 판단했어요.

. Sir.LOIN(설로인)은 왜 이 사업에 투자하고, 어떤 시너지가 있을까요?
+
설로인의 비전은 "고객이 설로인 브랜드를 믿고, 일정한 고기 경험을 누릴 수 있게 하는 것" 입니다.
+
위의 비전 실현을 위해서는 모든 프로세스가 다 중요하지만,
좋은 원육을 합리적 가격에 공급 받아야 한다는 전제가 매우 중요합니다.
이 전제가 실현되려면, 육류 도매 시장에서의 구매를 위한 정보 탐색이 훨씬 투명해져야 하는데, 그것을 "육쟁이 청년들" 을 통하여 이뤄내려고 하는 것이
설로인이 이 사업에 투자하는 이유입니다.
+
* 기본적인 시너지는 설로인도 육류 도매의 대표적인 구매자 고객이라는 점입니다.
설로인은 직접 많은 도매를 경험하면서 보고 느낀 불편함과 그 이유를 자세히 알고 있어요.
또한 많은 거래를 통해 신뢰가 쌓인 좋은 파트너 들이 많이 있고, 그 파트너분들을 초기 파트너로 모시기 유리한 발판을 제공해줄 수 있어요.
+
* 또한 판매자 입장에서 실제 구매자가 필요한 것이 무엇인지 많은 노하우를 알고 있어요.
설로인은 실제로 여러 레스토랑과 정육점에도 B2B 판매를 이미 진행하고 있어요.
설로인 상품을 사용하는 고객에 한정되지만, 실제 고깃집이나 정육점의 유통 특성과 구매 시 요구사항에 대해서 지속적으로 경험을 공유할 수 있어요.

[[people-aspects]]
=== 어떤 동료를 찾고 있나요?

* (호기심 천국) 
저희는 기본적으로 오지라퍼를 선호합니다. 우리가 잘하기 위한 모든 일에 관심을 가지고 어떤 방법으로라도 피드백을 자주 줄 수 있는 사람이어야 한다는 것입니다. 
+
물론 당연히 상대가 주는 피드백에 대해서 비판적 자세에서 수용할 수 있는 준비가 되어있는 사람이어야 한다는 것은 기본이겠죠.

* (끈기) 우리는 아직 완벽히 풀리지 않았던 문제를 푸는 팀이 될거에요.
물론 설로인의 경험에서 배울 수 있던 것으로 완전 맨땅에 헤딩은 아닐테지만, 아무래도 성공하기 까지 맞는 방법을 찾는데 여러 번의 시도가 필요할 수 있을거에요.
+
그 과정마다 좌절하지 않고 꿋꿋이 그리고 빠르게 새로운 시도를 도모할 수 있는 끈기와 에너지가 필요한 사람이었으면 좋겠어요.

* (집착) 끈질기게 한 점을 뚫고 나갈 수 있는 집착을 보여줄 수 있는 사람과 함께하고 싶어요.
그 집착은 고객과 고객의 만족, 그리고 고객의 편의성이 되었으면 해요.
그래서 정량적 데이터를 바탕으로 계속 개선하기 위한 의견을 내는 것이 기본이 되어야 해요.
+
* (왜) 저희는 문제를 정의하고, 그것을 해결해 나가는 과정은 모두 '왜' 에서 출발한다는 믿음을 가지고 있습니다. 따라서, 사소한 현상도 '왜' 벌어지는지를 끝까지 탐구하고, 이를 지식으로 전파할 수 있는 동료를 찾고 있습니다.

[[our-establishments]]
=== 설로인이 걸어온 길

. 2023년 06월   중소벤처기업부 '예비유니콘' 지원 대상자 선정 (link:https://platum.kr/archives/209462[관련기사 - Platum]), (link:https://zdnet.co.kr/view/?no=20230626163211[관련기사 - ZDNet Korea])
. 2022년 01월   설로인 구성원 110명 돌파
. 2021년 12월   기술혁신형 중소기업 인증
. 2021년 12월   자사몰 전년도 대비 가입자수 300% 성장
. 2021년 06월   시리즈B 투자유치 160억원
. 2020년 12월   성남물류센터 설립
. 2020년 07월   시리즈A 투자유치 40억원
. 2020년 03월   Hyper Aging 숙성 특허 출원
. 2019년 12월   설로인 다이닝 본점 설립
. 2019년 12월   미트 컴플렉스 압구정 본점 설립
. 2019년 08월   벤처기업 인증
. 2018년 10월   미슐랭스타 고객 유치
. 2018년 01월   온라인 커머스 런칭
. 2017년 09월   설로인 주식회사 설립

[[service-statistics]]
=== 본대로 서비스 연혁 및 현황

본대로 서비스는 런칭 첫달째부터 매출을 기록했습니다. 또한 런칭 이후 매출액이 꾸준히 증가하고 있습니다.

. 2023년 07월   서비스 누적 매출액 5억원 돌파
. 2022년 11월   육류 도매 서비스 '본대로' 런칭

[[jd-engineering]]
== 소프트웨어 엔지니어 Job Description
이런 분들이 오신다면 좋겠습니다!

* link:jd-backend.adoc[백엔드 개발자]
* link:jd-frontend.adoc[프론트엔드 개발자]
* link:jd-backoffice.adoc[백오피스(Admin) 개발자]
